### ISSUE TITLE
Generate thumbnails for videos

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#1005]
When ingested, video derivatives are made, but it would be nice if we could extract a thumbnail from the video.  We should be able to adapt Homarus to read Accept headers to know if it should make images or videos.  The ffmpeg command should be altered accordingly.  The logic would go roughly here: https://github.com/Islandora-CLAW/Crayfish/blob/master/Homarus/src/Controller/HomarusController.php#L113  I imagine in the long run we'll want to do audio derivatives this way too, so keep that in mind, even though it's certainly out of scope for this issue.

**Comment by dannylamb** [comment]
linking to https://github.com/Islandora-CLAW/CLAW/issues/929

**Comment by Natkeeran** [comment]
@dannylamb We discussed having a common approach to derivative creation.  Is that to be explored?  Or since we can customize the input parameters with actions, we should be good to with the approach stated here.  Please confirm.

**Comment by dannylamb** [comment]
The common approach we have now is re-using the camel routes to connect the derivative microservices back into the repository.  We've got that, but that's really only for adding new microservices.  For this we'll either have to adapt homarus or make a new action that has different Islandora Args.  It all comes down to the ffmpeg command you have to run to extract a thumbnail.

**Comment by Natkeeran** [comment]
@dannylamb 

Adding the jpeg_image2pipe format to the config, then passing appropriate params will create thumbnail image.  Example:
```
curl -H "Authorization: Bearer islandora" -H "X-Islandora-Args: -ss 00:00:01.000 -frames 1"  -H "Accept: image/jpeg" -H "Apix-Ldp-Resource:http://localhost:8080/fcrepo/rest/2019-05/test.mp4" http://localhost:8000/homarus/convert --output output.jpg
```

We can start with the above and then refine the logic to set more appropriate time frame later as in the 7.x stack.

I set up the context and action, it did not create it.  Need to troubleshoot that further.  But I do note that context that is setup to fire on any Service file can be problamatic.  Also, I am not sure if Alpaca is setup to handle this!

```
# managed by Ansible

homarus:
  # path to the ffmpeg executable
  executable: ffmpeg
  mime_types:
    valid:
      - video/mp4
      - video/x-msvideo
      - video/ogg
      - audio/x-wav
      - audio/mpeg
      - audio/aac
      - image/jpeg
    default: video/mp4
  mime_to_format:
    valid:
      - video/mp4_mp4
      - video/x-msvideo_avi
      - video/ogg_ogg
      - audio/x-wav_wav
      - audio/mpeg_mp3
      - audio/aac_m4a
      - image/jpeg_image2pipe
    default: mp4


fedora_resource:
  base_url: http://localhost:8080/fcrepo/rest

log:
  # Valid log levels are:
  # DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY, NONE
  # log level none won't open logfile
  level: DEBUG
  file: /var/log/islandora/homarus.log

syn:
  # toggles JWT security for service
  enable: True
  # Path to the syn config file for authentication.
  # example can be found here:
  # https://github.com/Islandora-CLAW/Syn/blob/master/conf/syn-settings.example.xml
  config: ../syn-settings.xml

```

**Comment by dannylamb** [comment]
@Natkeeran 

I just modified the validator in the form for `islandora_image` to accept image/jpeg, and it totally worked first time!  Too easy!!!

![Screenshot from 2019-05-07 10-58-04](https://user-images.githubusercontent.com/20773151/57305213-0fec9600-70b7-11e9-80c0-a4584522ca7b.png)

Needs some image styles, but hey :tada:

**Comment by dannylamb** [comment]
@Natkeeran^^ PRs are up.  Testing instructions in https://github.com/Islandora-CLAW/islandora_demo/pull/26
