### ISSUE TITLE
Unable to uninstall controlled_access_terms

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#1008]
When trying to uninstall controlled_access_terms to test this [PR](https://github.com/Islandora-CLAW/controlled_access_terms/pull/18), it is giving the following error:

```
    The Typed Relation field type is used in the following fields: node.field_linked_agent, taxonomy_term.field_relationships
    The Authority Link field type is used in the following field: taxonomy_term.field_authority_link
```

It seems like, the uninstalls are not cleaning up the configs completely.  Able to clean these using easy_install.

**Comment by seth-shaw-unlv** [comment]
It appears that any Drupal module that provides content types with custom field types face this issue. A user must remove any fields that use the field type _first_ and then uninstall the module. There is no way to tell core to go ahead and remove them for us. (Drupal Core doesn't want to enable something that could destroy data.)

We could make a "nuke from orbit" button somewhere to purge all of our Vocabularies but it should include big glaring warnings that they will be deleting all their terms if they do it.
