### ISSUE TITLE
Getting Ansible error in claw-playbook

### ISSUE THREAD

**Issue by paulclifford** [Islandora-CLAW/CLAW#1016]
When I try to 'vagrant up' on the current claw-playbook, I'm getting the following error:

`TASK [Islandora-Devops.fcrepo : Download fcrepo war] ***************************
Thursday 31 January 2019  15:57:37 -0500 (0:00:00.780)       0:19:43.228 ****** 
fatal: [default]: FAILED! => {"changed": false, "dest": "/var/lib/tomcat8/webapps/fcrepo.war", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://github.com/fcrepo4-exts/fcrepo-webapp-plus/releases/download/fcrepo-webapp-plus-5.0.0/fcrepo-webapp-plus-5.0.0.war"}`

**Comment by whikloj** [comment]
Hmm I thought I had taken care of that. I'll have a look.

**Comment by whikloj** [comment]
@paulclifford Can you try to delete the contents of your claw-playbook `roles/external` directory and try `vagrant up` again?

**Comment by quladmin** [comment]
Thanks, that did the trick!

**Comment by paulclifford** [comment]
Thanks, that did the trick!
