### ISSUE TITLE
Set the site name on the Vagrant to "Islandora 8"

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#1020]
Currently, the CLAW Vagrant uses the site name "Islandora-CLAW". We should set the name to "Islandora 8" to reflect the shift to using that name prior to the release.

The drush command `drush -y config-set system.site name "Islandora 8"` appears to do the trick, which can be run in https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml.

**Comment by bryjbrown** [comment]
@mjordan @dannylamb https://github.com/Islandora-Devops/claw-playbook/pull/92 fixes this, so this issue technically closed but grepping through the codebase there's still a LOT of references to CLAW everywhere. 

Should we have a larger umbrella issue for de-CLAWing the codebases?

**Comment by whikloj** [comment]
@bryjbrown yes I think a larger ticket would be in order.

**Comment by mjordan** [comment]
@bryjbrown once you open the new ticket, can you close this one, since the #92 has been merged?

**Comment by mjordan** [comment]
Sorry, I assumed @bryjbrown would open the ticket - I or @whikloj  can do it if you want. Let us know.

**Comment by whikloj** [comment]
Closing
