### ISSUE TITLE
Automatically Generate Node Titles

### ISSUE THREAD

**Issue by dmoses** [Islandora-CLAW/CLAW#103]
As I'm working with the content type I'm thinking about a few things.  At the moment we have Drupal's default Title field and we have another DC Title field.  I am wondering if it would make sense to:

 1. Use the content of the DC Title field to automatically populate the Drupal Title field.
   - use the Drupal [Title module](https://www.drupal.org/project/title) to turn the field into a field that we can do something with.
   - use [Automatic Entity Label](https://www.drupal.org/project/auto_entitylabel) and Token to populate the Title using DC Title
 2. Hide the Title (using auto entity lable)

There may be problems ... DC Title allows multiples, it is a textarea and not a text field field.

**Comment by dannylamb** [comment]
closing d7 tickets
