### ISSUE TITLE
Creating Media makes an orphaned Media

### ISSUE THREAD

**Issue by rosiel** [Islandora-CLAW/CLAW#1038]
When I create a node, then click the media tab, then create a media object, I expect it to be linked to the node that I navigated from.

however, if I don't explicitly fill out the "Media of" field then it won't get linked to anything. I thought this field used to default to the node that I navigated from. Currently (sparkling new playbook cloned feb 27 2019) that field defaults to a blank.

Also, if I realize the error and go back in and link the Media to the node, then derivatives don't trigger. (e.g. even if the node is type "Image" and the media is type "Image" and has use "Original File" the only way I can get derivatives is if I successfully link the media to the node when i create the Media).

Two issues. Not sure if they're bugs or user error, but if it's user error then there's some documentation/guidance piece that needs to be in place.

**Comment by whikloj** [comment]
@rosiel I think this was just fixed https://github.com/Islandora-CLAW/CLAW/issues/1028

You might need to rebuild your Islandora 8 box?

**Comment by seth-shaw-unlv** [comment]
Ninja-ed by @whikloj.

@rosiel, the #1028 patch was a single line change to the source. I recommend just updating that line on your box instead of rebuilding.

**Comment by rosiel** [comment]
Aaargh, sorry, didn't search all issues properly. Thanks @seth-shaw-unlv  and @whikloj!
