### ISSUE TITLE
Composer module updates

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#1052]
With the Core upgrade to 8.6.10 (#1034) the following modules we install are out of date:
- Devel (Unsupported): 8.x-1.2 → 8.x-2.0
- Migrate Plus: 8.x-4.0-beta3 → 8.x-4.1
- Migrate Tools: 8.x-4.0-beta3 → 8.x-4.1

**Comment by seth-shaw-unlv** [comment]
Talking through this: Devel is set in [claw_playbook](https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L9), but the migrate plugins are set in [the islandora composer file](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/composer.json#L27-L28). So, to get that loaded during the claw playbook provisioning we need to point the claw playbook at an islandora_demo branch that points to the respective islandora branch. Joy.

**Comment by seth-shaw-unlv** [comment]
PRs ready for whoever wants to try 'em. They can be tested together. Check the PRs' 'Additional Notes' section.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/claw-playbook/commit/3281a1d3bff632bbb6a61c938a36f670cc0dd130 and https://github.com/Islandora-CLAW/islandora/commit/be09b4340a72e31272ef855c2046817243907ce3
