### ISSUE TITLE
Controlled Access Terms blocks installing jsonapi module

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#1054]
Due to the way it builds routes/output based on entity reference fields, something about controlled access terms default config breaks jsonapi.  Double check the config and re-export it to make sure you can install jsonapi.

**Comment by mjordan** [comment]
@ajstanley is this related to the issue you identified on the islandora-dev email group?

**Comment by dannylamb** [comment]
@mjordan It's about that, and I have a fix.

**Comment by dannylamb** [comment]
@mjordan @ajstanley  Features re-export that seems to do it ^^  The field storage and field definition were out of alignment for the "Broader" entity reference field.
