### ISSUE TITLE
Use custom entities and bundles for managing fedora objects in drupal

### ISSUE THREAD

**Issue by DiegoPino** [Islandora-CLAW/CLAW#106]
Currently we are using content types(bundles), based on the drupal node entity to manage the drupal implementation of a fedora4 object. 

Using custom entities, gives us some further flexibility on what/how:
 * properties (for the entity definiton)
 * fields (from bundles)
 * rdf mapping and 
 * handlers (probably the most important part) 

for this entities and it's derived content types (which by the way are the bundles) 

Custom entities get their own db table (which is also good for backups) and CRUD handlers. We can also directly influence field dependencies (like rdf properties that point from one content to another, like collection membership), the way this entities are displayed based on bundles(independent of Views, not excluding) and other benefits.

Some further info: http://cgit.drupalcode.org/entity/tree/README.txt?id=refs/heads;id2=7.x-1.x

**Comment by dmoses** [comment]
The fields for the entities will need to be well defined. In Drupal once you add content using a particular content type you are basically 'locked in' to whatever was defined (eg. you can't change a field type from text field to link field).
