### ISSUE TITLE
Houdini has dependency on Fedora

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#1067]
It appears that Houdini has a dependency on API-X, which implies a dependency on Fedora. But Fedora is optional in the Islandora 8 stack. Does this mean that an Islandora 8 instance must use Fedora if it wants to use Houdini?

**Comment by mjordan** [comment]
Same question for Hypercube, which also appears to depend on API-X.

**Comment by mjordan** [comment]
Are https://github.com/Islandora-CLAW/CLAW/issues/1029#issuecomment-465675956 and later comments relevant to this question? Maybe we should document the relationship between Islandora and Fedora, and explain what "Fedora is optional" means in some detail appropriate for repo admins.

**Comment by whikloj** [comment]
Where does Houdini have a dependency on API-X? It uses the Apix-Ldp-Resource header to specify the location of the resource to get as it was meant to use API-X, but I don't believe it actual needs API-X as currently API-X is not working in claw-playbook but Houdini still does.

**Comment by mjordan** [comment]
Its [readme](https://github.com/Islandora-CLAW/Crayfish/tree/master/Houdini) says "Houdini is meant for use with API-X".

**Comment by whikloj** [comment]
Yes and it is "meant" to be used with API-X in that it is designed as an API-X service. But API-X is just a way to register services that can act upon Fedora resources. The actual service is still a microservice. [These static files](https://github.com/Islandora-CLAW/Crayfish/tree/master/Houdini/static) that are used to register the API-X service is what is required to make it "work" with API-X.

**Comment by mjordan** [comment]
Great, thanks for the clarification. Is the same true for Hypercube? I'm asking because I think we need to clarify (and document) what the implications are for not using an underlying Fedora in an Islandora 8 repository. If all of our microservices work the same regardless of whether there is an underlying Fedora, we need to document that, and conversely if some do not, we also need to document that. Maybe I should open a meta issue on Fedora/Fedora-less?

**Comment by whikloj** [comment]
Yes, for more information on API-X this [technical overview](https://github.com/fcrepo4-labs/fcrepo-api-x/blob/master/src/site/markdown/apix-design-overview.md) explains how it is designed to work.

**Comment by mjordan** [comment]
Linking to an existing issue on this, #945 .

**Comment by dannylamb** [comment]
Basically, as long as the resource in the Apix-Ldp-Resource header is available via GET using the same Authorization header as in the request to the microservice, it'll work.  That's why we always set Apix-Ldp-Resource to be the Drupal file URL, so the JWT will work no matter where it is (e.g. AWS bucket, DO space, whatevs).  You set up the details for those vendor specific sort of things with flysystem and  your individual users don't need to know those credentials in order to generate derivatives.

**Comment by whikloj** [comment]
@mjordan is this resolved or is there more this is needed for?

**Comment by mjordan** [comment]
@whikloj yes, I think my initial question has been answered. I have created the meta issue I mentioned (#1085) and will close this one.
