### ISSUE TITLE
Solr config drupal-6.4-solr-6.x doesn't match Solr 7.1.0

### ISSUE THREAD

**Issue by kayakr** [Islandora-CLAW/CLAW#1069]
https://github.com/Islandora-Devops/claw-playbook/blob/master/solr.yml references `geerlingguy.solr` that used to default to `7.1.0` but now defaults to `7.4.0` (see https://github.com/geerlingguy/ansible-role-solr/blob/master/defaults/main.yml). Either way, the solr config that gets copied across by `drupal.yml` is for solr 6.x (see https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml#L68).

Is there a particular reason for not using the `drupal-6.5-solr-7.x` solr config ?

**Comment by seth-shaw-unlv** [comment]
[That specific line was added in November 2017](https://github.com/Islandora-Devops/claw-playbook/commit/3cccf9327a1802a22159ad3ca0fe6c8a9b0b0188) but the solr 7.x configs weren't made available by the module until June 2018 (8.x-2.0). 

We [now reference 8.x-2.0](https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L12), so it should be a simple PR changing the "6" to a "7" to fix that.

**Comment by kayakr** [comment]
@seth-shaw-unlv Thanks. FWIW, the solr 7.x configs are working ok on my local instance with Search API Solr 8.x-2.6.

I had to change `/var/solr/data/CLAW/conf/solrcore.properties` to set `solr.install.dir=/opt/solr/`.

Contrary to https://www.drupal.org/project/search_api_solr/issues/3005186#comment-12807969 I had to change schema.xml `_version_` to
`<field name="_version_" type="plong" indexed="true" stored="true"/>`

**Comment by Natkeeran** [comment]
@kayakr 
Can you please provide some additional context about the following change (i.e what that is required).

`<field name="_version_" type="plong" indexed="true" stored="true"/>`

**Comment by kayakr** [comment]
@Natkeeran It was a while ago now, but when I tried to reload the Solr core with the 7.x config it reported a Java exception: `Caused by: java.lang.IllegalStateException: unexpected docvalues type NONE for field '_version_' (expected=NUMERIC). Re-index with correct docvalues type."`

**Comment by seth-shaw-unlv** [comment]
@kayakr and @Natkeeran, it doesn't look like loading the 7.x config at install needs the field change. My testing for Islandora-Devops/claw-playbook/pull/107 didn't show any issues and the SOLR logs didn't show any errors. 

Feel free to re-open the ticket if it pops up again.
