### ISSUE TITLE
geolocation 8.x-2.0-beta1 no longer supported

### ISSUE THREAD

**Issue by kayakr** [Islandora-CLAW/CLAW#1077]
https://github.com/Islandora-CLAW/controlled_access_terms composer.json references "drupal/geolocation": "^2.0" but this is no longer supported. The new version is 8.x-3.0-rc1 (2019-Apr-05).

**Comment by seth-shaw-unlv** [comment]
Resolved by Islandora-CLAW/controlled_access_terms/pull/22
