### ISSUE TITLE
EDTF Date doesn't accept L0 date range "1964/2008"

### ISSUE THREAD

**Issue by kayakr** [Islandora-CLAW/CLAW#1086]
According to https://www.loc.gov/standards/datetime/edtf.html L1 includes L0, and L0 Time Interval can be of format "1964/2008" but if I enter that value I get an error "Could not parse the date '1964/2008' Years must be at least 4 characters long."

**Comment by dannylamb** [comment]
@kayakr Thx so much for using the software and reporting issues.  I owe you :beers: if we ever meet IRL.

**Comment by seth-shaw-unlv** [comment]
@kayakr Can you check the field widget settings and confirm "Permit date intervals" is selected?
<img width="1293" alt="Screen Shot 2019-04-15 at 7 23 42 AM" src="https://user-images.githubusercontent.com/29869988/56140311-7f0b1a80-5f4f-11e9-8edf-998e6fe41063.png">. This may be a case where we need to change the default settings to avoid confusion.

**Comment by kayakr** [comment]
@seth-shaw-unlv Ah, that widget setting wasn't enabled, thanks. I _did_ check the Readme before posting (https://github.com/Islandora-CLAW/controlled_access_terms). I wonder if the readme could be updated: (a) rephrase or remove "EDTF was incorporated in ISO 8601-2019 with some modifications which will be supported in a future update." now that https://github.com/Islandora-CLAW/CLAW/issues/995 has landed, and (b) mention the EDTF widget settings.

**Comment by seth-shaw-unlv** [comment]
Resolved via Islandora-CLAW/controlled_access_terms/pull/25
