### ISSUE TITLE
Some taxonomy terms are not checked to be translatable

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#1092]
By default, Islandora 8 enable translation of taxonomy vocabularies.  However, only the following are checked to be currently translatable:
* Islandora Models, 
* Islandora Media Use
* Islandora Access

While, other taxonomy vocabularies such as Subject, Resource Type, Person, Family etc are not checked to be translatable.

**Comment by dannylamb** [comment]
@Natkeeran @seth-shaw-unlv @elizoller Are we good to close this now that https://github.com/Islandora-CLAW/controlled_access_terms/pull/23 has landed?

**Comment by elizoller** [comment]
Islandora-CLAW/controlled_access_terms#23 should make the remaining fields on corporate_body, family, geo_location, person, resource_type, and subject translatable. If this ticket was meant to cover additional taxonomies or fields, then I'm not sure.

**Comment by Natkeeran** [comment]
Looks good, thank you @elizoller @seth-shaw-unlv
