### ISSUE TITLE
make islandora_search theme independent 

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#1100]
[This block](https://github.com/Islandora-CLAW/islandora_demo/blob/8.x-1.x/modules/islandora_search/config/install/block.block.exposedformsolr_search_contentpage_1.yml#L9) is dependent on carspace theme.  However, when we try to enable drupal modules, the theme is not installed.  

The block should not be dependent on theme.  The block should be made available, and the user would have to place it in an existing region.

**Comment by dannylamb** [comment]
I'm reading this as "Remove the block yml and add install instructions / point to documentation".

**Comment by Natkeeran** [comment]
@dannylamb 

Hmm, ok.  Not sample block is good.  

Seems like there is no way to define a block without tying to a theme, is that correct?

Simply adding islandora_search to here https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L48 does not work, because it needs carspace theme.

We would have to enable it after here: https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml#L47, which is not clean, but should work.

**Comment by Natkeeran** [comment]
This issue has been addressed.
