### ISSUE TITLE
Is there any way to view the file checksum from the drupal UI?

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#1102]
Is there any way to view the file checksum from the drupal UI?

**Comment by mjordan** [comment]
Checksums managed by Riprap or by Drupal?

**Comment by Natkeeran** [comment]
Drupal.  We have filehash enabled, thus I assume it calculates it.  However, not sure where that info is stored.

If we have another way to display this info, that should be sufficient too.

**Comment by mjordan** [comment]
Don't know off top of my head but if the filehash module doesn't provide a way, you could write a field plugin for the Media view like the one I have for Islandora Riprap (https://github.com/mjordan/islandora_riprap/blob/master/src/Plugin/views/field/RiprapResults.php) to grab the checksum and render it. Replying on my phone now but can provide more info tomorrow if you want.

**Comment by dannylamb** [comment]
IIRC it stores checksums in a separate table, but then stuffs them into the file entity early on so that it's available there (and not coming from a bookeeper or 'manager' service that you have to inject in).  I think it also makes it available through views, so you could alter the main File view (admin/content/file) to include the hash in the results.  Or just make a custom one.  

And this is pure speculation on my part, but if you wanted it in the UI on Media display, maybe a pseudo field?

**Comment by Natkeeran** [comment]
@dannylamb 
http://localhost:8000/admin/content/files, yes able to add the checksum.

Is there a way to provide checksum and check it when a file gets uploaded via UI?  Not an urgent issue.  I remember that if a file or media gets created via REST, it will check the checksum.

**Comment by dannylamb** [comment]
The `filehash` module `file_validate` hook to check the checksum of an uploaded file against existing checksums: https://git.drupalcode.org/project/filehash/blob/8.x-1.x/filehash.module#L92 I imagine you could alter the form widget (or make another widget altogether) that has a text field where you can put a checksum.  Then implement the `file_validate` hook and check for mismatch.

**Comment by mjordan** [comment]
Also relevant is #867.

**Comment by dannylamb** [comment]
Also, just realized that there's a field formatter for files included in the `filehash` module that can be used to render file fields as checksums.  So we can display it on the Media as well, np.

**Comment by Natkeeran** [comment]
@mjordan @dannylamb 
Closing this ticket as 867 address this issue.
