### ISSUE TITLE
Does openseadragon support responsive view?

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#1105]
It seems like the width of the viewer is not adjusted for responsive mode.  Does openseadragon supports responsive view?

**Comment by seth-shaw-unlv** [comment]
[Open Seadragon](https://openseadragon.github.io/) itself can be responsive; but [the CSS provided by islandora/openseadragon](https://github.com/Islandora-CLAW/openseadragon/blob/8.x-1.x/css/openseadragon.css#L2) has a set width of 600px.

Playing around with it a bit in Chrome's developer tools shows that you can remove the width descriptor and it will resize just fine (it inherits a 100% width). You _do_ need a set height; but it doesn't have to be 640px. 

A repository can locally override a module's CSS although we might consider just removing the width descriptor as a reasonable default.

What do you think, @whikloj?

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/openseadragon/commit/d4d950c1733cd6abaf8e3d364118437275cf920b
