### ISSUE TITLE
Show fedora pseudo URI for File in the Media display UI

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#1109]
[This PR ](https://github.com/Islandora-CLAW/islandora/pull/124)enabled Fedora URI to be viewed in the Drupal using a pseudo field.  There has been key changes with respect to how things in Drupal get indexed in Fedora.  The changes are reflected in the Image 2 here: https://drive.google.com/file/d/1JmhWbcR8yHCzz879QWyqZ1lszuIsYcNn/view.

Basically, media node themselves are NOT indexed in Fedora.   RDF Resources point to Non RDF Resources=Files.  Thus, media related info can be found in the metadata for files.  For example: `http://localhost:8080/fcrepo/rest/filepathinfedora/fcr:metadata`

There is one - to - one relation between Media and File.  Thus, it was suggested by Seth and Danny that we show the File's Fedora URI in the Media display UI.  This requires some changes related to the above noted PR.  

@whikloj

**Comment by dannylamb** [comment]
@Natkeeran @whikloj https://github.com/Islandora-CLAW/islandora/pull/126 will address this by putting the Media's uri in Fedora in the pseudo field.  I wasn't sure that's exactly where we landed yesterday so  I went the full mile.  I can peel it back to just the file URI no prob if that's more of what folks are expecting.

**Comment by seth-shaw-unlv** [comment]
The Media's URI in Fedora is what I would expect based off yesterday's IRC conversation.
