### ISSUE TITLE
Islandora has too many Type vocabularies.

### ISSUE THREAD

**Issue by rosiel** [Islandora-CLAW/CLAW#1113]
This is a discussion ticket. 

If I create an islandora object, I have two places to say "what type it is":
"Resource Type" field, optional
![Screen Shot 2019-05-06 at 5 03 30 PM](https://user-images.githubusercontent.com/1943338/57251767-01ec3600-7021-11e9-9fbe-6f25308201ef.png)

And "Model" (under "System"), mandatory:
![Screen Shot 2019-05-06 at 5 03 43 PM](https://user-images.githubusercontent.com/1943338/57251787-0fa1bb80-7021-11e9-8e03-359c8f28b8f1.png)

If I select "Image" on both, I get (abridged jsonld):

```{
  "@graph": [
    {
      "@id": "http://localhost:8000/node/1?_format=jsonld",
      "@type": [
        "http://pcdm.org/models#Object",
        "http://purl.org/coar/resource_type/c_c513"
      ],
...
      "http://purl.org/dc/terms/type": [
        {
          "@id": "http://localhost:8000/taxonomy/term/5?_format=jsonld"
        }
      ],
    },
...
    {
      "@id": "http://localhost:8000/taxonomy/term/5?_format=jsonld",
      "@type": [
        "http://schema.org/Thing"
      ]
    }
  ]
}
```

The "Resource Type" is supposed to be, IIUC, the "metadata" declaration of what kind of thing it is - similar to typeOfResource in MODS, coming from a controlled list. The list I have from MIG is [here](https://docs.google.com/spreadsheets/d/18u2qFJ014IIxlVpM3JXfDEFccwBZcoFsjbBGpvL0jJI/edit#gid=25390054), and it looks similar but not exactly like the existing Resource Types available. If they're supposed to be the same list, then we have URIs available in that link to do the sameAs. (Above, `taxonomy/term/5` is "Image" in the Resource Types vocabulary).

The "Model" field relates to what happens with derivatives, context, etc. It seems to be doing something special in the JSONLD - not only is it mapping its value to @type instead of a "normal" predicate, it's swapping out `taxonomy/term/24` for its external URI, `http://purl.org/coar/resource_type/c_c513`.

Is this swapping-out a thing that we can do in the mapping yml? 

Choosing the same thing twice is a nonsensical UI. Three times, if you count: 
1. choose a resource type "image"
1. choose a model "image"
1. choose "image" from the available media types

Can we make the user pick a model first, then pre-populate the sensible resource type?

Or could we merge the two taxonomies so the terms so the resourceTypes are the actionable elements?

**Comment by Natkeeran** [comment]
@rosiel If feel this question has been reasonably answered, please consider closing this ticket.
