### ISSUE TITLE
Update controlled_access_terms's dependency on drupal/name to dev branch

### ISSUE THREAD

**Issue by alxp** [Islandora-CLAW/CLAW#1120]
Controlled Access Terms dependency on drupal/name

The [name](https://drupal.org/project/name) module has not had a release in over a year. The controlled_accesss_term module specifies a dependency in composer.json locked to the ^1.0-RC version. I would like to switch this to the -dev version so it does not conflict with a module in my codebase that is using a service added to the -dev release of name, the Name Formatter Service. As described on the drupal.org project page:

> Developers
> Requires dev version 20th March 2018.

> Easily format a name or name list with a name formatter service:

```php
\Drupal::service('name.formatter')->format($name_array, 'format_id');
\Drupal::service('name.formatter')->formatList($names_array, 'format_id', 'list_format_id');
```

**Comment by seth-shaw-unlv** [comment]
Resolved via Islandora-CLAW/controlled_access_terms/pull/26
