### ISSUE TITLE
openseadragon adding additional information into url with languages other than english

### ISSUE THREAD

**Issue by bstennett** [Islandora-CLAW/CLAW#1121]
We are running into an issue with openseadragon rendering iiif urls in specific conditions.

Here is an example:

https://dams-claw-prod.lib.utexas.edu/CIDCA/50239322-1e69-4606-8d5d-94e4d20ba1ba?lang=pt-br

If you look at the console view of this page it returns a 404 error for the content. This error is only visible when the additional language option (?lang=) is added to the end of the drupal url and only when not logged into to Drupal. 

The console output specifically shows this error message:
AJAX request returned 404: https://dams-claw-prod.lib.utexas.edu:444/cantaloupe/iiif/2/https%3A%2F%2Fdams-claw-prod.lib.utexas.edu%2Fsites%2Fdefault%2Ffiles%2F2019-04%2Fcidca_lai_aal_19410102_02.png

Here is an example of what it looks like without the error:

https://dams-claw-prod.lib.utexas.edu/CIDCA/07fde3f9-d5f1-4842-86f3-519a07827c04 
It appears to be adding extra information into the url that is causing it to render a 404 error.

**Comment by rangel35** [comment]
the ?lang=pt-br is from the multilingual modules, this only occurs when "anonymous" users are looking  at the object, if you are logged in even as just an authorized user, there is no problem, it is only when not logged in (which will be true for the general public) that the issue occurs

**Comment by dannylamb** [comment]
@bstennett @rangel35 We sorted out our 'langcodes in urls when they shouldn't be there' issues during the 1.0.0 release.  So maybe this one is fixed?  If not, it might look different.  Anyway, let me know.  If it's not resolved, I can probably hunt it down and fix it the same way I did with the other url/langcode issues.

**Comment by rangel35** [comment]
thanks Danny, we are installing a test instance with the latest release, so we will test this soon.

**Comment by seth-shaw-unlv** [comment]
Linking #1226 as they seem to be related, if not duplicated.

**Comment by rangel35** [comment]
@dannylamb @Natkeeran   I tested with release 1.0 and this is still an issue

when changing languages as an anonymous user the openseadragon viewer fails to display the image but when logged in as an authenticated user (or above) the display works fine...I created a testuser with the same permissions as the anonymous users and it could view when the anonymous user could not.
