### ISSUE TITLE
Controlled Access Terms emitting PHP warnings and notices

### ISSUE THREAD

**Issue by kayakr** [Islandora-CLAW/CLAW#1123]
e.g. EDTF Date field value of 1962 generates
* Warning: Declaration of Drupal\controlled_access_terms\EDTFConverter::dateIso8601Value(array $data) should be compatible with Drupal\rdf\CommonDataConverter::dateIso8601Value($data) in require() (line 10 of modules/contrib/controlled_access_terms/src/EDTFConverter.php).
* Notice: Undefined offset: 4 in Drupal\controlled_access_terms\EDTFUtils::iso8601Value() (line 336 of modules/contrib/controlled_access_terms/src/EDTFUtils.php).
* Notice: Undefined offset: 4 in Drupal\controlled_access_terms\Plugin\Field\FieldFormatter\EDTFFormatter->formatDate() (line 209 of modules/contrib/controlled_access_terms/src/Plugin/Field/FieldFormatter/EDTFFormatter.php).
* Notice: Undefined offset: 4 in Drupal\controlled_access_terms\Plugin\Field\FieldFormatter\EDTFFormatter->formatDate() (line 209 of modules/contrib/controlled_access_terms/src/Plugin/Field/FieldFormatter/EDTFFormatter.php).

**Comment by kayakr** [comment]
I've offered a PR at https://github.com/Islandora-CLAW/controlled_access_terms/pull/27 to remove the `array` type hint that conflicts with `CommonDataConverter` parent class.

**Comment by kayakr** [comment]
Regarding the PHP notice for line 336 in EDTFUtils.php, iso8601Value() receives $edtf="1962" and $parsed_date=
```Array
(
    [0] => 1962
    [1] => 
    [2] => 1962
    [3] => 1962
)
```
There is no value at `$parsed_date[EDTFUtils::YEAR_EXPONENT]` where YEAR_EXPONENT is set to 4.

**Comment by seth-shaw-unlv** [comment]
@kayakr, thanks for making an issue for these. I've kept kicking them down the road, but I'll see if I can address some of them this week (unless you beat me to it).

**Comment by seth-shaw-unlv** [comment]
Resolved by Islandora-CLAW/controlled_access_terms/pull/28
