### ISSUE TITLE
PHP notices from OpenSeadragon admin/display

### ISSUE THREAD

**Issue by kayakr** [Islandora-CLAW/CLAW#1124]
OpenSeadragon settings show numerous PHP notices, e.g. http://localhost:8000/admin/config/media/openseadragon

- Notice: Undefined index: fit_to_aspect_ratio in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 108 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: compositeOperation in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 180 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: placeholderFillStyle in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 215 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: minZoomLevel in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 231 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: maxZoomLevel in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 239 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: navigatorTop in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 698 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: navigatorLeft in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 706 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: navigatorHeight in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 714 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: navigatorWidth in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 722 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: referenceStripHeight in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 945 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).
- Notice: Undefined index: referenceStripWidth in Drupal\openseadragon\Form\OpenSeadragonSettingsForm->buildForm() (line 953 of modules/contrib/openseadragon/src/Form/OpenSeadragonSettingsForm.php).

OpenSeadragon shows PHP notice:
- Notice: Undefined index: fit_to_aspect_ratio in template_preprocess_openseadragon_formatter() (line 95 of modules/contrib/openseadragon/openseadragon.module).

**Comment by seth-shaw-unlv** [comment]
All the ones I've looked at so far are due to missing defaults in openseadragon.settings. Two options: first, add an entry for each of them in the settings file, or second, check in the form code if it is set and provide a blank value if missing.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/openseadragon/commit/03610eda7fed73cd05985b0c14f99acd84a36ba4
