### ISSUE TITLE
OpenSeadragon 'Controls Fade Delay' settings duplicated

### ISSUE THREAD

**Issue by kayakr** [Islandora-CLAW/CLAW#1125]
visit http://localhost:8000/admin/config/media/openseadragon, Controls Fade Delay field label exists twice.
See https://github.com/kayakr/openseadragon/blob/8.x-1.x/src/Form/OpenSeadragonSettingsForm.php#L751 and
https://github.com/kayakr/openseadragon/blob/8.x-1.x/src/Form/OpenSeadragonSettingsForm.php#L767

**Comment by whikloj** [comment]
Yup that would a **mea culpa** from me. 🙇

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/openseadragon/commit/03610eda7fed73cd05985b0c14f99acd84a36ba4
