### ISSUE TITLE
Configure Gemini URL in Islandora Settings for playbook

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#1129]
Now that we can display a link from Drupal to Fedora it would be nice if that was enabled by default in the claw-playbook.

This work would be to add the default gemini url and enable the pseudo field on Repository Item and Image, File, Audio, Video media.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/a6c89adbbe5b09b2f22a39c12ca27d8da1b78240 and https://github.com/Islandora-Devops/claw-playbook/commit/4d83cd6eafafef7848ffa0f378b1be05a4c2fd80
