### ISSUE TITLE
Provide a Context condition that detects a file's mimetype

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#1138]
A Context condition that detects a file's Mime type would be useful, for example, to create a Context that displayed a file of a specific Mime type using a specific view mode.

**Comment by mjordan** [comment]
As discussed at the June 5 Tech call, I will create this condition and open a PR.

**Comment by kayakr** [comment]
@mjordan You may be across this already by the code in https://www.drupal.org/node/3055302 #4 could be relevant to you.

**Comment by mjordan** [comment]
@kayakr thanks for the pointer. Turns out I don't need to detect the MimeType, I can get it using the `$file->getMimeType()` method from `Drupal\islandora\MediaSource\MediaSourceService`. I'll be issuing a PR as soon as I can get past #1179 so feel free to comment on my implementation there if you want.

**Comment by mjordan** [comment]
Closing since https://github.com/Islandora-CLAW/islandora/pull/145 has been merged.
