### ISSUE TITLE
Provide breadcrumbs based on a chain of member_of relationships

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#1141]
Breadcrumbs, by default, follow the URL pattern of a node but our repository item hierarchies (collections, sub-collections, items, and item parts, etc.) may not be reflected in the alias/paths. In these cases items should have breadcrumbs based on their member_of relationships.

PR available at https://github.com/Islandora-CLAW/islandora/pull/132

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/islandora/commit/53d977e434bed3197f19ab7815448e5551428c20
