### ISSUE TITLE
Enabling the Locale module will cause fedora fields to not be populated.

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-CLAW/CLAW#164]
When Karaf puts to Drupal to update the node, it takes the configured language into account.

**Locale not enable:**
"field_fedora_path":{"und":[{"value":"http:\/\/localhost:8080\/fcrepo\/rest\/66\/cc\/f4\/06\/66ccf406-f682-4d31-b08e-a99c049cc7b7"}]}

**Locale enabled and language set to english:**
"field_fedora_path":{"en":[{"value":"http:\/\/localhost:8080\/fcrepo\/rest\/0a\/57\/68\/f0\/0a5768f0-20ba-473b-bd76-887edbd165c0"}]}

Problem is the field does not update when any language other than no langage (und) is set for the field and so it's ignored.

**Comment by dannylamb** [comment]
closing d7 related tickets since we're moving to d8
