### ISSUE TITLE
Add pcdm:memberOf property on objects added to a collection

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#184]
Currently we generate pcdm:hasMember using the members indirect container. But we do not add the reverse property to all the objects.

**Comment by DiegoPino** [comment]
Do we need the reverse? @whikloj if we add this, then no more server managed(LDP) predicates. I can live without the inverse for now, tripplestores don't need it if the child resource is in the same server as the collection resource.

**Comment by whikloj** [comment]
It could save us having to do more SPARQL queries to tell where everything belongs. If we have the property on the pcdm:Object then we don't have to do a query of the triplestore for reverse pcdm:hasMember properties or for the ore:proxyFor proxies.

**Comment by bryjbrown** [comment]
@whikloj It looks like this issue was created before PDX was a separated from Crayfish. Should this functionality still be contained in Crayfish, or would this now be in PDX's CollectionService and/or ObjectService?
