### ISSUE TITLE
Don't overwrite the microservices configuration files, provide an example instead.

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#204]
Remove the `settings.dev.yml` and `settings.yml` from github and add an example configuration file.

**Comment by DiegoPino** [comment]
@whikloj and add a readme file to each microservice also (maybe?). I would leave the settings.dev.yml in place?

**Comment by whikloj** [comment]
But then they (the settings.dev.yml) will be overwritten by each new `git pull`, I think we are better to leave the existing configs in place and update our `example.settings.yml`. 
But I agree that a ReadMe for each service is probably about due.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/CLAW/commit/447d45eb7fd09f49a636768ab78ab93e5f4a7e5f
