### ISSUE TITLE
Use FITSservlet to extract Technical metadata

### ISSUE THREAD

**Issue by DiegoPino** [Islandora-CLAW/CLAW#212]
Basically under the concept of reuse instead of recode:
https://github.com/harvard-lts/FITSservlet
Since we are running Fedora4 inside Tomcat it should be easy to integrate.
propesed Workflow: 
Put NonRDFSource into Fedora4.
Trigger via Camel FITS Extraction if possible based on Formats
Transform output to Ebucore and EXIF RDF tripples
Use Microservices to PATCH metadata to pcmd:File

**Comment by acoburn** [comment]
@DiegoPino this could be a possible new service for `fcrepo-camel-toolbox`, no?

**Comment by DiegoPino** [comment]
@acoburn completely! At least until the "Transform output to Ebucore and EXIF RDF tripples" which i was about to define as php (ups!). But we can do it in a more general language of course.

**Comment by acoburn** [comment]
@DiegoPino I'm just (selfishly) thinking that I'd want this sort of service, independent of a running CLAW impl

**Comment by DiegoPino** [comment]
Aha! Well, you will have to run Claw eventually! (joking). Makes sense, i can built most of the stuff to be as independent as possible to CLAW, but i'm a lot faster(and more reliable) doing this in camel+php than java.
Also since (new issue of course) i have been playing with derivative creation with Camel in the last weeks, i was thinking of having a Derivative definition Service. A service that exposes a user configurable endpoint that answers with derivative workflows based on an mime/type + some rdf:type and properties. 
Camel reacts on event, goes to that service, ask what it should do with that file, and processes async all stuff.
It's on my whiteboard. But looks related.

**Comment by acoburn** [comment]
Yes, definitely related. We should talk, because I'm planning to write the same thing.

**Comment by dannylamb** [comment]
This is def. gonna happen. But clearing out ticket clutter for now until we get to impl, where we'll have a more detailed ticket.
