### ISSUE TITLE
Design an RDF Serializer for Drupal 8

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#338]
Drupal 8 has a pluggable serialization system for entities.  What would it take to have a custom serializer for our entities so we can import/export RDF?

**Comment by bryjbrown** [comment]
For anyone looking for an entry point into this topic, here are some of the notes I'm looking at:
- [Explanation of the Symfony Serializer component (which Drupal 8 extends)](http://symfony.com/doc/current/components/serializer.html)
- [The actual code of the Drupal 8 core serialization module](https://github.com/drupal/drupal/tree/8.2.x/core/modules/serialization)
- [ALL TEH INFOS about JSON-LD](http://json-ld.org/spec/latest/)

**Comment by DiegoPino** [comment]
Link to JSON-LD issue https://github.com/Islandora-CLAW/CLAW/issues/297

**Comment by dannylamb** [comment]
Closing since sprint is over.  We can open another ticket to 'revisit' this concept later if required.
