### ISSUE TITLE
Consider creating a GraphQL - based endpoint

### ISSUE THREAD

**Issue by acoburn** [Islandora-CLAW/CLAW#351]
This is _not_ for the MVP, but a graphQL endpoint could be an excellent part of the eventual API: http://graphql.org

(Especially if the interactions deal in JSON-LD, and not just JSON)

In fact, depending on how compelling/useful this ends up being, it could be a good fcrepo-exts project. n.b. I added this to the 9/1/16 fcrepo-tech [agenda](https://wiki.duraspace.org/display/FF/2016-09-01+-+Fedora+Tech+Meeting) as a discussion point

**Comment by DiegoPino** [comment]
@acoburn https://github.com/fubhy/graphql-drupal. 😄

**Comment by acoburn** [comment]
@DiegoPino this is why, when you stick with specifications, you often find that someone has already written the code for you!

**Comment by DiegoPino** [comment]
@acoburn++ specs++

**Comment by acoburn** [comment]
Closing this, as a GraphQL module already exists for Drupal, and there should be no need to write one ourselves.
