### ISSUE TITLE
Upgrade fcrepo to fecrepo-4.6.0 in Vagrant

### ISSUE THREAD

**Issue by DiegoPino** [Islandora-CLAW/CLAW#358]
fcrepo-4.6.0 is out, lot of bug fixes, new stuff, deprecation, etc. We should upgrade as soon as we can.

**Comment by DiegoPino** [comment]
@ruebot will ping you here. Not sure if we can make this happen for this sprint but i opened this as suggested by you.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/CLAW/commit/83cdc7436110e296e6e6151c3980237dfb71996d
