### ISSUE TITLE
HOMEWORK: Explore Drupal 8 UI

### ISSUE THREAD

**Issue by manez** [Islandora-CLAW/CLAW#360]
For the front-endians of Islandora, let's do a local install of [Drupal 8](https://www.drupal.org/8) and get to know it better. Build some pages, set up users, play with permissions, etc. So we can be better informed when making suggestions about how CLA's UI should work.

**Comment by manez** [comment]
http://simplytest.me/ is a pretty quick way to throw up a sandbox to play with. It only lives for a 1/2 hour, but it spins up in moments and provides user1 access to a real live Drupal 8 site.

**Comment by highermath** [comment]
thom8 has a beetbox-based D8 vagrant box at https://packagist.org/packages/thom8/drupal8-vagrant

It is dead simple to launch.

Requirements

- Composer
- Vagrant >= 1.8
- Virtualbox
- Vagrant Hostsupdater

Installation

Open terminal (or git bash for windows users) and run the following commands --

`composer create-project thom8/drupal8-vagrant drupal8-vagrant && cd $_`
`vagrant up`
Go to http://d8.local/

- username: admin
- password: admin

This speeds right along until it comes to the drush make section. It isn't dead. Just give it time.

Subsequent launches are snappy.

**Comment by ajs6f** [comment]
I'd be happy to cut on this ticket, but it's not clear to me what the product is. Is what's desired some kind of comparison between D8 and some other system?

**Comment by manez** [comment]
@ajs6f it's a holdover from when we still had regular sprints, to have a ticket in for people who were joining to learn & research rather than output. Might be time to close it out, since it doesn't really fit how we're operating now.

**Comment by ajs6f** [comment]
Awesome! I feel like I'm contributing already-- I've just caused a ticket to be closed!
