### ISSUE TITLE
CLAW vagrant - theme does not get applied

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#374]
Steps to reproduce:
* Get the latest CLAW - Sep 19 20106 - (git clone --recursive https://github.com/Islandora-CLAW/CLAW.git)
* vagrant up
* go to http://localhost:8000 (drupal)
* the theme/css does not get applied properly

Expected behavior:
* The theme/css should get applied 

The actual, incorrect behavior:
* the theme/css does not get applied properly

Notes:
* Possible issue is that current vagrant installation does not set the /var/www/html/drupal/sites/default/files ownership to www-data, while at the same time css/js aggregation is enabled.  Providing www-data ownership to files folder resolves this issue.

**Comment by MarcusBarnes** [comment]
I've confirmed the issue and @Natkeeran's  notes appears to pinpoint the problem.  Please note that you will need to clear the Drupal cache to have the theme apply.

Example before:    
<img width="560" alt="theme_not_applied_properly" src="https://cloud.githubusercontent.com/assets/938274/18674321/d2699ba4-7f1c-11e6-9bde-45d7db1ca6aa.png">

Example after setting ownership of /var/www/html/drupal/sites/default/files ownership to www-data (different page than above, but for illustration on what to expect):

<img width="928" alt="after_ownership_change" src="https://cloud.githubusercontent.com/assets/938274/18674398/1ab1a2d0-7f1d-11e6-8f67-f9652704bd7e.png">

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/CLAW/commit/83cdc7436110e296e6e6151c3980237dfb71996d
