### ISSUE TITLE
Drupal Collections and Fedora Containment

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#381]
This issue is to discuss all opinions thoughts and questions around how we want to deal with collections and the objects inside once move from Drupal to Fedora.

Currently all items will be under (LDP contained by) an islandora:root object.

Resources (both RDF and NonRDF) will **not** necessarily be LDP contained by any collections they are a member of.

**Comment by DiegoPino** [comment]
Ok, i don't want to repeat myself, since there is a lot of stuff i already said in IRC, so basically it's all there: http://irclogs.islandora.ca/2016-09-26.html

**Comment by dannylamb** [comment]
Out of that IRC conversation, did we ever agree on collection membership being required?

**Comment by DiegoPino** [comment]
@dannylamb at least not in a call i was part of. I feel we said it was desired to keep (re-implement and code is a better expression) the islandora 1.x idea on collection membership, but i don't think we should impose it. Moreover islandora 1.x does allow orphan children. Our children could be at most/at least not part of a collection but still be, semantically speaking, part of the LDP tree and contained.

**Comment by whikloj** [comment]
Due to performance implications the default triplestore indexing does not index ldp:contains. The recommendation is to use fedora:hasParent, pcdm:memberOf or this type of property.

This removes the usefulness of the ldp:indirectContainer.

Therefore it is probably a good idea to dump the /members indirect container inside Collections and instead add a user configurable predicate (defaulting to pcdm:memberOf, dcmi:isPartOf ??) to the Collection module configuration and add it to any object added to the collection.

Death to Proxies!!

**Comment by dannylamb** [comment]
:+1: Let's use the CMS and its relational database to let users manage relationships.  Just flush it to Fedora as triples.  No need for anything else.

Using the inverse relationships will make everything easier for SQL too.  Can't wait 'til the collection view is actually a Drupal view.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/a1987aecb747b0b297176fc4d34afdc22cbddb4d
