### ISSUE TITLE
Re-wire triplestore indexing

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#394]
Depends on #393 

Drupal's triplestore indexer is running in Karaf, waiting to receive messages.  Use EasyRDF to generate a N-Triple (we'll change it to jsonld after the next release of fcrepo-camel) representation and send it to the queue defined in configuration.

Make sure the stomp broker url and queue name are configured the [same as the triplestore indexer](https://github.com/Islandora-CLAW/Alpaca/blob/master/indexing/islandora-indexing-triplestore/src/main/cfg/ca.islandora.indexing.triplestore.cfg#L4-L8).  Note that in Drupal you don't add the `activemq:queue` prefix to the queue name.

You can test that this ticket is complete by ingesting content in Drupal after setting your rdf mapping.  If you get triples in your 3-store with the same subject, you're good to go :+1:

**Comment by dannylamb** [comment]
We've updated Fedora, fcrepo-camel, and fcrepo-camel-toolbox recently, so there's a lot more changes involved now.  All of them for the better.

**Comment by dannylamb** [comment]
https://github.com/Islandora-CLAW/CLAW/issues/394 is up, but I'm going to work with @ruebot on https://github.com/Islandora-CLAW/claw_vagrant/pull/3 to make installation easier to test.

**Comment by whikloj** [comment]
Resolved with:

1. https://github.com/Islandora-CLAW/Alpaca/commit/6c38bc4de83d411c2ae6c92d8d7f7c4d7bdb31dd
2. https://github.com/Islandora-CLAW/islandora/commit/38943575d538e4ce96ad7a870850b973f00b3554
3. https://github.com/Islandora-CLAW/claw_vagrant/commit/62b35f349bac7438d0984a38ad204fd666094017
