### ISSUE TITLE
Entity database tables aren't all being created

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#419]
Despite being declared in the entity's annotation, the revision and revision_data tables are not being created when installing the module.

To verify:
- `$ cd /var/www/html/drupal`
- `$ drupal database:client`
- `mysql> show tables;`
You should see something like this (abbreviated for clarity)
```
mysql> show tables;
+------------------------------------+
| Tables_in_drupal8                  |
+------------------------------------+
...
| fedora_resource                    |
| fedora_resource_field_data         |
...
+------------------------------------+
```

After applying the fix, you should see (also abbreviated):
```
mysql> show tables;
+------------------------------------+
| Tables_in_drupal8                  |
+------------------------------------+
...
| fedora_resource                    |
| fedora_resource_field_data         |
| fedora_resource_field_data_revision |
| fedora_resource_revision            |
...
+------------------------------------+
```

**Comment by dannylamb** [comment]
Just putting this here too since I burned time on it today:


# Uninstall the islandora module before you pull down this code!!!

If you pull down the code with git, you're defining a revision entity_key that does not exist yet.  Your database will go kaboom.  I've done it twice today because of this.  Just a heads up.

**Comment by DiegoPino** [comment]
solved with https://github.com/Islandora-CLAW/islandora/commit/d465c4106e31477dbbd651db74d2d3c0e126ae59

**Comment by dannylamb** [comment]
this is resolved, no? https://github.com/Islandora-CLAW/islandora/issues/10 is a seperate bug/issue.

**Comment by dannylamb** [comment]
thanks @DiegoPino
