### ISSUE TITLE
Can we output expanded JSON-LD by default?

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#422]
@DiegoPino what do you think?  I want to use the jsonld serializer to return responses AND put jsonld on the queue.  I'd prefer it be expanded when getting passed to Fedora.  Can we make that the default?

I'd like to explore other options (like auto-generating contexts and allowing the user to request different representations through the use of headers) later, but for now would like to simplify things if possible.

**Comment by dannylamb** [comment]
Talking to @acoburn has revealed the use of "profile" within the accept header.  Fedora 4 is doing something like `Accept: application/ld+json; profile=\"http://www.w3.org/ns/json-ld#expanded\"`.

Now, we don't strictly enforce Accept headers, but we could still look for this and act on it.  :+1: for a standard way of describing which jsonld operation you want to perform upon request.

**Comment by acoburn** [comment]
The JSON-LD spec describes this here: https://www.w3.org/TR/json-ld/#application-ld-json

**Comment by DiegoPino** [comment]
OK, can do that. Have to see where do i have to cut/break/hack to be able to have a clean header access. If not, can make it the default via config options. Is that right for you @dannylamb?

**Comment by dannylamb** [comment]
@DiegoPino right now all i need is the serializer to output expanded by default.  I'm outside of the HTTP layer and I'm using it to publish to a queue.  That will unblock me for the time being.

We can map out the specifics for headers and GET requests separately as part of https://github.com/Islandora-CLAW/CLAW/issues/398.

**Comment by DiegoPino** [comment]
@dannylamb will do that for today. 😄

**Comment by dannylamb** [comment]
Hey @DiegoPino, can you give this a look when you have a chance?

**Comment by DiegoPino** [comment]
@dannylamb yes, i'm my radar. Just finished fedora4camp and moved to my new apartment. You will get news on this on Friday.

**Comment by dannylamb** [comment]
@DiegoPino Those are definitely more important things than this.  Just whenever you get a chance, man.
