### ISSUE TITLE
Add a Collection bundle for FedoraResource

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#430]
Create an islandora_collection module with configuration files for a Collection object.  It should have a field for description and reference field for memberOf.  Also provide a default rdf mapping for these fields.

**Comment by Natkeeran** [comment]
@dannylamb, can you please confirm that the tasks for this issue are:

* Create a module: islandora/islandora_collection (drupal generate:module) 
* It should contain  islandora/islandora_collection/config/install
-> islandora.fedora_resource_type.collection.yml
-> rdf.mapping.fedora_resource_type.collection.yml
-> Not sure what is the config to add fields. field.field.islandora.fedora_resource.<<field>>.yml?

Reference: http://valuebound.com/resources/blog/create-custom-content-type-programmatically-using-configuration-api-drupal-8

I can work on this one!

**Comment by dannylamb** [comment]
Hey great!  You'll want your root directory in the islandora project to contain two folders:
- `islandora` as we have it now
- `islandora_collection` that you'll make for this issue

And in the `config/install` folder you'll want yml files for

- The Collection fedora resource type
- The RDF Mapping
- The field and field storage definitions for
  - A description field (full text with summary/trimmed, look at a node's body field for reference)
  - A memberOf entity reference field

Except for the RDF mapping, you can make all of these things through the UI.  If you go to `admin/config/development/configuration/single/export` afterwards, you can choose them from the drop-downs and export them.  It'll even tell you what to name the files underneath the exported yml.

**Comment by Natkeeran** [comment]
@dannylamb 
A first go is here: https://github.com/Natkeeran/CLAW/tree/issue-430/islandora_collection

I am unable to test the rdf mapping because REST UI does not work properly with 8.2.  @DiegoPino suggested a way to configure via yml, but don't have the details.

**Comment by dannylamb** [comment]
Hey, looks good.  Throw up a PR.  You seem to have an rdf mapping yml there.  We can work on it through the PR.

**Comment by whikloj** [comment]
@dannylamb is `islandora_collection` going to be a separate module from https://github.com/Islandora-CLAW/islandora? 

Or is it going inside it?

**Comment by dannylamb** [comment]
Was thinking separate module, but still within the islandora repo.  Top-level.

**Comment by dannylamb** [comment]
Oh, now I see. The islandora folder needs to be nested inside a folder named `islandora`.  `islandora_collection` needs to be in the islandora folder, alongside another `islandora`.

e.g.
- CLAW/islandora
- CLAW/islandora/islandora
- CLAW/islandora/islandora_collection

**Comment by dannylamb** [comment]
@Natkeeran clear as mud?

**Comment by Natkeeran** [comment]
@dannylamb No I got it.  I suppose some one will move the current CLAW/islandora into CLAW/islandora/islandora.  I can put it into to CLAW/islandora/islandora_collection.

**Comment by whikloj** [comment]
@dannylamb @Natkeeran actually, wouldn't islandora_collection just be a sub-module of islandora? So
```
modules/islandora
modules/islandora/islandora.module

modules/islandora/islandora_collection
modules/islandora/islandora_collection/islandora_collection.module
````

**Comment by dannylamb** [comment]
@whikloj Either way.  I have no strong opinions.

@Natkeeran if it's easier for you, wanna just put islandora_collection into 'modules' folder in `islandora`?  e.g.
- CLAW/islandora
- CLAW/islandora/modules
- CLAW/islandora/modules/islandora_collection

**Comment by whikloj** [comment]
Lets not forget that CLAW is not where these things are, they are in a separate repo which will go into Drupal.org. So technically `CLAW` is not part of this conversation, that is the wrapper construct around our virtual development environment.

So in the https://github.com/Islandora-CLAW/islandora repo you'd need to add a `islandora_collection` folder to put the new code and make it dependant on `islandora`

**Comment by dannylamb** [comment]
@whikloj, correct.  The PR needs to be against the islandora repo. My mistake for working within the context of CLAW submodule madness.

**Comment by whikloj** [comment]
@Natkeeran so your PR against the islandora repo, will just add a new folder with all your code inside it. No need to move the existing islandora drupal module code.

**Comment by Natkeeran** [comment]
@whikloj sure.  Would that be https://github.com/Islandora-CLAW/islandora/modules or https://github.com/Islandora-CLAW/islandora/islandora_collection ?

**Comment by dannylamb** [comment]
@Natkeeran make your PR against https://github.com/Islandora-CLAW/islandora.  Add a modules folder and put islandora_collection in it.

**Comment by Natkeeran** [comment]
@dannylamb, @whikloj Created a [PR](https://github.com/Islandora-CLAW/islandora/pull/13). I am able to test the rdf mapping.  Details in the PR.

**Comment by dannylamb** [comment]
Resolved with https://github.com/Islandora-CLAW/islandora/commit/d233f406500391cce01b5ba6b8b73c053a4efc6b
