### ISSUE TITLE
Add configuration for Fedora

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#431]
Add two fields to configuration for the islandora module
- Fedora REST endpoint
  - Default to `http://localhost:8080/fcrepo/rest`
  - If a parent is not specified when creating a new resource, it will be created as a child to this resource. 
- Fedora indexing queue
  - Default to `islandora/indexing/fedora`
  - Name of the queue you will publish indexing events to for Fedora.

**Comment by whikloj** [comment]
@dannylamb I'm gonna try this if you're not relying on it right now. Could take me a little to figure out how this stuff works in Drupal.

**Comment by whikloj** [comment]
PR - https://github.com/Islandora-CLAW/islandora/pull/11
