### ISSUE TITLE
Make Collection description field plain text

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#441]
Make it long plain text, and re-export the config.

**Comment by Natkeeran** [comment]
@dannylamb 
* The request is to change the description field to "long plain text".
* We need plain text to avoid rdf mapping having html markup.
* We want to avoid html markup because: https://github.com/Islandora-CLAW/islandora/pull/15

I'll make the changes.

**Comment by dannylamb** [comment]
@Natkeeran Yes, the scope of this ticket is just to make the field 'long plain text'.  And it's not that the rdf mapping will have markup (it's a config entity on its own), but that the end jsonld can have markup embedded if we're not careful and that's often (almost always?) undesirable.

Thx for taking this on.

**Comment by Natkeeran** [comment]
@dannylamb Updated it here: https://github.com/Natkeeran/islandora/tree/issue-441/islandora_collection

Pls let me know if I should create a PR.

**Comment by dannylamb** [comment]
You don't need to ask permission to make a PR.  Just go for it.

I've already pulled in the changes and tested them.  The description field is indeed plain text, and when exported as jsonld, there is no markup.

```json
{
  "@graph": [
    {
      "@id": "http://localhost:8000/fedora_resource/5?_format=jsonld",
      "@type": [
        "http://schema.org/Thing",
        "http://www.w3.org/ns/ldp#RDFSource",
        "http://www.w3.org/ns/ldp#Container"
      ],
      "http://purl.org/dc/terms/title": [
        {
          "@value": "Plain text description"
        }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#label": [
        {
          "@value": "Plain text description"
        }
      ],
      "http://schema.org/dateCreated": [
        {
          "@value": "2016-12-02T14:06:44+00:00"
        }
      ],
      "http://purl.org/dc/terms/created": [
        {
          "@value": "2016-12-02T14:06:44+00:00"
        }
      ],
      "http://schema.org/dateModified": [
        {
          "@value": "2016-12-02T14:06:44+00:00"
        }
      ],
      "http://purl.org/dc/terms/description": [
        {
          "@value": "I am just plain ol' text."
        }
      ]
    }
  ]
}
```

:+1:

**Comment by Natkeeran** [comment]
@dannylamb Created a PR here: https://github.com/Islandora-CLAW/islandora/pull/19

**Comment by dannylamb** [comment]
Resolved with https://github.com/Islandora-CLAW/islandora/commit/3d3ebc432fbf3436ad0e6f716df20763faefb3a7

Thx @Natkeeran !
