### ISSUE TITLE
RdfResource rdf mapping now showing all fields when entity is serialized as jsonld.

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#442]
The id and type properties are getting serialized, but the rest aren't.  The culprit appears to be https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora/config/install/rdf.mapping.fedora_resource_type.rdf_source.yml#L8-L9.

fedora_resource_type should be fedora_resource.

Also, be ever vigilant about clearing caches when playing with configuration changes.  No need to sink time into wondering why your changes aren't applied when working on this!

To test
- Make a new RdfResource
- Get the jsonld representation of it from http://localhost:8000/fedora_resource/{id}?_format=jsonld
- You should only see Id and Type properties in the jsonld
- Update the rdf mapping in configuration with your changes
- Clear your caches
- Get the jsonld representation of it from http://localhost:8000/fedora_resource/{id}?_format=jsonld
- You should be able to see other properties, like created and modified dates.

**Comment by whikloj** [comment]
PR - https://github.com/Islandora-CLAW/islandora/pull/16
