### ISSUE TITLE
Make an EventGenerator service and provide a default implementation

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#445]
Sub-issue of #432 

We need a service to generate serialized events for when CMS operations occur.  The default implementation should be [Activeity Stream 2.0](https://www.w3.org/TR/activitystreams-core/) events (the same as Fedora 4 will soon use).

For now, the service should generate three event serializations, one for Create, Update, and Delete operations.  Here's what the example messages should look like:

### Create
```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Create",
  "actor": {
    "type" : "Person",
    "id" : "http://localhost:8000/user/X"
  },
  "object": "http://localhost:8000/fedora_resource/Y"
}
```

### Update
```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Update",
  "actor": {
    "type" : "Person",
    "id" : "http://localhost:8000/user/X"
  },
  "object": "http://localhost:8000/fedora_resource/Y"
}
```

### Delete
```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Delete",
  "actor": {
    "type" : "Person",
    "id" : "http://localhost:8000/user/X"
  },
  "object": "http://localhost:8000/fedora_resource/Y"
}
```

**Comment by dannylamb** [comment]
I've updated the examples for what I think is the minimum representation I can give while following the spec.

**Comment by dannylamb** [comment]
Blocked by https://github.com/Islandora-CLAW/CLAW/issues/446

**Comment by DiegoPino** [comment]
Solved by https://github.com/Islandora-CLAW/islandora/commit/8553541b3149584dea5d9c8a7dc5c5568dce97b6
