### ISSUE TITLE
Make travis run tests in islandora modules.

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#446]
Right now, Travis is configured to only run checkstyle and copy-paste detection.  We need to add a command for running unit and functional tests inside our drupal modules to the script Travis executes.

[This documentation](https://www.drupal.org/docs/7/testing/running-tests-through-command-line) suggests something like `sudo -u www-data php ./core/scripts/run-tests.sh islandora`.  We don't have sudo on Travis, so we'll have to adjust that somehow to make it run.  As long as you have access to your document root while running it should be ok.

**Comment by dannylamb** [comment]
See https://github.com/Islandora-CLAW/islandora/issues/20

**Comment by DiegoPino** [comment]
Solved with https://github.com/Islandora-CLAW/islandora/commit/8553541b3149584dea5d9c8a7dc5c5568dce97b6
