### ISSUE TITLE
Create 'Teaser' view mode for Fedora resources

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#447]
This can be done through the Drupal UI by navigating to `http://localhost:8000/admin/structure/display-modes/view` and clicking on the "+ Add view mode" button.

It can be exported by visiting http://localhost:8000/admin/config/development/configuration/single/export.  Add it to the `islandora/config/install`.

**Comment by kimpham54** [comment]
@dannylamb is this literally just creating a view mode called "Teaser" and then exporting it? Is any additional configuration required?

**Comment by DiegoPino** [comment]
@kimpham54 once tested and exported you must add it to islandora/config/install and make a pull request. That should be all

**Comment by dannylamb** [comment]
Resolved with https://github.com/Islandora-CLAW/islandora/commit/4b882db0ecbb2fb3f07e1684d53e0494d2695bab.

Thx @kimpham54 and @DiegoPino

**Comment by DiegoPino** [comment]
@kimpham54 you are the best!++
