### ISSUE TITLE
Fedora fails to deploy on vagrant up

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#458]
Blocks #448 

Fedora fails to deploy when running a new vagrant up.  Seems to be related to our tomcat setup, and where transaction.log gets written to.  Somehow it's going somewhere the user doesn't have access to during the install process.  See this gist for my catalina.out: https://gist.github.com/dannylamb/cea486a82d1467baf70d67bf40e8f9b9

**Comment by dannylamb** [comment]
I'm investigating the service script for tomcat7 to see where the command is run from, as that may lead to where transaction.log gets written.

**Comment by DiegoPino** [comment]
Confirmed. It's failing.

**Comment by DiegoPino** [comment]
It sees to be related to tomcat deployment via apt-get 
see https://bugs.launchpad.net/ubuntu/+source/tomcat7/+bug/1232258
and https://bugs.launchpad.net/ubuntu/+source/tomcat7/+bug/1308284

**Comment by dannylamb** [comment]
I'm going to attempt the fix outlined in https://bugs.launchpad.net/ubuntu/+source/tomcat7/+bug/1232258

```
sudo ln -s /var/lib/tomcat7/common/ common
sudo ln -s /var/lib/tomcat7/server/ server
sudo ln -s /var/lib/tomcat7/shared/ shared

I believe the installer should create these links.
```

**Comment by dannylamb** [comment]
PR is up! https://github.com/Islandora-CLAW/CLAW/pull/462

**Comment by dannylamb** [comment]
bah.... perms are getting set incorrectly further downstream...  tested in isolation, (e.g. just the fcrepo.sh script), everything works fine.  but full install shows this still fails.

**Comment by DiegoPino** [comment]
Fixed via https://github.com/Islandora-CLAW/CLAW/commit/876d44b7984fdb283d0493e037309623b106fb83
