### ISSUE TITLE
Fedora's velocity.log written to incorrect location

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#459]
See this gist for my catalina.out: https://gist.github.com/dannylamb/cea486a82d1467baf70d67bf40e8f9b9

We should be able to control this by setting the following config for fcrepo: `-Dfcrepo.velocity.runtime.log=file:/path/to/log`

**Comment by dannylamb** [comment]
This is also resolved with https://github.com/Islandora-CLAW/CLAW/pull/462

**Comment by DiegoPino** [comment]
Fixed via https://github.com/Islandora-CLAW/CLAW/commit/876d44b7984fdb283d0493e037309623b106fb83
