### ISSUE TITLE
Make FedoraResource's 'fedora_has_parent' field single valued.

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#472]
Change the base field definition for `fedora_has_parent` to allow only single values.  This will guarantee we have a tree.

You'll have to touch up the functions for getting and setting the parent and parent id to accommodate a single value.

**Comment by whikloj** [comment]
@dannylamb This is not currently possible.
https://www.drupal.org/node/1869574

**Comment by dannylamb** [comment]
Whaaaaaa?

Terrible....
