### ISSUE TITLE
RDF UI: Map multiple ontologies to a field

### ISSUE THREAD

**Issue by kimpham54** [Islandora-CLAW/CLAW#487]
| Title (Goal)  | RDF UI: Map multiple properties to a field            |
--------------- |------------------------------------                           |
| Primary Actor | Repository admin     |
| Scope         | access       |
| Level         | Low  |
| Story         | As a repository admin, I want to be able to select multiple properties (including from different ontologies) to map to the same field of a bundle resource/entity type. This use case depends on a previous use case #485 , the ability to load multiple ontologies. |

**Comment by DiegoPino** [comment]
@kimpham54 just a quick update on this. I suppose this should state: "Map multiple properties coming from different ontologies to a field". Because the mapping that happens in Drupal 8 is field to property, not the whole ontology

**Comment by kimpham54** [comment]
@DiegoPino thanks, you're right! I made the fix

**Comment by dannylamb** [comment]
Transferring to https://github.com/Islandora-Labs/rdfux/issues/3
