### ISSUE TITLE
RDF UI: Validating mappings/usage of ontologies

### ISSUE THREAD

**Issue by kimpham54** [Islandora-CLAW/CLAW#488]
| Title (Goal)  | RDF UI: Validating mappings/usage of ontologies |
--------------- |------------------------------------                           |
| Primary Actor | Repository admin    |
| Scope         | access  |
| Level         | Medium? |
| Story         | As a repository admin, when I am mapping fields in RDF, I want the system to impose restrictions on field assignment if it violates the specification/model of the ontology - this could be reflected in the UI by greying out inappropriate classes/predicates or removing them as a possible select option. Restrictions includes but is not limited to domains & ranges of properties, subclasses, class disjoints and equivalence.  Ideally, validation should happen across bundles. |

**Comment by DiegoPino** [comment]
Thanks for bringing this up. I feel this is very important. 👍

**Comment by dannylamb** [comment]
Transferred to https://github.com/Islandora-Labs/rdfux/issues/4
