### ISSUE TITLE
RDF UI: Ability to integrate linked data authorities/subjects/genres

### ISSUE THREAD

**Issue by kimpham54** [Islandora-CLAW/CLAW#489]
| Title (Goal)  | RDF UI: Ability to integrate linked data authorities/subjects/genres |
--------------- |------------------------------------                           |
| Primary Actor | Repository admin, user    |
| Scope         | access       |
| Level         | Low for now, but an important requirement for the future. Potentially out of scope for RDF UI |
| Story         | As a repository admin, I want to be able to load linked data authorities and vocabularies that can be used to autofill form fields.  As a user, when I am filling out a form in Islandora with a field that uses a linked data authority, I would like to see a long select list of terms with human-readable labels that I can choose from. |

**Comment by ajs6f** [comment]
It would be nice to have a choice of UI/UX elements. E.g. autocomplete blanks for giant lists, select lists, maps might be best for geospatial vocabs, timelines for chronology vocabs, etc.

**Comment by ajs6f** [comment]
👍

**Comment by ddavis** [comment]
:+1:

**Comment by DiegoPino** [comment]
@kimpham54 @ajs6f @ddavis I will research field widgets and plugins functionality in Drupal 8 to generalize or at least try to, and propose a way of doing for this use case. Thanks

**Comment by ajs6f** [comment]
@DiegoPino ++ !

**Comment by uconnjeustis** [comment]
In the Islandora Metadata Interest group, we were thinking it would be nice to have to top used authorities and vocabularies such as Linked LC, VIAF, AAT, TGM, FAST. Perhaps there's a way to offer something like a "package" such as the archival package or library package. I've seen with our consortium repository that the archives and libraries have their preferred set. For example, archives tends to go AAT, TGN, FAST, and VIAF.

**Comment by dannylamb** [comment]
Transferring to https://github.com/Islandora-Labs/rdfux/issues/1
