### ISSUE TITLE
Remove vcs entries in all composer.json files

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#497]
All drupal repos (islandora, islandora_collection, claw-jsonld, and drupal-project) have vcs entries for github.  Now that we're on packagist, please remove those.  Simply requiring "dev-8.x-1.x" is sufficient.  This will require a PR per repo.

**Comment by DiegoPino** [comment]
@dannylamb looking at this now, what will be the difference between https://packagist.org/packages/islandora/islandora#0.0.1 and
https://packagist.org/packages/islandora/islandora#dev-8.x-1.x
Are we still on semantic versioning?

**Comment by dannylamb** [comment]
@DiegoPino dev-8.x-1.x pulls a tarball of master, and is what we want right now.  0.0.1 is just me messing around and testing the release process.  It's not legit.  The first version we actually slice off will be in the 8.x range.  I guess 8.1.1?  We seem to be skipping 8.0 altogether based on previous naming.

**Comment by DiegoPino** [comment]
@dannylamb cool. Got confused with the 0.0.1. Thanks!

**Comment by bryjbrown** [comment]
@dannylamb This would just involve cloning a repo, removing lines like https://github.com/Islandora-CLAW/islandora_collection/blob/8.x-1.x/composer.json#L19-L26 and then creating a PR? Just wanting to double check what is actually being asked here.

**Comment by dannylamb** [comment]
@bryjbrown That is exactly what I'm asking for.  I need someone to do that for each of the repos listed in the issue.

**Comment by bryjbrown** [comment]
@dannylamb PRs for islandora, islandora_collection and drupal-project (listed above).

[claw-jsonld's composer.json file](https://github.com/Islandora-CLAW/claw-jsonld/blob/8.x-1.x/composer.json) doesn't have much in it (no existing repository/vcs entries or requirements) so I left it alone. If it requires work I'm happy to do that as well, just need to know what is needed.

**Comment by DiegoPino** [comment]
Previous pull partially solved issue. reopening

**Comment by whikloj** [comment]
@bryjbrown If a single PR doesn't close a ticket fully by itself use 
```
Partially resolves ....
```

as in

```
Partially resolves Islandora-CLAW/CLAW#497
```

**Comment by bryjbrown** [comment]
@whikloj My bad. I was just copying the wording from another PR.

**Comment by whikloj** [comment]
@bryjbrown no worries that Github ticket trickery is new voodoo.

**Comment by bryjbrown** [comment]
@dannylamb As @whikloj pointed out, I goofed the wording of the PR message which causes GH to close the referring ticket. https://github.com/Islandora-CLAW/CLAW/issues/497 should be reopened until https://github.com/Islandora-CLAW/islandora_collection/issues/6 is merged and we verify that claw-jsonld doesn't need any TLC.

**Comment by whikloj** [comment]
@bryjbrown I just merged it, so no worries 👍

**Comment by dannylamb** [comment]
@bryjbrown No worries.  I just caught that and was about to re-open anyway.

**Comment by dannylamb** [comment]
Ninja'd by @whikloj
