### ISSUE TITLE
Dealing with children when you delete a parent

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#512]
Currently you can create Drupal entities and add children. But if you delete the parent you get a White Screen of Death (WSOD) and the Apache log says.
```
[Thu Jan 26 14:14:48.563388 2017] [:error] [pid 3098] [client 10.0.2.2:49814] Error: Call to a member function getValue() on null in /home/ubuntu/claw/islandora/src/Entity/FedoraResource.php on line 249 #0 /home/ubuntu/claw/islandora/src/FedoraResourceListBuilder.php(38): Drupal\\islandora\\Entity\\FedoraResource->getParent()
#1 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityListBuilder.php(229): Drupal\\islandora\\FedoraResourceListBuilder->buildRow(Object(Drupal\\islandora\\Entity\\FedoraResource))
#2 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Controller/EntityListController.php(22): Drupal\\Core\\Entity\\EntityListBuilder->render()
#3 [internal function]: Drupal\\Core\\Entity\\Controller\\EntityListController->listing('fedora_resource')
#4 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#5 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(574): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()
#6 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))
#7 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#8 [internal function]: Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()
#9 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(144): call_user_func_array(Object(Closure), Array)
#10 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#11 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/drupal/web/modules/contrib/devel/webprofiler/src/StackMiddleware/WebprofilerMiddleware.php(38): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\\webprofiler\\StackMiddleware\\WebprofilerMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(652): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#21 {main}, referer: http://localhost:8000/fedora_resource/1/delete
```

We should either 
1. Not allow the object with children to be deleted.
1. Move the parent of the children up a level.
1. Delete all the children too

Discuss

**Comment by DiegoPino** [comment]
@whikloj cool, thanks for opening this. Will think about the consequences of any of those options!

**Comment by dannylamb** [comment]
@whikloj Lol, That's for the admin list.  I think it's redirecting you to that after the delete, but is then trying to reference the parent entity from one of the children and WSODs.

So you could possibly also
4. Remove references to the deleted entity (which I guess would be like 2 but makes them top level resources?)

**Comment by whikloj** [comment]
@dannylamb yes its from the admin list, but thats because the entity is still referencing a deleted entity. So do I just delete the reference? Then they would fall to the top and become a child of the root?

**Comment by dannylamb** [comment]
My gut says 3, but with a confirm form just to make sure folks are aware of the consequences.

I see this as analogous to having http://fedora_host/fcrepo/rest/abc/123 and then issuing a DELETE to http://fedora_host/fcrepo/rest/abc in Fedora.

**Comment by ajs6f** [comment]
LDP would say, just delete the children. (Assume that the client knows what it's doing.) But that's an API POV. One question is: what are the expectations for an API and for a UI and are they different here?

**Comment by DiegoPino** [comment]
@ajs6f there is no assumption here that LDP containment is in place or driving this parent relationships, the predicates used are not LDP ( @whikloj please correct me if I'm wrong) on the islandora side?

**Comment by dannylamb** [comment]
@ajs6f @DiegoPino This is precisely that relationship, it's just not going to get implemented the way people think it will.  This is where we need to base things in drupal off of the parent relationship so we can easily paginate and prevent the scenario of a resource with potentially infinite children tanking the site.

**Comment by dannylamb** [comment]
To clarify, we need to use something akin to fedora:hasParent, _assume_ it's the inverse of ldp:contains, but still make sure things wind up in Fedora in the right place in the hierarchy.  The fact that Fedora manages that relationship is a complication, but something I think is worth working with to prevent responses that are too large from being generated.

**Comment by whikloj** [comment]
This is not an LDP relationship because (as I understand it) that would be parent -> children (ie. ldp:contains). Is there an LDP child -> parent relationship? 

But really this would depend on the rdf mapping. We could delete the children but (and I'm talking off the top of my head) update the delete confirmation to tell you that all children will also be deleted.

**Comment by dannylamb** [comment]
@whikloj There is no in LDP.  We're on the hook for formalizing that relationship.

**Comment by dannylamb** [comment]
@ajs6f To get back to your question, everything that can be done in with the API should be possible in the UI.  But not the other way around.

And this does bring up implications for the API.  Since moving your stuff around in Fedora sounds like a thing people will want to do with islandora.

**Comment by DiegoPino** [comment]
Also, the "I will delete the children" radical (sorry) idea can be fine but is just a "wish or intention of bad will". Because the client/UI could not have the credentials to do so, leaving you with the same problematic state as this issue tries to prevent

**Comment by dannylamb** [comment]
Thanks you @whikloj @DiegoPino
