### ISSUE TITLE
Add Drupal dependency for islandora to islandora_collection

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#514]
We require islandora/islandora in the composer.json, but we need to add a dependency in the `islandora_collection.info.yml`. I was able to uninstall islandora and leave islandora_collection in place that seems wrong.

So just adding a line like https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora.info.yml#L8-L9 to the `islandora_collection.info.yml` but use `islandora` instead of `block`.

**Comment by jonathangreen** [comment]
Handled here:
https://github.com/Islandora-CLAW/islandora_collection/pull/7
