### ISSUE TITLE
Implement GET request for FedoraResource entities

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#524]
Implement a GET request for fedora resources, exposing an endpoint at http://localhost:8000/fedora_resource/{id} that has the following behaviour:
 
* Respects the drupal/symfony _format query parameter
  * e.g. http://localhost:8000/fedora_resource/{id}?_format={format} where format can be json, xml, hal, jsonld, or any other serializer that is enabled.
* Returns vclock in as a header, `X-Islandora-Vclock`
* Returns the bundle as a header, `X-Islandora-Bundle`
* Although Drupal does not use/require Accept headers, respect the 'profile' parameter of an accept header of 'application/ld+json' if provided.  The _format query parameter will always be used to determine the mime of the response, but by reading the profile from the Accept header, clients can represent various forms of the resource using different jsonld operations.
  * `Accept: application/ld+json; profile=http://www.w3.org/ns/json-ld#expanded` to request an expanded document
  * `Accept: application/ld+json; profile=http://www.w3.org/ns/json-ld#compacted` to request a compacted document
  * `Accept: application/ld+json; profile=http://www.w3.org/ns/json-ld#flattened` to request a flattened document

Possible responses:
* 200, with the serialized resource as the body.
* 404

**Comment by dannylamb** [comment]
I'm also considering respecting Prefer headers to include or omit containment triples.  There is also the option to always exclude containment triples and provide a link header to the list of resources contained, which we could page.

I'm trying hard to design this from someone issuing a request and it killing the site when there's potentially millions of contained resources.

**Comment by dannylamb** [comment]
I'm gonna snag this one.  I'll start with just jsonld as the format and go from there.

**Comment by dannylamb** [comment]
Ah, I'm blocked by https://github.com/Islandora-CLAW/CLAW/issues/493.  I'll put this aside and move to something else for now.

**Comment by DiegoPino** [comment]
#493 is working Dani and all your concerns were addressed, just no tests until I have code freeze for old 1.x done.  So if you can live without tests for now you should be able to continue

**Comment by dannylamb** [comment]
I'll wait for #493 to be fully addressed.  It's ok, there's plenty to do.

**Comment by whikloj** [comment]
#527 kinda relies on this as it would be good to do a test with a GET first to get the X-Islandora-Vclock header and then patch. I'll use known values for now.
