### ISSUE TITLE
Parse Events Before Broadcasting/Pipelining

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#570]
When working through fcrepo indexing, I'm seeing a recurring pattern on each step in the workflow processing the event from Drupal the same way.  By publishing to an event processing route that extracts informtation and stores it as exchange properties, we can only do processing once before passing it off to the user defined worfklow.

Basically, we need to pull [this](https://github.com/Islandora-CLAW/Alpaca/blob/master/islandora-indexing-triplestore/src/main/java/ca/islandora/alpaca/indexing/triplestore/TriplestoreIndexer.java#L66-L79) out into its own OSGi bundle that reads from message broker instead of being direct.  After processing it will publish to the singular route that handles distributing the message from #569.

**Comment by dannylamb** [comment]
Turns out this isn't possible given the lifecycle of an `Exchange`.  They are created per consumer, so we'll actually lose the parsed properties as we go from route to route if they're not `direct`.  So looks like the best plan of attack is to create a shared EventProcessor that will get used by all the components, and be careful that we reset the message to the original so we can deliver the same event throughout the pipeline.

**Comment by whikloj** [comment]
Wait, what are you saying here? That you can't have a simple shared pipeline that sets those 2 properties and then publishes to a user-defined recipient list?

**Comment by dannylamb** [comment]
What I'm saying is up to each consumer to parse the AS2 event, and we can share code by using a shared processor.  Headers and message bodies will get passed between listeners, but not Exchange properties.  Each bundle creates a new Exchange when it starts to process a message.

**Comment by dannylamb** [comment]
It occurs to me that there's the option of adding the properties as headers, but we'd need to take care to make sure they get passed back along to every recipient in the list.   We often clobber all headers before making http requests so it'd just be convention to stash those headers as exchange properties and then put them back as headers at the end of the route.

**Comment by whikloj** [comment]
Ok I see, I missed the part where the routes were in separate bundles. But that makes perfect sense.
