### ISSUE TITLE
Moving JsonldContextGenerator to jsonld (claw-jsonld)

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#596]
JsonldContextGenerator is needed in the [jsonld](https://github.com/Islandora-CLAW/jsonld) (formerly claw-jsonld) module to get the bundle's context.  However, adding it as a dependency would require [islandora](https://github.com/Islandora-CLAW/islandora) module to be a dependency to jsonld.  As jsonld is already a dependency to islandora, @whikloj and @dannylamb suggested that a circular dependency is not required.  In addition, jsonld can be further developed as a generic module than a claw module.  JsonldContextGenerator Interface and Class needs to be moved into jsonld.

**Comment by whikloj** [comment]
Okay the two above PRs should cover this issue.

**Comment by dannylamb** [comment]
Thanks again @whikloj and @Natkeeran
