### ISSUE TITLE
jsonld - normalize - date format

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#602]
hal_json and json return date values as Unix-timestamp.  I.e below
```
  "created": [
    {
      "value": "1491930286"
    }
  ],
  "changed": [
    {
      "value": "1491930286"
    }
  ],
```

jsonld returns the date values in different format.
```
      "http://schema.org/dateCreated": [
        {
          "@value": "2017-04-11T17:04:46+00:00"
        }
      ],
      "http://schema.org/dateModified": [
        {
          "@value": "2017-04-11T17:04:46+00:00"
        }
      ],
```

Is this the expected behaviour?

This can cause an issue denormalize as denormalize generally expects a Unix-timestamp.

**Comment by DiegoPino** [comment]
Expected.

**Comment by whikloj** [comment]
I would say yes this is expected and we will need to handle it in the normalize/denormalize functions.

**Comment by Natkeeran** [comment]
@DiegoPino @whikloj ok, please close the ticket.
