### ISSUE TITLE
Push DoctrineServiceProvider into IslandoraServiceProvider

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#604]
I'll be using it in both Gemini and the upcoming fedora flushing microservice, so I oughta push registering that service provider inside IslandoraServiceProvider.

**Comment by jonathangreen** [comment]
Resolved with: 
https://github.com/Islandora-CLAW/Crayfish-Commons/commit/bdd33fb3766e3ab359009547dc4ead968edd574f
