### ISSUE TITLE
Convert Hypercube and Houdini to respect Apix-Ldp-Resource header

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#611]
Relevant reading: https://github.com/fcrepo4-labs/fcrepo-api-x/blob/master/src/site/markdown/execution-and-routing.md#endpoint-example

When Api-X will foward a request to a microservice, it will enrich the message with an Apix-Ldp-Resource header.  Instead of reading in the path from the url and combining that with the Fedora base url, we should simply use this header provided by Api-X in Hypercube and Houdini.  This means the endpoints will not have any route parameters, and we'll need to use a `before` middleware to manually execute the FedoraResourceConverter and jam it into the request.

It's a bit tough to set things on the Request, so it may be easier to [duplicate](http://api.symfony.com/3.1/Symfony/Component/HttpFoundation/Request.html#method_duplicate) it and provide the response from Chullo in the `attribute` parameter.

Controllers will also need to be touched up to retrieve the response from Chullo, as it will no longer be provided as a route parameter.

**Comment by whikloj** [comment]
Soooo this might be a good place for a couple questions and to reveal my lack of grasp of API-X.

To start, would Houdini and Hypercube be [Resource scope services](https://github.com/fcrepo4-labs/fcrepo-api-x/blob/master/src/site/markdown/uris-in-apix.md#resource-scoped-services)?

**Comment by whikloj** [comment]
@dannylamb So after reading the "Generic Endpoint Proxy" example you linked to I have a couple questions. 

1. Not exactly clear how we expose these API-X services, so would Houdini become
  
     `Apix-Exposed-Uri: http://islandora.ca/services/objectFoo/svc:Houdini/convert/`


2. Using Houdini as the example, is the plan to continue to use the `X-Islandora-Args` header to determine resizing, etc? So in which case the request would come as 
```
GET /houdini/convert
Host: islandora.ca
Accept: image/jpeg
User-Agent: whatever
X-Islandora-Args: -resize 10%
Apix-Ldp-Resource: http://fedora01.backend.local/repository/objectFoo/
Apix-Exposed-Uri: http://islandora.ca/services/objectFoo/svc:Houdini/convert/
```

**Comment by whikloj** [comment]
It appears that instead we should be specify presets, so a request to `/services/houdini` would return a menu of possible choices (following in the API-X examples).

```
GET /services/houdini
Host: islandora.ca
Accept: */*
User-Agent: whatever
Apix-Ldp-Resource: http://fedora01.backend.local/repository/objectFoo/
Apix-Exposed-Uri: http://islandora.ca/services/objectFoo/svc:Houdini
```
which replies (I was going to do JSON-LD, but that is sooo painful to write by hand)
```
HTTP/1.1 200 OK
Content-Type: text/turtle; charset=UTF-8
Allow: HEAD, OPTIONS, GET
Content-Length: 123

@prefix islandApix: <http://islandora.ca/apixService>
<> a islandApix:serviceMenu ;
   islandApix:hasService <convert> ;
   islandApix:hasService <identify> .

<identify> a islandApix:subService .

<convert> a islandApix:subService ;   
   islandApix:provides ["image/jpeg", "image/tiff", "image/png", "image/gif"] ;
   islandApix:accepts  "X-Islandora-Args" .
```

Is that at all close to how this should work?

**Comment by dannylamb** [comment]
I think maybe instead of thinking of it as two services, i'd treat each as its own service.  E.g. http://localhost:8080/fcrepo/rest/some-image/svc:identify and http://localhost:8080/fcrepo/rest/some-image/svc:convert.  Does that simplify things?

**Comment by whikloj** [comment]
Sure, so the other part is do we define a set of service options or do we advertise the header somehow? Like do we say that `svc:convert` does a `LargeImage` and a `MediumImage` and a `SmallImage` **or** do we say `define dimensions with this format in this header`?

The latter seems more flexible but also harder to express in the "service menu" thingy.

**Comment by dannylamb** [comment]
@whikloj I'm gonna do the coding quickly here to have the services accept those headers, and then we'll address your other concerns under the umbrella of https://github.com/Islandora-CLAW/CLAW/issues/612.

**Comment by dannylamb** [comment]
### Testing Instructions

To deploy the changes:
- `vagrant ssh`
- `cd /var/www/html/Crayfish`
- `git remote add danny https://github.com/dannylamb/Crayfish.git`
- `git fetch`
- `git checkout issue-611`
- `cd /var/www/html/Crayfish/Hypercube/vendor/islandora/crayfish-commons`
- `git remote add danny https://github.com/dannylamb/Crayfish-Commons.git`
- `git fetch`
- `git checkout issue-611`
- `cd /var/www/html/Crayfish/Houdini/vendor/islandora/crayfish-commons`
- `git remote add danny https://github.com/dannylamb/Crayfish-Commons.git`
- `git fetch`
- `git checkout issue-611`

Then ingest a tiff into Fedora, I put mine at http://localhost:8080/fcrepo/rest/test.tiff.

`curl -i -H "Authorization: Bearer islandora" -H "Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/test.tiff" "http://localhost:8000/hypercube/"` should return 200 and the OCR of the tiff.

`curl -i -H "Authorization: Bearer islandora" -H "Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/test.tiff" "http://localhost:8000/houdini/identify"` should return 200 and the json describing the image.

`curl -H "Authorization: Bearer islandora" -H "Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/test.tiff" -H "Accept: image/png" "http://localhost:8000/houdini/convert" > test.png` should return 200 and get you a png version of the image.

**Comment by dannylamb** [comment]
@Islandora-CLAW/committers ^^

**Comment by whikloj** [comment]
Nice work @dannylamb, I'll spin these up tonight. 👍

**Comment by whikloj** [comment]
Worked as described

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/Crayfish/commit/ad6d957dabc9b619102c20d398da68d3c2c2a447 and https://github.com/Islandora-CLAW/Crayfish-Commons/commit/f6532974f83745320906ea9b143ef3b1413795d9
