### ISSUE TITLE
Remove Amherst extensions from Vagrant install

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#613]
We're using Gemini for path mapping and Houdini for images, so we can get remove the Amherst extensions from the Vagrant install

- [ ] Delete https://github.com/Islandora-CLAW/claw_vagrant/blob/master/scripts/islandora-karaf-components.sh#L12-L20
- [ ] and https://github.com/Islandora-CLAW/claw_vagrant/blob/master/configs/karaf/alpaca.script#L13-L16
- [ ] and https://github.com/Islandora-CLAW/claw_vagrant/blob/master/configs/karaf/alpaca.script#L3
- [ ] EDIT: Also delete these lines so we don't try and deploy config for them: https://github.com/Islandora-CLAW/claw_vagrant/blob/master/scripts/config.sh#L24-L46

**Comment by bryjbrown** [comment]
I'll take this one, looks about my speed :)

**Comment by dannylamb** [comment]
@bryjbrown I just edited in a fourth chunk of lines to remove.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/claw_vagrant/commit/9ecdba0dff61afe9ed2d79d3485e240bbe25511f
