### ISSUE TITLE
Everything gets a mascot

### ISSUE THREAD

**Issue by manez** [Islandora-CLAW/CLAW#615]
Our mascot coverage is good, but there are a couple of gaps. I'm putting together some presentations and a poster about CLAW for the coming months that would benefit from having a graphic for everything, so I'd like to go through and fill in the gaps:

* Islandora Collection
* Islandora
* CLAWntology
* Milliner

Any others?

**Comment by dannylamb** [comment]
@manez I merged those three PRs.  You can hold off on CLAWntology until we actually need it.  I wouldn't advertise it.  Hopefully we'll never need it and it can ride off into the sunset.

**Comment by manez** [comment]
@dannylamb sounds good. Thanks for the merges. Unless some one can suggest a repo I've missed, I guess this one is complete.
