### ISSUE TITLE
Do we delete tombstones?

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#630]
Do we allow a way to delete tombstones from Fedora? This may not be a linked data best practice, but it may still be needed by some use cases?

Should this be a configuration in Drupal, or maybe in Milliner to make it harder to switch?

**Comment by acoburn** [comment]
Possibly worth noting, but "tombstones" are not part of the Fedora API specification.

**Comment by whikloj** [comment]
Good point @acoburn, best to assume they don't exist then

**Comment by acoburn** [comment]
I just wouldn't build anything complicated to support them, as it may be necessary to remove all of that code down the road.

**Comment by whikloj** [comment]
Well, I'm wondering if we should build the infrastructure to test for the existence of a tombstone and remove them if they are there?

**Comment by DiegoPino** [comment]
I would say yes @whikloj. Even if not part of the API, we have them on the fedora we run, and that means right now their presence means we can have issues, not a common issue since we are using the   internal PID minter.

**Comment by acoburn** [comment]
Just be aware that the way Fedora "advertises" tombstones: 

    Link: <http://localhost:8080/fcrepo/rest/some-resource/fcr:tombstone>; rel="hasTombstone"

Is incorrect (the `rel="hasTombstone"` token is not registered with IANA and so a full URI _should_ exist in that place). So, just be careful.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/2b3418e0fa4e5b9239c20a8fecedc42242b1d95c
