### ISSUE TITLE
How modular of an install do we provide?

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#637]
Part of https://github.com/Islandora-CLAW/CLAW/issues/635

This can be a pretty big rabbit hole, so I want to create a definitive scope for the first phase of development of a scripted install provided by the foundation.  This will be driven by the deployment configurations we want to support.  Those two things are the outcome I want from the ticket.  What deployment setups do we support and what are the packages we need to make those happen?

So let's start with 'What deployment setups do we support?"

I'm thinking an all-in-one install and then a reasonably broken apart stack.  Looking for guidance on what is reasonable to break out.  Here's what my gut is telling me:
1. Drupal
1. Fedora
1. Microservices
1. Karaf with Alpaca and API-X
1. Blazegraph
1. Solr
1. MySQL
1. Activemq
1. Canteloupe

Thoughts?

**Comment by whikloj** [comment]
Don't forget Cantaloupe which can go with Fedora or separate... probably separate is better to allow you to have your preservation layer completely separate from your display layer.

**Comment by dannylamb** [comment]
@whikloj Editing into original post

**Comment by bryjbrown** [comment]
Since one of the major goals of CLAW is scalability, it would make sense for each microservice (or any individual part of the stack that may need to grow/shrink dynamically) to be its own thing. That way you could spin up more Tesseracts or Imagemagicks as needed without each the overhead of anything else that isn't needed being spun up with it.

**Comment by ajs6f** [comment]
There was some discussion about this on https://github.com/Islandora-CLAW/CLAW/wiki/May-24%2C-2017 and my suggestion then was that we could start by putting everything that can go in one kind of container (i.e. servlet container, httpd/PHP, Karaf) into one of that kind and put each container into a Docker of its own. Then as we discover which pieces need scaling out by practice, we can break them out into their own Dockers.

That would start us out with something like three Dockers:

1. Apache httpd (or other webserver) with PHP gear containing Drupal and Crayfish Microservices and the SQL database supporting them
2. Karaf containing Alpaca, API-X and ActiveMQ
3. Tomcat or other servlet container containing Fedora, Canteloupe, Blazegraph and Solr

That's almost surely not as fine-grained as we might eventually want to be, but my hope in putting forward the suggestion is that we can start more coarse-grained than we know we will be and figure out _with experience_ how to subdivide.

Anyway, just a suggestion...

**Comment by dannylamb** [comment]
Closing this. We'll deal with it during sprint/planning.
