### ISSUE TITLE
Islandora.versioncounter Drupal Service and Entity Types (node) questions: Is media entity missing?

### ISSUE THREAD

**Issue by DiegoPino** [Islandora-CLAW/CLAW#654]
One of the phew custom functionalities we deliver via Islandora Module is the [`islandora.versioncounter` ](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora.services.yml#L22 )service 

This [service](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/src/VersionCounter/VersionCounter.php) is called invoked/triggered by an Entity type specific  legacy hook,  that handles an insert/update(increment) of a pair of values `(uuid,version`) into DB for: creation, update and delete of `nodes`

https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora.module#L84-L118

Under the new architecture nodes are the equivalent of RDF resources but I don't see the version counter used for media entities, which are the equivalent of non rdf sources.

Questions are:

 * Do we need to have the same for all media entities or is there an architecture decision on not having that?
 * How do we distinguish what needs a version counter? Should we be reading the existence of a Drupal RDF Mapping to decide?
 * Where/how is the version count used? (i could not find the usage of the `::get` method). Is this exposed or will this be exposed as part of the REST API?

**Comment by dannylamb** [comment]
@DiegoPino The version counter will be eventually used to allow conditional updates to resources.  The API effort has more or less completely halted, so I haven't bothered implementing it for other content entity types like media or users.

You've raised this question a few times now in a few different forums, which leads me to believe it's just too confusing to keep around.  I'm more than agreeable to removing this feature until we can start the API effort again in earnest after more of the foundation is laid.

**Comment by dannylamb** [comment]
We're no longer pursuing this feature
