### ISSUE TITLE
Transfer Carapace to the Islandora-CLAW organization

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#667]
@favenzio I've sent you an invite to become a temporary owner.  You can transfer the repo by going to its settings page and scrolling all the way down to the Danger Zone™

**Comment by Favenzio** [comment]
@dannylamb I have transferred the repo. In the section where it asks who should have access, I only selected committers (did not check the box for sprinters or temp admin team). Not sure if that was correct. As far as @whikloj question regarding claw_vagrant, I asked Bryan to submit the pull request, knowing that we would be transferring the repository shortly and all it would require afterwards would be updating that one line of code.

**Comment by dannylamb** [comment]
ty @Favenzio
