### ISSUE TITLE
Documentation: Migrate content from the 2017 Islandoracon hack/doc to official docs

### ISSUE THREAD

**Issue by ysuarez** [Islandora-CLAW/CLAW#668]
This is a meta-issue to keep track of work on migrating the content from the 2017 Islandoracon hack/doc documentation work. 

Quick shutout to some of the hack/doc participants whose Github handles I know, and that may want to chime on this issue: @kimpham54 @aulorbe @uconnjeustis

The content is stored in this [Google Doc](https://docs.google.com/document/d/1CN7mBYdU-ACYoDwWFncUwLPD2bLpt2FKG9CuT63_Pps/edit#heading=h.ptidptu8k2h)

Below are the sections from this document, with added content notes.  Sections of the content that have been added to the official CLAW documentation have been checked off.

# Sections

## Resources
* The Resources section contains a collections of CLAW related links.

- [ ] CLAW
* "CLAW Lessons - webinars on how to develop CLAW (they’re a bit outdated but still really useful)"

- [ ] Fedora
* This section is empty.

- [ ] Drupal 8
* Short section with a (Drupal.org link on Drupal 8)[https://www.drupal.org/docs/8/administering-drupal-8-site/managing-content] and a graphic showing the Drupal/Islandora/Fedora stack.

- [x] Linked Data & PCDM

## System Analogies
* These sections contain single paragraph descriptions of several CLAW components. There is also a [CLAW system diagram created](https://www.lucidchart.com/invitations/accept/85c16784-eb98-49fc-98f4-09d809bc426c) with  https://www.lucidchart.com. The diagram's "owner"is @kimpham54 , please contact her "if anyone has issues or would look to be added to the document as an editor."  

- [ ] Drupal 8 (drupal-project)

- [ ] Fedora 4

- [ ] Crayfish Microservices

- [ ] Gemini

- [ ] Milliner

- [ ] Houdini

- [ ] Hypercube

- [ ] Alpaca

- [ ] Syn

- [ ] triplestore

- [ ] API-X

## System Navigation
- [x] Adding a User

- [x] Creating a new user role

### Administrative tasks

- [x] How to add an item to a collection

- [x] How to create a new Islandora collection

- [ ] How to edit an object’s metadata

- [ ] How to edit multiple objects

- [ ] How to delete an object

- [ ] How to add an object to multiple collections

- [ ] How to purge/delete objects

- [ ] How to delete a collection and all of its child objects
* No documentation content, just questions about feature.

- [ ] How to batch delete multiple objects
* No documentation content, just questions about feature.

- [ ] How to make mass edits and/or find and replace
* This section is empty.

- [ ] How to review mapping of Metadata fields in an object
* "?\_format=JSONLD (or jsonld, append to your url resource in Drupal)"

- [ ] Reports
* No documentation content, just questions about feature.

- [ ] Interface Functions

- [ ] How do I create a new type

- [ ] How to control mapping via your own YAML file
* This section is empty.

NOTE: Here is a message found at the very bottom of this Google document with the goals the creators had for the future. It was labeled as being part of the report to the "opening session" of the conference.

Islandora Opening Session

1. We all wanted to learn more about CLAW and be able to explain it better
2. We made this document and we understand a lot more about CLAW and how to explain it to our various workplaces (how we’re going to do our work in CLAW)
3. **Thank G for Jared**
4. We want
    * To take this back to the Doc interest group and finish it
    * To build interlocking diagrams governed by a style guide (as well as other tools useful for diverse learning styles) - a general style guide would be good.
5. To have marginal callouts that highlight differences for those well versed in 7.x who will benefit from this kind of “just in time” info about what’s changed

**Comment by kimpham54** [comment]
Link to editable systems diagram: https://www.lucidchart.com/invitations/accept/85c16784-eb98-49fc-98f4-09d809bc426c. Let me know if anyone has issues or would look to be added to the document as an editor

**Comment by ysuarez** [comment]
@dannylamb I just ran into this old issue. I think it can be closed, since Islandora 8 v.1 has been released and this older docs/information may not apply at all.
