### ISSUE TITLE
Update allowed mimetypes for Images

### ISSUE THREAD

**Issue by manez** [Islandora-CLAW/CLAW#669]
Basic image content type is only allowing jpg and jpeg at the moment for OBJ and MEDIUM_SIZE.

Also, when the file is replaced the warning doesn't go away:

![image](https://user-images.githubusercontent.com/2371345/27619955-9b090cd2-5b9c-11e7-8904-ff56c2cefa15.png)

Separate issue? Drupal's problem? It doesn't stop the node from publishing; it's just a confusing thing in the UI.

**Comment by dannylamb** [comment]
@manez It's a Drupal config thang.  We can change it in the config that the module ships with so it's more open by default.  To fix for an individual site, you have to edit the field settings of MEDIUM_SIZE and OBJ on the Image object.
