### ISSUE TITLE
Deploy Carapace with Composer

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#671]
Give Carapace an appropriate composer.json file, and we'll put it up on packagist for all to enjoy.  We'll also have to update claw_vagrant and the Travis build system to use it.

**Comment by dannylamb** [comment]
Moving this to the Ansible install sprint to be handled there.

**Comment by dannylamb** [comment]
After https://github.com/Islandora-CLAW/carapace/pull/1 gets merged, please move this issue back to "In Progress" and assigned to me.  Then I'll add Carapace to https://github.com/Islandora-CLAW/drupal-project in a subsequent PR.

**Comment by jonathangreen** [comment]
Some good discussion about `drupal-project` https://github.com/Islandora-CLAW/CLAW/issues/700 @dannylamb

**Comment by dannylamb** [comment]
resolved with 7b5624b1a89dc7bb7650ea70d215bfeb3d622b1c
