### ISSUE TITLE
Create 'Web Image Preservation Master'

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#676]
Blocked by https://github.com/Islandora-CLAW/CLAW/issues/675.

Duplicate the 'Web Image' media bundle and name it 'Web Image Preservation Master'.  It should be identical except for the rdf mapping, which should have an `rdf:type` of `use:PreservationMaster` from the PCDM Use ontology: http://pcdm.org/2015/05/12/use.

**Comment by whikloj** [comment]
Should this new media bundle be included in the default setup for the "islandora image" or just installed but not configured?
