### ISSUE TITLE
Rename 'Image OBJ' to 'Tiff Image'

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#677]
That's really what it is.  Leave everything the same, including the rdf mapping, just rename it to Tiff Image.

**Comment by whikloj** [comment]
Looking at this, it appears we reference a config that does not exist here https://github.com/Islandora-CLAW/islandora_image/blob/8.x-1.x/config/install/field.field.node.islandora_image.field_obj.yml#L6

I could add it, but I'm not sure what it was supposed to be.
