### ISSUE TITLE
Create Basic and Large Image content types.

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#678]
Currently, islandora_image only provides one content type for images.  This means repositories are limited to Tiffs as preservation masters, excluding more basic images formats like png or jpeg.

We need to provide two content types, one for Basic Image functionality and one for Large Image functionality.  The main difference being the type of Media bundle that is allowed for the field_obj entity reference.

Basic images should not have field_jp2, field_tn, or field_medium_size.  Instead, there should only be field_obj with 'Web Image Preservation Master' as the only allowed type.

Large Image should be similar to the existing 'Islandora Image' content type, except field_medium_size should be field_web and reference 'Web Image' medias.  We also can drop TN because field_web with image styles is more than enough to get thumbnails.

**Comment by Natkeeran** [comment]
@whikloj 

Explored  using [Field Formatter Condition](https://www.drupal.org/project/fico) to conditionally switch between field formatters, but did not have much success in changing the render array ($build).  You may have better luck.  Note that fico has [ds](https://www.drupal.org/project/ds) as dependency.  

```
<?php
namespace Drupal\fico\Plugin\Field\FieldFormatter\Condition;

use Drupal\fico\Plugin\FieldFormatterConditionBase;

/**
 * Description for your plugin.
 *
 * @FieldFormatterCondition(
 *   id = "choose_file_formatter",
 *   label = @Translation("Choose file formatter"),
 *   dsFields = TRUE,
 *   types = {
 *     "all"
 *   }
 * )
 */
class ChooseFileFormatter extends FieldFormatterConditionBase {

  /**
   * {@inheritdoc}
   */
  public function alterForm(&$form, $settings) {
    // Define your formular elements here...
  }

  /**
   * {@inheritdoc}
   */

  public function access(&$build, $field, $settings) {
     \Drupal::logger('my_module3')->notice($settings["field_type"]);

    // Define the access here.
    // Restrict Access via: $build[$field]['#access'] = FALSE; .
  }

  /**
   * {@inheritdoc}
   */
  public function summary($settings) {
    return t("Condition: %condition (%settings)", [
      "%condition" => t('Choose your formatter')
    ]);
  }

}
```
