### ISSUE TITLE
Cannot uninstall islandora module

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#685]
From https://github.com/Islandora-CLAW/jsonld/pull/23

While uninstalling the core islandora module, this error occurs:
```
ubuntu@claw:/var/www/html/drupal/web/modules/contrib$ drupal module:uninstall islandora
 [ERROR] Attempt to create a field field_image that does not exist on entity type media.                                
```

It seems to be tied to the order in which our config entities get removed when uninstalling the module.

**Comment by whikloj** [comment]
References:
https://www.drupal.org/node/2661806

I've also seen this exception when working:
https://www.drupal.org/node/2622160

**Comment by whikloj** [comment]
I did some digging into this and it appears that the fields we add to the media entity type don't get stored.
I can't really explain it yet, but when we go to delete the fields on uninstallation. We end up in the [FieldConfig classes preDelete](https://api.drupal.org/api/drupal/core%21modules%21field%21src%21Entity%21FieldConfig.php/function/FieldConfig%3A%3ApreDelete/8.2.x) method. 
It hits this line.
```
$config['field_storage_uuid'] = $field->getFieldStorageDefinition()->uuid();
```
and then it runs to [`getFieldStorageDefinition()`](https://api.drupal.org/api/drupal/core%21modules%21field%21src%21Entity%21FieldConfig.php/function/FieldConfig%3A%3AgetFieldStorageDefinition/8.2.x)
where it fails to find any of our field names (field_mimetype, field_tn, field_height, etc) in the storage and throws the Exception.

So either we are not creating our fields correctly, or they are not expecting us to create fields...

**Comment by DiegoPino** [comment]
@whikloj nice catch! Probably we have some issue with the config entity. Will give it a look.

**Comment by whikloj** [comment]
Why is the field storage configured on the media instead of node like it is in islandora_image. Perhaps that is the problem?
ie.
`field.storage.media.field_file.yml` in islandora

versus

`field.storage.node.field_jp2.yml` in islandora_image.

**Comment by dannylamb** [comment]
@whikloj I think that's correct.  `field_file` is is the file entity reference that Media have.  The nodes have entity references to media that essentially correspond to datastream ids.

I'm wondering if it's just how we exported them?  Maybe it would be beneficial to just rebuild and re-export to see if that fixes the error.

**Comment by dannylamb** [comment]
So I dug even deeper and the issue appears to be that the field_storage is deleted before the field definition.  When deleting the definition it needs to look up the storage and ka-boom.

All of our exported field definitions explicitly declare the storage as a dependency, which makes me worried that we're hitting a bug in core Drupal module uninstall code. :disappointed:

**Comment by Natkeeran** [comment]
whikloj  script can be used in the meantime to uninstall islandora.  Note that MYSQL_USER has changed to drupal8: https://gist.github.com/whikloj/614fa21d7145b09197fd1e8513dd2f41

**Comment by whikloj** [comment]
I updated the script to use the **drupal8** user by default. But of course you can customize it.
