### ISSUE TITLE
Activemq Ansible Role

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#690]
### Description

Create an Ansible role to install activemq and add it to [the CLAW playbook](https://github.com/jonathangreen/claw-playbook).

As with all Ansible roles, check [Galaxy](https://galaxy.ansible.com/) for an existing role.  If one is found, look to see if it supports both Ubuntu and CENTOS.  If it does not support CENTOS, ask the maintainer if they would be receptive to a pull request later on.  If it looks well used and either supports CENTOS or is agreeable to a PR for supporting CENTOS, we should use it instead of creating new one.

If creating a new role, start by looking at https://github.com/Islandora-CLAW/claw_vagrant as a starting point.  Be sure that it is idempotent and can be run over and over again with no new effect.  Use Jinja templating to alter config when deploying instead of using `sed` a la claw_vagrant.

### Testing Instructions

Test the role by running [the CLAW playbook](https://github.com/jonathangreen/claw-playbook) after pulling in the changes.  Be sure to execute it multiple times to confirm it is idempotent.

**Comment by Natkeeran** [comment]
@dannylamb This looks like a self contained ticket.  You can assign this one to me for next week.

**Comment by Natkeeran** [comment]
@jonathangreen @dannylamb @MarcusBarnes 

Please review this role here: https://github.com/Natkeeran/activemq-role.  I have not integrated into https://github.com/Islandora-Devops/claw-playbook yet.  

I did review several ansible roles from galaxy, including [this one](https://galaxy.ansible.com/shelleg/activemq/).  They seemed bit complicated to duplicate the [activemq.sh](https://github.com/Islandora-CLAW/claw_vagrant/blob/master/scripts/activemq.sh) functionality.  Thus I followed @jonathangreen fits example to create this role.  

## Testing
To test it, you will need a bare metal ubuntu machine with java installed:

```
# Java
apt-get -y install openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre
sed -i '$iJAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' /etc/environment
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
```

Please see further notes here about setting up ansible [here](https://github.com/Natkeeran/Notes/blob/master/Ansible%20-%20Helloworld.md)

**Comment by MarcusBarnes** [comment]
I'll give this a run through this afternoon and or tomorrow morning and report back.  Thanks!

**Comment by dannylamb** [comment]
@Natkeeran Do you think you could make it part of claw-playbook and issue a PR against that? It would make it easier to review as a diff.

**Comment by Natkeeran** [comment]
@dannylamb @jonathangreen Pushed a branch here: https://github.com/Islandora-Devops/claw-playbook/tree/activemq.  

Please note that I am running into some issues such as below that I am not able to test this properly.  
```
TASK [webserver-app : Trusted Host Settings] ***********************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: path"}
```
or 
```
TASK [fits : Set fits.home in catalina.properties] *****************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: path"}
```

**Comment by jonathangreen** [comment]
@Natkeeran cool I'll try testing your branch and see what I get. If you want to make a PR from you branch it makes it way easier to give feedback on the code.

**Comment by Natkeeran** [comment]
@jonathangreen Pls see https://github.com/Islandora-Devops/claw-playbook/pull/6

**Comment by jonathangreen** [comment]
Closed with: https://github.com/Islandora-Devops/claw-playbook/commit/cab799c67d92563205403eea89074cfbfc8b740e
