### ISSUE TITLE
Install and Enable OpenSeadragon

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#693]
Add https://github.com/Islandora-CLAW/openseadragon to the list of modules to be installed and enabled here: https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L19

**Comment by jonathangreen** [comment]
My opinion would be to install the openseadragon module with composer.

**Comment by dannylamb** [comment]
@jonathangreen Hahaha, ninja'd by you.  Was about to put in a comment to see the other ticket for composer discussion.

**Comment by jonathangreen** [comment]
Seadragon config from claw_vagrant: 
https://github.com/Islandora-CLAW/claw_vagrant/blob/master/scripts/openseadragon.sh
