### ISSUE TITLE
Cantaloupe Ansible Role

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#694]
### Description

Create an [Ansible](https://www.ansible.com/) role to install [Cantaloupe](https://medusa-project.github.io/cantaloupe/) and add it to [the CLAW playbook](https://github.com/jonathangreen/claw-playbook).

As with all Ansible roles, check [Galaxy](https://galaxy.ansible.com/) for an existing role.  If one is found, look to see if it supports both Ubuntu and CENTOS.  If it does not support CENTOS, ask the maintainer if they would be receptive to a pull request later on.  If it looks well used and either supports CENTOS or is agreeable to a PR for supporting CENTOS, we should use it instead of creating new one.

If creating a new role, start by looking at https://github.com/Islandora-CLAW/claw_vagrant as a starting point.  Be sure that it is idempotent and can be run over and over again with no new effect.  Use Jinja templating to alter config when deploying instead of using `sed` a la claw_vagrant.

### Testing Instructions

Test the role by running [the CLAW playbook](https://github.com/jonathangreen/claw-playbook) after pulling in the changes.  Be sure to execute it multiple times to confirm it is idempotent.

**Comment by jonathangreen** [comment]
Cantaloupe info from vagrant scripts here:
https://github.com/Islandora-CLAW/claw_vagrant/blob/master/scripts/cantaloupe.sh
