### ISSUE TITLE
Postgres Ansible Role

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#695]
# STRETCH GOAL

### Description

Create an [Ansible](https://www.ansible.com/) role to install [PostgreSQL](https://www.postgresql.org/) and add it to [the CLAW playbook](https://github.com/jonathangreen/claw-playbook).

As with all Ansible roles, check [Galaxy](https://galaxy.ansible.com/) for an existing role.  If one is found, look to see if it supports both Ubuntu and CENTOS.  If it does not support CENTOS, ask the maintainer if they would be receptive to a pull request later on.  If it looks well used and either supports CENTOS or is agreeable to a PR for supporting CENTOS, we should use it instead of creating new one.

If creating a new role, start by looking at https://github.com/Islandora-CLAW/claw_vagrant as a starting point.  Be sure that it is idempotent and can be run over and over again with no new effect.  Use Jinja templating to alter config when deploying instead of using `sed` a la claw_vagrant.

### Testing Instructions

Test the role by running [the CLAW playbook](https://github.com/jonathangreen/claw-playbook) after pulling in the changes.  Be sure to execute it multiple times to confirm it is idempotent.

**Comment by ajs6f** [comment]
I think you could argue that this is a `Small` goal, but hard to say…

**Comment by dannylamb** [comment]
I'm sure there's an existing Galaxy role out there, but I put Medium because of the complications it may or may not cause with configuring the Drupal role.

Do you have the appropriate permissions to set the `Small` label yourself?

**Comment by jonathangreen** [comment]
I'd say we should almost certainly use this role: 
https://github.com/geerlingguy/ansible-role-postgresql

I think its meant to be basically a drop in replacement for the mysql role we are currently using.

**Comment by ajs6f** [comment]
@dannylamb No, I can't fool with labels, but I don't want to anyway unless we have a consensus that this really is smaller than the other issues labelled `Medium`.

**Comment by dannylamb** [comment]
Resolved with https://github.com/Islandora-Devops/claw-playbook/commit/06b8cba4b4f2233d94a3cccada6341e3e873e6b9
