### ISSUE TITLE
Audit claw_vagrant and claw-playbook

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#696]
Audit [claw_vagrant](https://github..com/Islandora-CLAW/claw_vagrant) for any possible roles not already in [claw-playbook](https://github.com/jonathangreen/claw-playbook) that do not have an issue for this sprint.

If anything missing is found, create an issue for it, give it an estimate label (Small, Medium, Large, or Super Size), and add it to the [Ansible Install Sprint](https://github.com/Islandora-CLAW/CLAW/projects/1) project.

**Comment by g7morris** [comment]
@dannylamb @jonathangreen Feels like this task dovetails potentially with this [one](https://github.com/Islandora-CLAW/CLAW/issues/701) Should I be "auditing" at the very least for anything that appears to be "missing" from the Vagrant Claw AND for OS porting opportunities e.g. identifying roles that need OS specific ports to RHEL/CENTOS? Your thoughts?

**Comment by jonathangreen** [comment]
I think this question goes to the goals of this sprint. The way I see it is that the goal is to bring the [claw-playbook](https://github.com/islandora-devops/claw-playbook) to a place where its at feature parity with the current [claw_vagrant](https://github..com/Islandora-CLAW/claw_vagrant) repo, but done in Ansible. This gives a convenient finish line for the first sprint and assists in the scope of the work to be done.  Given that goal, I think this ticket is to make sure we have a tickets ready to address all the functionality packed into the current vagrant box. 

Does this sound right @dannylamb or am I way off base?

> Should I be "auditing" at the very least for anything that appears to be "missing" from the Vagrant Claw 

I would say this ticket should be auditing [claw-playbook](https://github.com/islandora-devops/claw-playbook) and the [ansible install sprint](https://github.com/Islandora-CLAW/CLAW/projects/1?) project to make sure they together they create a plan to put all the functionality of [claw_vagrant](https://github..com/Islandora-CLAW/claw_vagrant) into [claw-playbook](https://github.com/islandora-devops/claw-playbook).

> for OS porting opportunities e.g. identifying roles that need OS specific ports to RHEL/CENTOS? 

I think this one is outside the scope of this sprint. My feeling is that almost every role will need an OS specific stub to deal with OS differences (package management, paths etc). I think this should be left for later.

**Comment by g7morris** [comment]
@jonathangreen Sounds clear to me. I'll include a passthrough per your first explanation of scope and will table the RHEL audit as explained. Thanks!

**Comment by dannylamb** [comment]
@jonathangreen Nailed it.

@g7morris Thanks for looking into this.

**Comment by jonathangreen** [comment]
@g7morris are you working on this one?

**Comment by g7morris** [comment]
@jonathangreen Yes I intend to as I look through overall progress and update documentation, feels like this is a natural by product. I'll be trying to post doc drafts by Wed/Thurs. I'll also update my progress here too. However having a second pair of eyes never hurts.

**Comment by dannylamb** [comment]
@g7morris Are we good to close this issue?

**Comment by dannylamb** [comment]
@g7morris Sry, wrong button!  Feel free to close this when you feel it's appropriate.
