### ISSUE TITLE
CLAW vagrant - installing search_api_solr and facets

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#698]
CLAW will make use of drupal modules to provide solr search and faceting related behaviour.  [Search API](https://www.drupal.org/project/search_api)  is already installed.  [Solr Search](https://www.drupal.org/project/search_api_solr) and [Facets](https://www.drupal.org/project/facets) need to be installed.  

## Additional Notes
* https://github.com/Natkeeran/Notes/blob/master/Configuring%20Apache%20Solr%20Search%20and%20Facets%20in%20CLAW.md

## Related Tickets
* https://github.com/Islandora-CLAW/CLAW/issues/646

**Comment by dannylamb** [comment]
Thanks @Natkeeran.
Thanks to @kimpham54 and @MarcusBarnes for testing, too.
