### ISSUE TITLE
Consider using grok instead of openjp2 with cantaloupe

### ISSUE THREAD

**Issue by jonathangreen** [Islandora-CLAW/CLAW#703]
## Idea

[Grok](https://github.com/GrokImageCompression/grok) is a fork of OpenJP2 that is focusing on performance. I compiled it and it seems to work as a drop in replacement for OpenJP2 as far as Cantaloupe is concerned. I also saw a huge speed improvement using Grok vs OpenJP2 with a 40Mb JP2 file.

Since its not in Ubuntu package management its a little harder to install, but I think we should consider shipping it with our vagrant config because it will make large jp2 with cantaloupe much easier to work with. 

Thoughts? 

## Compile instructions

```
$ apt install cmake libpng16-dev libtiff-dev liblcms2-dev
$ git clone -b v2.3.0 https://github.com/GrokImageCompression/grok.git
$ cd grok
$ mkdir build
$ cd build
$ cmake ../.
$ make && make install
```

**Comment by DiegoPino** [comment]
@jonathangreen and image quality/standard? Do you have some images around to compare? Sounds like a good plan, open version is sloooooow 👍

**Comment by jonathangreen** [comment]
Here are some test results Diego. Thanks for the prod to get some numbers behind this. Turns out my initial tests had caching enabled, so sometimes the image was coming out of the cache. After disabling all caching, the numbers don't look as good, but Grok is a still faster. 

It seems to get most of its advantage when: 
- there are multiple cores available
- we are working with a tile rather then the full image 

JP2 I tested with was 40mb, 6851x5601. My output format was jpeg.

## OpenJP2
- Single core
  - full image: 30702 msec
- Two cores
  - full image: 28912 msec
  - 100x100 tile: 20641 msec
  - 512x512 tile: 20405 msec

## Grok 
- Single core
  - full image: 28971 msec
- Two cores
  - full image: 18852 msec
  - 100x100 tile: 441 msec
  - 512x512 tile: 713 msec

## Kakadu
- Single core
  - full image: 13120 msec
- Two cores
  - full image: 8914 msec
  - 100x100 tile: 15 msec
  - 512x512 tile: 78 msec

**Comment by jonathangreen** [comment]
Resolved with: 
https://github.com/Islandora-Devops/claw-playbook/pull/2
