### ISSUE TITLE
Add PR template and travis to Openseadragon

### ISSUE THREAD

**Issue by jonathangreen** [Islandora-CLAW/CLAW#705]
Get openseadragon ready to be deployed with composer, so it can be added to ansible.

**Comment by dannylamb** [comment]
I did this probably as you were making the ticket: https://packagist.org/packages/islandora/openseadragon

**Comment by jonathangreen** [comment]
Awesome! Thanks @dannylamb. Figured I'd make a PR to add travis and the PR template as well.

**Comment by dannylamb** [comment]
closed via https://github.com/Islandora-CLAW/openseadragon/commit/a1284acb25a2e6d1f805b8858778e8ec9498de30
