### ISSUE TITLE
Default Search API Solr Settings using Vagrant

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#707]
The current version of vagrant [creates the Solr core as "CLAW"](https://github.com/Islandora-CLAW/claw_vagrant/blob/master/scripts/solr.sh#L21) but the [Drupal setup uses the search_api_solr_defaults](https://github.com/Islandora-CLAW/claw_vagrant/blob/master/scripts/drupal.sh#L85) which looks for a Solr core of "d8". This requires [updating the Drupal default_solr_server Solr core setting](http://localhost:8000/admin/config/search/search-api/server/default_solr_server/edit) before before Drupal can connect to the Solr server.

Two possible options: changing the solr.sh to use the same Solr core setting as Drupal 8 (i.e. change "solr create_core -c CLAW" to "solr create_core -c d8") OR find a way to update this setting in drupal.sh. (I couldn't find an obvious config file setting or Drush command, but I'm new to this environment.)

**Comment by dannylamb** [comment]
Thanks for reporting this @seth-shaw-unlv.

**Comment by ajs6f** [comment]
Potentially we could use Collections to deal with this:

https://lucene.apache.org/solr/guide/6_6/collections-api.html
