### ISSUE TITLE
claw-playbook fails to bring up fcrepo

### ISSUE THREAD

**Issue by jonathangreen** [Islandora-CLAW/CLAW#711]
Same issue as here with vagrant:
https://github.com/Islandora-CLAW/CLAW/issues/660

Fedora is trying to bring up its own broker. Need to have it use the external broker.

**Comment by ajs6f** [comment]
Fixed with https://github.com/Islandora-Devops/claw-playbook/commit/79d2160b8b284e6b839371b1688c8a8f20aa18ca. @jonathangreen, I think you can close this?

**Comment by jonathangreen** [comment]
@ajs6f closed!
