### ISSUE TITLE
claw-playbook has fcrepo-indexing-triplestore listening to the broadcaster queue

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#719]
I derped on review for https://github.com/Islandora-Devops/claw-playbook/pull/13.  We need to point fcrepo-indexing-triplestore for Api-X to the default Fedora topic.

**Comment by jonathangreen** [comment]
revolved with https://github.com/Islandora-Devops/claw-playbook/commit/17083126845853e118ec0a5e01d2ec2541ebab26
