### ISSUE TITLE
Alpaca gear up

### ISSUE THREAD

**Issue by ajs6f** [Islandora-CLAW/CLAW#725]
There are some convenient Gradle plugins available to engage code analysis tools at build time without adding any extra work for the developers. Why not use them?

[Gear up.](https://www.youtube.com/watch?v=WA0joYngQKE)

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/Alpaca/commit/ea1d9aab279cb12858e0c385e7796db19ee812ac
