### ISSUE TITLE
Issue with sync when claw_vagrant virtualbox is accessed via an ip

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#727]
In local testing/development workflow, we often access virtualbox over an ip.  Instead of NAT, we use the Bridge adapter.  More info about this setup [here](http://digitalscholarship.utsc.utoronto.ca/content/blogs/let-others-access-your-islandora-vm).  This setup does not change the network naming of the vagrant.  It disables port forwarding, however all needed ports are accessible over the network.

When using this setup, fedora is failing to sync.  Tracing back on this issue showed that Gemini db is not being populated.  

@whikloj and @ajs6f troubleshooted this issue.  

The issue seem to be that $path received here: https://github.com/Islandora-CLAW/Crayfish/blob/master/Milliner/src/Converter/DrupalEntityConverter.php#L55 seems to be incorrect.  The path is `8000/node/nid` instead of `node/nid`.  **Removing that 8000 resolves this issue (`$path = substr($path, 4);`).  However it is not clear where the 8000 is coming from.**

@whikloj suggested the issue might be in Alpaca (https://github.com/Islandora-CLAW/Alpaca/blob/master/islandora-indexing-fcrepo/src/main/java/ca/islandora/alpaca/indexing/fcrepo/FcrepoIndexer.java#L84 or https://github.com/Islandora-CLAW/Alpaca/blob/master/islandora-indexing-fcrepo/src/main/java/ca/islandora/alpaca/indexing/fcrepo/FcrepoIndexerBean.java#L131-L151).

This might be a general issue if CLAW gets deployed into an actual machine.

We need to add more logging in Alpaca to troubleshoot this issue.

**Comment by whikloj** [comment]
I'm way behind on the Alpaca stuff, but now I am wondering if it is actually in Drupal when the original Activity Stream is generated. Regardless of what is happening we should add some more DEBUG/TRACE level statements to Alpaca to make this easier to trace without altering code.

**Comment by dannylamb** [comment]
:+1: Nothing wrong with more, and more granular, logging.

**Comment by Natkeeran** [comment]
@whikloj @dannylamb 
This issue can be closed.  Looks like merging 640 and recent changes has addressed this issue.  Tested in claw-playbook.
