### ISSUE TITLE
Blazegraph namespace not automatically selected

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#728]
## Steps to reproduce
* Open a private window in FF or any browser.  
* Go to http://future.islandora.ca:8080/bigdata/#namespaces 

## Expected behavior
The islandora namespace should be selected so that when queries are run, results will be returned.

### The actual, incorrect behavior
The islandora namespace is not selected.  Queries return empty results.

## Notes
Not sure if this is the expected default behavior for blazegraph.  If so, we may have to provide some hints in the query page to let the user know that they have to use the islandora namespace!

**Comment by whikloj** [comment]
Yeah....sorry @Natkeeran we looked in to this before.
https://github.com/Islandora-CLAW/CLAW/issues/536

**Comment by Natkeeran** [comment]
@whikloj Added that to the documentation.

**Comment by whikloj** [comment]
@Natkeeran can we close this then?

**Comment by dannylamb** [comment]
Closed via https://github.com/Islandora-CLAW/claw_vagrant/commit/5307f5e37e98cca6d5df8bd7116659a9eb944afb

**Comment by dannylamb** [comment]
@Natkeeran++
