### ISSUE TITLE
no Blazegraph clustering for us freeloaders

### ISSUE THREAD

**Issue by ajs6f** [Islandora-CLAW/CLAW#730]
https://sourceforge.net/p/bigdata/mailman/message/36057734/

makes clear a new position from Blazegraph (SYSTAP) that they won't be supported clustered operation for scale-out or HA in their open source edition. I don't know to what extent Blazegraph was chosen for CLAW based on its scale-out characteristics, but to the extent that it was, this might give reason to try operation with another tuplestore (or two). (Jena might ought to have some forms of distributed operation coming available in another minor release or three, but as an all-volunteer no-funding project, no promises!)

The new Ansible should (fingers crossed!) make that much easier than before. To the extent that CLAW is acting against well-spec'd interfaces like SPARQL Query and Update, this shouldn't (fingers crossed 'til they start making weird cracking sounds!) be too hard.

Another approach would be to guarantee distribution for HA by building on top of generic SPARQL endpoints via [delta distribution](https://github.com/afs/rdf-delta), but that would be no small bucket of chicken wings to eat through.

**Comment by dannylamb** [comment]
Well that's :poop:.  When we decided on Blazegraph it was only GPU acceleration that was absent from the free version.

It would be a good exercise to try things out with another 3-store just to make sure they're really swappable, as we have good reason to do so now.  Scalability of the 3-store is still a pretty major concern even though it's not as central to stack as it used to be.

**Comment by ajs6f** [comment]
In my ideal world, our Ansible-fu would be so strong that we test with multiple 3stores _in CI_.

**Comment by ajs6f** [comment]
Closed for https://github.com/Islandora-CLAW/CLAW/issues/732
