### ISSUE TITLE
Audit claw-playbook for RHEL/CENTOS support

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#742]
We need to go through both our internal and external roles and audit them to see what already has support for RHEL/CENT systems.

The outcome of this ticket is a comprehensive list of what does and does not need work so that we can divide up the work into smaller tickets.

**Comment by dannylamb** [comment]
From @whikloj in Sprint Kickoff meeting: If we use tomcat 7 in RHEL/CENT, we need to use cantaloupe version 3.3.2 or older.

**Comment by whikloj** [comment]
From the related discussion with the Cantaloupe folks. 
https://github.com/medusa-project/cantaloupe/issues/160#issuecomment-341231132

**Comment by dannylamb** [comment]
- apache
- composer
- drupal 
- drupal-console
- drush
- geerlingguy.php
- git
- java
- mysql
- php
- postgresql
- solr

**Comment by ajs6f** [comment]
@dannylamb Do you want to close this in favor of #744 and #745?

**Comment by dannylamb** [comment]
yes, thank you
