### ISSUE TITLE
 Audit claw-playbook for RHEL/CENTOS support PART I

### ISSUE THREAD

**Issue by ajs6f** [Islandora-CLAW/CLAW#744]
We need to go through both our internal and external roles and audit them to see what already has support for RHEL/CENT systems.

The outcome of this ticket is a comprehensive list of what does and does not need work so that we can divide up the work into smaller tickets.

- apache
- composer
- drupal
- drupal-console
- drush
- geerlingguy.php

**Comment by ajs6f** [comment]
All of these roles appear to fail on Centos7 with the [same error](https://gist.github.com/ajs6f/87bb5e72cdc6566298c3c0b78a746f83). This with

- Ansible 2.3.1.0, 2.3.2.0, or 2.4.0.0.
- Linux 3.10.0-693.5.2.el7.x86_64 #1 SMP 
- CentOS Linux release 7.4.1708 (Core)

**Comment by DigitLib** [comment]
Ansible installation via pip (2.4.1) will succesfully install geerlingguy.php

**Comment by whikloj** [comment]
@ajs6f if you want to try and trace that error I'd recommend [PyCharm](https://www.jetbrains.com/pycharm/download/#section=mac) from JetBrains. They have a community version which is less full-featured but free.

**Comment by dannylamb** [comment]
Downloading the base box now to try it out for myself.  I'm on vagrant 2.3.2.

**Comment by jonathangreen** [comment]
I think maybe the issue is this: 
`ansible-galaxy install -r requirements.yml `**composer**` -vvv`
Are you meaning to install composer there? 

https://github.com/Islandora-Devops/claw-playbook/blob/master/Vagrantfile#L45
I'd expect the `ansible-galaxy` command to look more like: 
`ansible-galaxy install --role-file=requirements.yml --roles-path=roles/external --force`

Not sure if that is the issue or not, but it seems like it might be.

**Comment by ajs6f** [comment]
I'll try that @jonathangreen. Ansible newbies unite!

**Comment by ajs6f** [comment]
Holy smoke! @jonathangreen's tip seems to have made everything install successfully, or at least it claims to have. I will now be manually spot-checking the installs to see if they worked correctly for reals.

**Comment by whikloj** [comment]
@DigitLib what about 2.4.1, did it complete installing?

**Comment by ajs6f** [comment]
At this point I think everything did indeed work. To put that another way, in my simple spot testing, I didn't find anything that didn't work. Go @geerlingguy!

**Comment by dannylamb** [comment]
@ajs6f @DigitLib It seems like both of your lists will work.  Shall we close both of your tickets and move on to our internal roles?  Those will get unlocked after https://github.com/Islandora-CLAW/CLAW/issues/749 gets resolved.

**Comment by ajs6f** [comment]
Works for me, @dannylamb . You mean doing the same thing, but for our internal roles, right?

**Comment by DigitLib** [comment]
@dannylamb Ok.

**Comment by dannylamb** [comment]
@ajs6f Yep.  Once the bootstrapping is taken care of, the roles can be tested more or less individually if we want to make another list and split it up.

@DigitLib :+1: 

Let's close these two out.
