### ISSUE TITLE
Audit claw-playbook for RHEL/CENTOS support PART II

### ISSUE THREAD

**Issue by ajs6f** [Islandora-CLAW/CLAW#745]
We need to go through both our internal and external roles and audit them to see what already has support for RHEL/CENT systems.

The outcome of this ticket is a comprehensive list of what does and does not need work so that we can divide up the work into smaller tickets.

- git
- java
- mysql
- php
- postgresql
- solr

**Comment by DigitLib** [comment]
After Ansible installation trought pip install (v.2.4.1) on CentOS postrgresql = successfully!
via ansible-galaxy install geerlingguy.postgresql

**Comment by DigitLib** [comment]
default: Running ansible-galaxy...
- downloading role 'apache', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-apache/archive/2.1.1.tar.gz
- extracting apache to /home/digilib/Documents/claw-playbook/roles/external/apache
- apache (2.1.1) was installed successfully
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.4.5.tar.gz
- extracting php to /home/digilib/Documents/claw-playbook/roles/external/php
- php (3.4.5) was installed successfully
- downloading role 'composer', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-composer/archive/1.6.1.tar.gz
- extracting composer to /home/digilib/Documents/claw-playbook/roles/external/composer
- composer (1.6.1) was installed successfully
- downloading role 'git', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-git/archive/1.3.0.tar.gz
- extracting git to /home/digilib/Documents/claw-playbook/roles/external/git
- git (1.3.0) was installed successfully
- downloading role 'mysql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.7.2.tar.gz
- extracting mysql to /home/digilib/Documents/claw-playbook/roles/external/mysql
- mysql (2.7.2) was installed successfully
- downloading role 'postgresql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-postgresql/archive/1.3.1.tar.gz
- extracting postgresql to /home/digilib/Documents/claw-playbook/roles/external/postgresql
- postgresql (1.3.1) was installed successfully
- downloading role 'solr', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-solr/archive/3.5.5.tar.gz
- extracting solr to /home/digilib/Documents/claw-playbook/roles/external/solr
- solr (3.5.5) was installed successfully
- downloading role 'java', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-java/archive/1.7.4.tar.gz
- extracting java to /home/digilib/Documents/claw-playbook/roles/external/java
- java (1.7.4) was installed successfully
- downloading role 'drupal', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-drupal/archive/2.2.2.tar.gz
- extracting drupal to /home/digilib/Documents/claw-playbook/roles/external/drupal
- drupal (2.2.2) was installed successfully
- downloading role 'drush', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-drush/archive/2.0.1.tar.gz
- extracting drush to /home/digilib/Documents/claw-playbook/roles/external/drush
- drush (2.0.1) was installed successfully
- downloading role 'drupal-console', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-drupal-console/archive/1.1.0.tar.gz
- extracting drupal-console to /home/digilib/Documents/claw-playbook/roles/external/drupal-console
- drupal-console (1.1.0) was installed successfully
- adding dependency: geerlingguy.php
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.5.0.tar.gz
- extracting geerlingguy.php to /home/digilib/Documents/claw-playbook/roles/external/geerlingguy.php
- geerlingguy.php (3.5.0) was installed successfully

**Comment by dannylamb** [comment]
Seems good to close then.  Moving on to https://github.com/Islandora-CLAW/CLAW/issues/749
