### ISSUE TITLE
Update bootstrap.yml to work with Centos

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#749]
Right now our [bootstrap play](https://github.com/Islandora-Devops/claw-playbook/blob/master/bootstrap.yml) explicitly calls apt-get.  We should update it to use `package` instead: http://docs.ansible.com/ansible/latest/package_module.html

**Comment by jonathangreen** [comment]
We should totally take a look at the `package` module. I've never used it, but it seems perfect for this sort of thing. 

Another option that I've seen used more often when looking at other peoples roles is something like this: 
https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/main.yml#L51-L58
https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/setup-Debian.yml
https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/setup-RedHat.yml

I've never had to support multiple OS in Ansible, so I don't have a lot of insight into whats the best option. I just have read other folks roles, and I've seen the pattern I mentioned used a lot.

**Comment by jonathangreen** [comment]
Something else to note is that these lines: 
https://github.com/Islandora-Devops/claw-playbook/blob/master/bootstrap.yml#L14-L18

Are installing python so Ansible will work because Ubuntu doesn't ship with Python by default. If Cent does, then maybe we don't need a lot of the things in bootstrap at all.

**Comment by DigitLib** [comment]
Python is already installed in CentOS v. 2.5.7

**Comment by dannylamb** [comment]
@jonathangreen I see, just branch and have two separate plays.  I'll try to use `package` where I can, but clearly there's differences beyond just package managers so we'll probably have to adopt that sort of strategy.

**Comment by dannylamb** [comment]
^^PR is up
