### ISSUE TITLE
Test internal Ansible roles with Centos 7 PART II

### ISSUE THREAD

**Issue by ajs6f** [Islandora-CLAW/CLAW#751]
To include:
	
-	fcrepo 
-	fits 	
-	grok 	
-	karaf 	
-	openseadragon 	
-	tomcat8 	
-	webserver-app

**Comment by ajs6f** [comment]
`tomcat8` fails with:
```
failed: [localhost] (item=[u'tomcat8']) => {"changed": false, "cmd": "apt-get update", "failed": true, "item": ["tomcat8"], "msg": "[Errno 2] No such file or directory", "rc": 2}
```

**Comment by DigitLib** [comment]
Downloading and installing Tomcat 8.0.47 on CentOS forked from https://github.com/NicolasMas/ansible.tomcat was successful. I adapted user, group and systemd file to tomcat8, here is adapted vesion https://github.com/DigitLib/ansible-role-tomcat-cent. It install tomcat in /opt dir but I linked it to /var/lib/tomcat8, adapted restart command. Installation of FITS and FCREPO was successful! Need to implement in ansible role tomcat8 if it is agreed with ver8 on CentOS.

**Comment by ajs6f** [comment]
As one CentOS (really RHEL) site, 8 is fine with SI.

**Comment by DigitLib** [comment]
Great! ver 8.0 of tomcat is end of life in june 2018.  Here is a note from official site "Users of Tomcat 8.0.x should be aware that the Tomcat team have announced the end of life date for Tomcat 8.0.x. Users of Tomcat 8.0.x should plan to upgrade before Tomcat 8.0.x reaches end of life". If we have an oportunity to chose a version, maybe it is not bad idea to have v8.5 or to plan in that direction.
