### ISSUE TITLE
Claw-Playbook broken in Ubuntu

### ISSUE THREAD

**Issue by jonathangreen** [Islandora-CLAW/CLAW#752]
The recent PR for CentOS broke Claw Playbook for Ubuntu:
https://github.com/Islandora-Devops/claw-playbook/pull/27

```
PLAY [bootstrap] ***************************************************************

TASK [Gathering Facts] *********************************************************
Friday 10 November 2017  10:38:14 -0400 (0:00:00.091)       0:00:00.091 ******* 
fatal: [default]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 0}
```

The issue is that we enabled `gather_facts` in the bootstrap play:
https://github.com/Islandora-Devops/claw-playbook/blob/master/bootstrap.yml#L6

Because `gather_facts` runs before anything else, and Ubuntu doesn't have Python installed by default the play fails. I realize we probably need to `gather_facts` in order to be able to know if we are running on cent or not, so we have a bit of a bootstrapping problem. 

One thing we could do is to set `gather_facts: no` then conditionally run the first task on an environment variable. Then force gathering facts by calling the [`setup`](http://docs.ansible.com/ansible/latest/setup_module.html) module. Another option is to conditionally run a shell provisioner in vagrant to setup python, I like doing it in ansible because Ubuntu lacking python will be a problem on real servers too.

**Comment by jonathangreen** [comment]
@dannylamb @whikloj

**Comment by dannylamb** [comment]
@jonathangreen :man_facepalming: K.  I'm mid `vagrant up` right now testing https://github.com/Islandora-Devops/claw-playbook/pull/25, but I should be able to work through it with the method you've outlined this afternoon.

**Comment by dannylamb** [comment]
hoppin' on this one now
