### ISSUE TITLE
Drupal 8 need php  5.5.9+ - CentOS installed 5.4.6

### ISSUE THREAD

**Issue by DigitLib** [Islandora-CLAW/CLAW#754]
TASK [drupal : Generate Drupal project with composer package.] *****************
Friday 10 November 2017  19:53:27 +0100 (0:00:00.333)       0:03:56.784 ******* 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/html/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:01:19.526405", "end": "2017-11-10 18:54:46.980154", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2017-11-10 18:53:27.453749", "stderr": "Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory\nInstalling drupal-composer/drupal-project (8.x-dev 89a6e99a1a536a9bbd5bb5af65b92f68855348ab)\n  - Installing drupal-composer/drupal-project (8.x-dev 89a6e99): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)         \b\b\b\b\b\b\b\b\b\nCreated project in /var/www/html/drupal\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - drupal/console 1.1.0 requires php ^5.5.9 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/console 1.0.2 requires php ^5.5.9 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - Installation request for drupal/console ^1.0.2 -> satisfiable by drupal/console[1.0.2, 1.1.0].", "stderr_lines": ["Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory", "Installing drupal-composer/drupal-project (8.x-dev 89a6e99a1a536a9bbd5bb5af65b92f68855348ab)", "  - Installing drupal-composer/drupal-project (8.x-dev 89a6e99): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)         \b\b\b\b\b\b\b\b\b", "Created project in /var/www/html/drupal", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - drupal/console 1.1.0 requires php ^5.5.9 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/console 1.0.2 requires php ^5.5.9 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - Installation request for drupal/console ^1.0.2 -> satisfiable by drupal/console[1.0.2, 1.1.0]."], "stdout": "", "stdout_lines": []}

**Comment by DigitLib** [comment]
Do we need to import new repos for CentOS to solve this issue, if yes then maybe to add additional repo https://github.com/geerlingguy/ansible-role-repo-remi where is php7?

**Comment by dannylamb** [comment]
@DigitLib++  I was pretty sure we'd run into this.  Personally, I'd say PHP 7 since you're already having to reach out to non-standard repos.  I'll let others speak up, though.

@ajs6f @whikloj?

**Comment by DigitLib** [comment]
php 7 installed via https://github.com/geerlingguy/ansible-role-repo-remi
but need to be enabled in geerlingguy.php to use remo-php70

**Comment by whikloj** [comment]
I'm 👍 for PHP 7.0 if we are going out anyways.

**Comment by ajs6f** [comment]
Sorry for missing this-- this would be a problem for SI, but I don't know how big of one. We definitely cannot deploy PHP 7 now, and I'm not sure how long it will take. I will go do some research.

**Comment by seth-shaw-unlv** [comment]
@DigitLib [commented on the selinux thread](https://github.com/Islandora-Devops/claw-playbook/pull/42#issuecomment-357432227) regarding PHP, which is relevant here. The linked solution works for me with the exception of the line `php_executable: "php56"` in webserver.yml which causes geerlingguy.composer to fail.

**Comment by DigitLib** [comment]
@seth-shaw-unlv Yes geerlingguy.composer failed, but with regular php drupal fail. We must find some solution....

**Comment by seth-shaw-unlv** [comment]
Huh, it passed for me (well, it got all the way to openseadragon, another issue). Let me destroy and do a fresh provision to see if it fails this time.

**Comment by seth-shaw-unlv** [comment]
vagrant destroy, vagrant up [based on this commit](https://github.com/seth-shaw-unlv/claw-playbook/commit/f210c90c2a69540a4d31a65f32f702aaf2cd3d17) got me all the way to openseadragon. I already have a fix for that based on the old unified playbook that I'm working on getting a patch ready for.

**Comment by DigitLib** [comment]
Great!

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-Devops/claw-playbook/commit/d4990d38e94d2fa10d9c87ee4b5221b37e873047
