### ISSUE TITLE
CLAW-playbook: ubuntu user dependency 

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#760]
Currently webserver-app role has a dependency on an ubuntu user: https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/defaults/main.yml#L12

That task use the apache user `www-data`.  It would need to be generalized to support other operating system.  It can also be clarified via documentation.

**Comment by whikloj** [comment]
👍 
To clarify, we want to replace the default `ubuntu` user with `www-data` which will work for Ubuntu in non-vagrant installations. 

But we also need the Centos/RHEL apache user (I think it is `apache`) and adjust to use that in Centos/RHEL builds.

**Comment by seth-shaw-unlv** [comment]
Yes, the CentOS apache user is `apache`

**Comment by Natkeeran** [comment]
This has been addressed with this PR : https://github.com/Islandora-Devops/claw-playbook/commit/d23f819720f84228956cdffa643d4c680ff63f88
