### ISSUE TITLE
Make it easier to change Crayfish URLs

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#761]
Currently the Crayfish ansible role has separate URLs for each service, this makes changing the URL harder.

This task is to define a general variable (or 2) for the hostname and port then re-use those in all the other variables. 

This keeps the separation in place in case we decide to split these out, but also makes a global change easier.

Repeated URLs:
- `crayfish_..._fedora_base_url`
   - https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/crayfish/defaults/main.yml#L29
   - https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/crayfish/defaults/main.yml#L49
   - https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/crayfish/defaults/main.yml#L68
   - https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/crayfish/defaults/main.yml#L80

-

**Comment by Natkeeran** [comment]
fedora_base_url is defined https://github.com/Islandora-Devops/claw-playbook/blob/fdb08ff025908ef10f75c253055e949fa258e5ef/inventory/vagrant/group_vars/webserver/drupal.yml#L53.
