### ISSUE TITLE
 CLAW-playbook: Allow for other than root to be drupal_db_user

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#762]
Currently the playbook allows for drupal_db_user to be [specified](https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L20).  However, if another value is specified other than root, it fails.

```
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "site-install", "standard", "-y", "--root=/var/www/html/drupal/web", "--site-name=Islandora-CLAW", "--account-name=dragomansadmin", "--account-pass=Iris4lib", "--db-url=mysql://drupal8user:aaaaa@127.0.0.1/drupal8"], "delta": "0:00:00.252369", "end": "2017-12-14 12:07:28.189216", "msg": "non-zero return code", "rc": 1, "start": "2017-12-14 12:07:27.936847", "stderr": "Failed to create database: ERROR 1045 (28000): Access denied for user\u001b[31;40m\u001b[1m[error]\u001b[0m\n'drupal8user'@'localhost' (using password: YES)", "stderr_lines": ["Failed to create database: ERROR 1045 (28000): Access denied for user\u001b[31;40m\u001b[1m[error]\u001b[0m", "'drupal8user'@'localhost' (using password: YES)"], "stdout": "You are about to CREATE the 'drupal8' database. Do you want to continue? (y/n): y", "stdout_lines": ["You are about to CREATE the 'drupal8' database. Do you want to continue? (y/n): y"]}
```

**Comment by whikloj** [comment]
Does that user have create database permissions in MySQL?

**Comment by dannylamb** [comment]
@DigitLib and I have been seeing
```
TASK [mysql : Ensure MySQL users are present.] *********************************
Thursday 11 January 2018 17:58:08 +0100 (0:00:00.014) 0:00:15.118 ******
failed: [default] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
```
but for different reasons.

For me it happens when re-provisioning because of another failure.  I can't get past mysql when using the root user.

@DigitLib is trying on CENTOS and failing first time.

**Comment by whikloj** [comment]
@dannylamb @DigitLib - I hit this error, only when trying to run the playbook a second time. But I have a [ticket here](https://github.com/Islandora-CLAW/CLAW/issues/778) and a PR attached to it.

**Comment by whikloj** [comment]
Resolved (I believe) with https://github.com/Islandora-Devops/claw-playbook/commit/c74b1859e7d6a49d15eb2772c663c05e2c02013c and https://github.com/Islandora-Devops/claw-playbook/commit/5697b4bec497e1f89d6cc8e33ed371648bf550d5
