### ISSUE TITLE
Have the option of not storing master binary in Drupal

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#769]
| Title (Goal)  | Have the option of not storing master binary in Drupal |
--------------- |------------------------------------                           |
| Primary Actor | Repository admin |
| Scope         | Architecture       |
| Level         | High |
| Story         | As a repository admin, I want to be able to configure my Islandora repo to not store a copy of the master (formerly known as OBJ) binary in Drupal. The binary would be stored only in Fedora. Two motivations for this: 1) to avoid doubling storage requirements and 2) to avoid doubling management requirements, e.g. validating checksums.|

**Comment by DiegoPino** [comment]
+1

**Comment by bryjbrown** [comment]
+1, derivs in Drupal and masters in Fedora seems like a thing people are gonna want.

**Comment by ajs6f** [comment]
+1 to this backwards. WHAAAAAA?!

I want to be able to store masters _only_ in Drupal. Not joking. I want an LDP backend for several reasons, but preservation isn't one of them, so putting masters in LDP doesn't help me at all.

**Comment by mjordan** [comment]
@ajs6f I was seeing this as configurable ("the option to"), although not necessarily something you'd want to toggle every few days.

**Comment by ajs6f** [comment]
@mjordan Right on, I'm just adding that we want a three-way switch; masters to one side, masters to the other side, and (default) masters to both.

**Comment by dannylamb** [comment]
:+1:, but is there a need for storing both, really?  I'm fine with just a regular switch between Drupal and Fedora.

**Comment by ajs6f** [comment]
I'm fine with whatever meets my use case, which is just the one way! :grin: As long as I don't have to push any more into Fedora than I actually want to, all good.

**Comment by dannylamb** [comment]
https://www.drupal.org/project/flysystem seems to support multiple filesystems.  Adapters are written as plugins and in theory there'd be a way to denote the destination when uploading a file.  I'd have to do a deep dive to confirm all that, though.

**Comment by ajs6f** [comment]
Would that mean synchronous operation?

**Comment by dannylamb** [comment]
It depends.  For your use case, everything can still be asynchronous.  Ingest into Drupal -> Generate derivatives -> Derivatives go in Fedora.

For the use case of putting preservation masters in Fedora but everything else in Drupal, staying asynch will incur double storage temporarily.  That is, Ingest in Drupal -> Flush to Fedora -> Delete from Drupal.  Going synchronous just on certain uploads would prevent that if it doens't unravel the design of the entire application :cry:

**Comment by ajs6f** [comment]
My use case actually doesn't include derivatives -> backend. It's just metadata -> backend, masters and derivatives stored elsewhere (not in Drupal). But it may be (it's not at all unlikely) that our set up is "weird" (= unlike most other sites) and if so, we can deprioritize this use case.

**Comment by dannylamb** [comment]
Weird use cases are ok.  Maybe you wanna make one yourself / your organization?  It wouldn't hurt.

I suspect you could get by with what we have now if you don't plan on generating derivatives through Islandora.

Back on point: it'll take some thought / exploration to figure out he least insane approach.  Looks like we're butting up on some Drupal opinions like "there's only one file system".

**Comment by ajs6f** [comment]
@dannylamb I made https://github.com/Islandora-CLAW/CLAW/issues/771, but I can't label it (or figure out how to use the use case template, which is probably just me not understanding Github).

**Comment by whikloj** [comment]
@ajs6f I added the label, the permissions in Github are weird. We're still missing something I think.

**Comment by dannylamb** [comment]
@ajs6f @whikloj So... finally found this.  Looks like you need _write_ permissions to add a label or move an issue around...  I'd be fine with @ajs6f having those permissions, but I can't say I feel that way about _everybody_.

**Comment by ajs6f** [comment]
Nice, Github. :slow-clap:

**Comment by dannylamb** [comment]
@Islandora-CLAW/committers Install PR for work that directly addresses this use case is up.  I have to circle through all the related PRs and update/add tests, etc... but you can still totally check it out and give the feature a whirl.

**Comment by dannylamb** [comment]
I should mention this also addresses @ajs6f's reversed use case, as well ;-0

**Comment by ajs6f** [comment]
Snazzy! I am finishing up work on a reliable test instance, and should be able to look at this soon, but maybe not in time to test. Def don't wait to hear from me to merge.

**Comment by rosiel** [comment]
Is this solved by the new configuration opportunities we have using Flysystem?

**Comment by dannylamb** [comment]
@rosiel It most certainly is.
