### ISSUE TITLE
Add optimistic locking to PATCH requests

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#772]
From https://github.com/Islandora-CLAW/islandora/pull/52

Look for a user provided header and use its contents to compare versions with https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/src/VersionCounter/VersionCounter.php .  If a number provided is stale, reject the request with a 412 Precondition Failed.

You can name the header whatever sounds best.  X-Islandora-Version-Count is the best I can come up wtih at the time of writin this issue, but whatever confuses people the least is what we should gow tih.

You'll want to do the check as early as possible in a way that functions with Drupal caching.  You could listen to Kernel::RESPONSE at priority 129 (that's just before the REST resource listener responds). Howerver, I think that means the entity is already loaded.  If we wanted to avoid the entity load and just look at the db table, we could give it a ridiculously high priority and see how that plays out with caching.

This could potentitally be a Stack PHP middleware too, but I don't know which approach is best.

Also... looks like I got a little too worked up and clobbered the tests for it during the Context refactor ^_^ So you'll need to dig that out of history and add it back with whatever tests you write: https://github.com/Islandora-CLAW/islandora/blob/d357de4cfbc43b245555c1dbf8e9cf72caa800d1/tests/src/Kernel/VersionCounterTest.php

**Comment by whikloj** [comment]
@dannylamb can this be closed now that we are using `PUT` and `DELETE` only?

**Comment by dannylamb** [comment]
Yeah, sure. We don't need this now and if anyone wants it weve got a starting point in our got history.
