### ISSUE TITLE
Drupal properties are not being indexed in the triplestore

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#774]
In the CLAW vagrant with the following claw-playbook commit:
```
commit 8ace2557ef8f5f8964c81ab879bcbb000733cda1
Author: Jared Whiklo <jwhiklo@gmail.com>
Date:   Wed Jan 17 09:19:52 2018 -0600
```
The drupal properties are not being indexed in the triple-store.

We should have triples such as, but they are not being populated. 
```
<http://localhost:8000/node/1> dcterm:title "blah"
```

The Fedora triples are being populated:
```
<http://localhost:8080/fcrepo/rest/47/6b/d7/32/476bd732-d77e-4ef3-8bb2-74b8445e238a>  dcterm:title "blah"
```

## Steps to Reproduce
* Fire up the vagrant
* Create a node in drupal
* Go to triplestore, select islandora namespace, check

**Comment by whikloj** [comment]
islandora-triplestore-index is using the old `kb` namespace for Drupal. So your triples are there just not in the `islandora` namespace.

So I am guessing [this isn't](https://github.com/Islandora-Devops/ansible-role-alpaca/commit/5430b5f7f1112d1a22440cf5dcb914442d43e437) getting applied, not sure why not. But I can see my configuration file is incorrect.

**Comment by Natkeeran** [comment]
Thank you @whikloj 

That would be my fault.  I overwrote the setting with this PR here: https://github.com/Islandora-Devops/claw-playbook/commit/8c13cd21b7ad6d306b5de896aa979323c51bf6fa.  I may have copied an older config.  I will issue a PR to correct this.

**Comment by whikloj** [comment]
😆  awesome...I would never have figured that out. This ansible thing has so many places to hide stuff.

**Comment by dannylamb** [comment]
Closed via https://github.com/Islandora-Devops/claw-playbook/commit/c652a489dabb1ca2a1eff2c9b673469c7e08b70f
