### ISSUE TITLE
Openseadragon fails to install

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#775]
ansible-role-drupal-seadragon fails with CentOS 7. The shell calls drush but it isn't found. [The fix is to use the drush_path variable instead](https://github.com/seth-shaw-unlv/ansible-role-drupal-openseadragon/commit/1e6251fa1b6e3e516e0840b89d53b37abc3fed92). I'll issue a pull request with the fix, once I figure out how to do it...

**Comment by whikloj** [comment]
Good call @seth-shaw-unlv, I should have be doing that anyways.

I'll note that I don't think the `{{ drush_path }}` is defined in the openseadragon role so you probably need to define a variable and add it to one of the top level `group_vars` files.

**Comment by seth-shaw-unlv** [comment]
Ah, yes, making these things idempotent... Could I just add it to the repo's defaults/main.yml? Granted, it won't work at all if drush isn't installed, so we should note that in the docs too....

**Comment by seth-shaw-unlv** [comment]
I've updated the pull request to include the variable in defaults/main.yml and updated the README.

**Comment by DigitLib** [comment]
@seth-shaw-unlv It passed on CentOS

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-Devops/ansible-role-drupal-openseadragon/pull/4
