### ISSUE TITLE
claw-playbook: ../roles/internal/webserver-app failed

### ISSUE THREAD

**Issue by DigitLib** [Islandora-CLAW/CLAW#776]
TASK [webserver-app : Uninstall core search module] ****************************
Friday 19 January 2018  01:27:14 +0100 (0:00:00.809)       0:16:12.599 ******** 
fatal: [default]: FAILED! => {"failed": true, "msg": "The conditional check ''successfully uninstalled' in uninstall_search.stdout' failed. The error was: error while evaluating conditional ('successfully uninstalled' in uninstall_search.stdout): Unable to look up a name or access an attribute in template string ({% if 'successfully uninstalled' in uninstall_search.stdout %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"}

**Comment by seth-shaw-unlv** [comment]
This is due to the webserver_app_user being set incorrectly when using CentOS. I'm posting a PR to resolve this momentarily.

**Comment by whikloj** [comment]
@DigitLib if you can confirm @seth-shaw-unlv's fix (https://github.com/Islandora-Devops/claw-playbook/pull/49) fixed your problem the we can close this issue.

**Comment by DigitLib** [comment]
@whikloj Confirmed! We can close it.
