### ISSUE TITLE
Syn not installed in claw-playbook

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#777]
Just noticed that based on the [fcrepo-syn install](https://github.com/Islandora-Devops/ansible-role-fcrepo-syn/blob/master/tasks/install.yml) tasks in its playbook we never actually copy the jar into the fcrepo webapp.

Just tried to do a test against a running claw-playbook.
```
> curl -i -XPUT "http://localhost:8080/fcrepo/rest/tester"
HTTP/1.1 201 Created
Server: Apache-Coyote/1.1
ETag: W/"ffc459ee1ad5bbed2b4718f433d82b8828565fd6"
Last-Modified: Sun, 21 Jan 2018 02:08:16 GMT
Location: http://localhost:8080/fcrepo/rest/tester
Content-Type: text/plain
Content-Length: 40
Date: Sun, 21 Jan 2018 02:08:16 GMT

http://localhost:8080/fcrepo/rest/tester
```

**Comment by dannylamb** [comment]
And to think of all the times I bothered with auth in curl...  Never once did I try it without creds or a token :man_facepalming:

**Comment by ajs6f** [comment]
Perhaps the best fix here is to use [Maven War overlays](https://maven.apache.org/plugins/maven-war-plugin/overlays.html) (or the Gradle equiv) to build a directly-deployable artifact? That has always worked much better for me than pushing "naked" JAR files in and out of web apps.
