### ISSUE TITLE
Carapace is not a module

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#779]
@rosiel and @Natkeeran noticed (and I subsequently also hit) this error.
```
TASK [geerlingguy.drupal : Install configured modules with drush.] **********************************************************************************************
Wednesday 24 January 2018  16:25:02 -0600 (0:00:16.817)       0:12:09.833 ***** 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "pm-enable", "-y", "rdf", "responsive_image", "syslog", "serialization", "basic_auth", "rest", "simpletest", "restui", "media_entity", "media_entity_image", "devel", "search_api", "carapace", "islandora_image", "search_api_solr", "search_api_solr_defaults", "facets", "--root=/var/www/html/drupal/web"], "delta": "0:00:00.509111", "end": "2018-01-24 22:25:02.431969", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-01-24 22:25:01.922858", "stderr": " [error]  Unable to install modules rdf, responsive_image, syslog, serialization, basic_auth, rest, simpletest, restui, media_entity, media_entity_image, devel, search_api, carapace, islandora_image, search_api_solr, search_api_solr_defaults, facets due to missing modules carapace. ", "stderr_lines": [" [error]  Unable to install modules rdf, responsive_image, syslog, serialization, basic_auth, rest, simpletest, restui, media_entity, media_entity_image, devel, search_api, carapace, islandora_image, search_api_solr, search_api_solr_defaults, facets due to missing modules carapace. "], "stdout": "", "stdout_lines": []}
```

Which is essentially a problem enabling the carapace module, because carapace is a theme.

So [this line](https://github.com/Islandora-CLAW/carapace/blob/8.x-1.x/composer.json#L4) should actually be 
```
"type": "drupal-theme",
```
So its installed in the correct location and doesn't cause this error.

**Comment by Natkeeran** [comment]
Is there any way to modify the composer dependency to point to this branch: https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L15

I tried to get this branch https://github.com/whikloj/carapace/tree/issue-779 like `- "whikloj/carapace:dev-issue-779"`.  That does not work.  I could not get [alias](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) to work either.

**Comment by Natkeeran** [comment]
This issue has been addressed with the following PRs:

* https://github.com/Islandora-Devops/claw-playbook/pull/52
* https://github.com/Islandora-CLAW/carapace/pull/4
