### ISSUE TITLE
claw-playbook: blazegraph failed in CentOS-fixed

### ISSUE THREAD

**Issue by DigitLib** [Islandora-CLAW/CLAW#786]
Destination of RWStore.properties was defined in /opt/blazegraph/conf but must be in tomcat8/webapps/bigdata/WEB-INF/classes path. this [fix](https://github.com/Islandora-Devops/ansible-role-blazegraph/commit/33b3f3c78e28a7f1c2bb26fbb690d42ee105ffda) path to this destination and also changed the tasks steps to enable this [path](https://github.com/Islandora-Devops/ansible-role-blazegraph/pull/4/commits/f574cabf54dd6843bf5d3431a1fcc333299ce149).

**Comment by whikloj** [comment]
This is not true, you can definitely run blazegraph with the configuration file outside of the classpath. See documentation steps here (https://wiki.blazegraph.com/wiki/index.php/NanoSparqlServer)

But it could be that we are not defining the `$JAVA_OPT` properly in Centos. 

We should be adding `-Dbigdata.propertyFile={{ blazegraph_home_dir }}/conf/RWStore.properties` to 

* `/etc/defaults/tomcat` in Ubuntu
* `/etc/profile.d/tomcat.sh` in Centos

For Centos that file probably won't exist

**Comment by whikloj** [comment]
Oops sorry wrong parameter, we are setting the correct one here (https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/tomcat.yml#L22)

@DigitLib can you check if that parameter ends up in the `$JAVA_OPTS` in Centos, if not that might explain why it is not coming up.

**Comment by DigitLib** [comment]
@whikloj you were right! after checked $JAVA_OPTS it work now on CentOS!
