### ISSUE TITLE
Memory not sufficient

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#788]
When claw-playbook is launched in a 2 GB RAM, the following error get thrown.  Stopping apache and tomcat and restarting services seems to resolve this issue.  Need to clarify memory requirements.  

```
[Tue Jan 30 19:48:02.602344 2018] [:error] [pid 32346] [client 142.1.101.243:34448] PHP Fatal error:  Out of memory (allocated 10485760) (tried to allocate 65536 bytes) in /var/www/html/drupal/vendor/symfony/class-loader/ApcClassLoader.php on line 110
```

**Comment by dannylamb** [comment]
Let's bump it to 4GB for safety.  Even at 3 composer will still crap out on you.
