### ISSUE TITLE
Followup with geerlingguy to see if drupal version can be specified

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#789]
Currently we are planning to use https://github.com/Islandora-CLAW/drupal-project to specify a drupal version.  @jonathangreen suggested further research to see if it is possible to specify a drupal version in  https://github.com/geerlingguy/ansible-role-drupal.  This ticket is to follow up that issue.

**Comment by DiegoPino** [comment]
@Natkeeran seems like that ansible-role-drupal allows for that using the drupal_deploy_version: some-branch option.  I see it handles also drupal console (composer way) deployment and the original drush one, which would trigger something like ```drush dl drupal-8.6.x-dev``` followed by a [drush site-install ](https://drushcommands.com/drush-8x/core/site-install/) using the previously downloaded version of drupal. But that is documented as depending on a parent Drush ansible role.
