### ISSUE TITLE
playbook drupal_public_filesystem_user hardcoded to Ubuntu's www-data user

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#793]
Running the playbook internal webserver-app role fails when deploying on CentOS during the [set permissions on the public files directory step](https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml#L49-L55). The [owner and group for that step are set to a drupal_public_filesystem_user variable](https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml#L54-L55) which is [currently set in inventory](https://github.com/Islandora-Devops/claw-playbook/blob/5049c3e9bd1c7625ce121aecd3dad38b17596089/inventory/vagrant/group_vars/webserver/drupal.yml#L49) to Ubuntu's Apache user "www-data".

Now, this step is the only one that uses this variable. The drupal_public_filesystem_user variable is only used for this step and I can't think of a reason why we shouldn't just use the webserver_app_user variable all the other steps use (which is also set to the Apache user, just like the drupal one). If we really wanted to keep the drupal_public_filesystem_user variable we could move this variable from group_vars into the role defaults and have it inherit the value of webserver_app_user. This would allow it to work for both Ubuntu and CentOS by default and still allow someone to set their own value group_vars if they really wanted to change it.

If no one objects, I'm willing to create the 4-line pull request.

**Comment by seth-shaw-unlv** [comment]
On a related note, why doesn't the playbook's repo have its own issues tab?

**Comment by whikloj** [comment]
I think none of the repos in Islandora-Devops are supposed to have issues tabs, we just forgot to turn them off. There was a decision made long ago to centralize the issues on the Islandora-CLAW/CLAW repo to keep them all in one place.

As for the actual issue, I am a 👍 to using the [`webserver_app_user`](https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/defaults/main.yml#L12) instead of the `drupal_public_filesystem_user`

**Comment by seth-shaw-unlv** [comment]
Probably not, since this was using the www-data user (as described in the initial post but not made clear by the issue title).
