### ISSUE TITLE
Use node properties other than content type to determine its metadata profile

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#799]
| Title (Goal)  | Use node properties/attributes other than content type to determine its metadata profile
--------------- |------------------------------------                           |
| Primary Actor | Repository admin |
| Scope         | Architecture       |
| Level         | High |
| Story         | As a repository admin, I want to be able to configure a default metadata profile for a node based not only on the node's content type but on a variety of conditions, e.g. collection membership, (creating) user permissions, or taxonomy terms added to the node. In the case of collection membership, I want all of the nodes in a collection to share the same set of metadata fields, regardless of whether they are images, videos, or PDFs. |

**Comment by mjordan** [comment]
Coming out of discussion at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/islandora-dev/jlv0afJjNIw/eEbS9Xc-BQAJ.

**Comment by dannylamb** [comment]
Hence `context` 😄

Having this functionality for display profiles would be awesome, too.
