### ISSUE TITLE
claw-playbook - drupal error

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#801]
claw-playbook gets deployed without error.  However, when I go to localhost:8000, the following error message gets thrown:

```
handle($request); $response->send(); $kernel->terminate($request, $response); 
```

```
commit 00fa2321fe8c2840ab3882d7f83e3d05ec3088f1
Author: Natkeeran <natkeeran@gmail.com>
Date:   Mon Feb 12 11:11:58 2018 -0500
```

**Comment by whikloj** [comment]
@Natkeeran I just tried that and I was ok.
```
> git log -n 1
commit 00fa2321fe8c2840ab3882d7f83e3d05ec3088f1 (HEAD -> master, origin/master, origin/HEAD)
Author: Natkeeran <natkeeran@gmail.com>
Date:   Mon Feb 12 11:11:58 2018 -0500

    Update README.md (#54)
    
    Update instructions about deploying to port 80
```

Once it came up.
```
> curl -I http://localhost:8000
HTTP/1.1 200 OK
Date: Wed, 14 Feb 2018 18:27:01 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Powered-By: PHP/7.0.25-0ubuntu0.16.04.1
Cache-Control: must-revalidate, no-cache, private
X-Drupal-Dynamic-Cache: UNCACHEABLE
X-UA-Compatible: IE=edge
Content-language: en
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Expires: Sun, 19 Nov 1978 05:00:00 GMT
X-Generator: Drupal 8 (https://www.drupal.org)
X-Drupal-Cache: HIT
Content-Type: text/html; charset=UTF-8
```

**Comment by MarcusBarnes** [comment]
I've been able to reproduce the behaviour @Natkeeran reported in https://github.com/Islandora-CLAW/CLAW/issues/801#issue-297177082.   We are investigating a few things to see if we can determine what may be going on.

**Comment by Natkeeran** [comment]
@whikloj @MarcusBarnes 

Installing this module `libapache2-mod-php7.0` seems to fix the issue.  [Reference](https://www.drupal.org/forum/support/post-installation/2016-12-21/localhost-is-down)

**Comment by mjordan** [comment]
@Natkeeran I hit this too and installing `libapache2-mod-php7.0` worked for me too (I chose to keep the locally modified php.ini).
