### ISSUE TITLE
Islandora-Devops/ansible-role-grok needs a new minor version

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#809]
Claw-playbook is pegged to grok 0.0.1 which doesn't include the most recent fixes for CentOS. This is a simple update to requirements.yml; _however_, the ansible-role-grok repo doesn't have a tag reflecting the changes either. 

So, someone with rights needs to tag current version as 0.0.2 and then we can update requirements.yml version number for grok.

**Comment by whikloj** [comment]
I have added a `0.0.2` tag to `ansible-role-grok`.

https://github.com/Islandora-Devops/ansible-role-grok/tree/0.0.2

**Comment by ajs6f** [comment]
I just had an install failure on CentoOS with
```
TASK [Islandora-Devops.grok : Install Grok dependencies] ***********************************************************************************
Monday 30 April 2018  13:09:53 -0400 (0:00:02.191)       0:33:52.619 **********
failed: [default] (item=[u'cmake', u'libpng16-dev', u'libtiff-dev', u'liblcms2-dev']) => {"changed": false, "cmd": "apt-get update", "item": ["cmake", "libpng16-dev", "libtiff-dev", "liblcms2-dev"], "msg": "[Errno 2] No such file or directory", "rc": 2}
```

Not sure if this is the same thing?

**Comment by seth-shaw-unlv** [comment]
@ajs6f I think so. The error you reported is from Ansible trying to use apt-get instead of yum. The 0.0.2 version fixes that.

**Comment by ajs6f** [comment]
Hm, in `roles/internal/Islandora-Devops.grok/tasks/install.yml` I found:
```
- name: Install Grok dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - cmake
    - libpng16-dev
    - libtiff-dev
    - liblcms2-dev
```
That can't work on CentOS, can it? Wouldn't that have to be a `yum` task? Or is that somehow fixed by https://github.com/Islandora-Devops/claw-playbook/pull/62? I edited it to a `yum` task locally and it got past that.

**Comment by ajs6f** [comment]
The other thing that seems to be problematic for me on CentOS is those package names-- they aren't quite the same. (`libpng-devel`, `libtiff-devel` and I can't find anything that resembles `liblcms2-dev`)

**Comment by seth-shaw-unlv** [comment]
@ajs6f Note that in the 0.0.2 branch the package installations use an [IF clause to call the appropriate package manager](https://github.com/Islandora-Devops/ansible-role-grok/blob/0.0.2/tasks/install.yml#L3-L23) (with the appropriate package names) based on whether Debian or CentOS is being used.

**Comment by seth-shaw-unlv** [comment]
@ajs6f  Yes, Islandora-Devops/claw-playbook#62 fixes it by updating the [ansible-role-grok to version 0.0.2](https://github.com/Islandora-Devops/ansible-role-grok/tree/0.0.2). That version [uses conditional statements](https://github.com/Islandora-Devops/ansible-role-grok/blob/0.0.2/tasks/install.yml#L3-L23) allowing the appropriate package manager to install the appropriate packages for the Os being used.

**Comment by ajs6f** [comment]
@seth-shaw-unlv Thank you for enlightening me! I was already starting to go down some weird rabbit hole (as you can see above). I will back my fluffy tail out of there and go get that PR.

**Comment by ajs6f** [comment]
Okay, after much fuss and bother (see comments I left on  Islandora-Devops/claw-playbook#62) I have found that Grok _can_ be installed on CentOS, but not effectively with the stock dev tools. Grok uses C++14, and while the stock tools can deal with 14, they use nonstandard flags to do it, so the best way is
```
sudo yum install cmake3 devtoolset-7-gcc-c+
scl enable devtoolset-7 bash
```
which will switch over to `gcc` and friends 7.3.1, which handles Grok well. Note the appearance of `cmake3`, which (for CentOS) is a separate package from `cmake` (which goes only through the 2-series).

I guess I can try a PR against @whikloj's PR? The dependencies are straightforward, but I'm not totally sure how best to execute `scl` invocations, especially because `scl` doesn't persist its changes-- they are effective only in the scope of the single command you pass to it (a bit like `sudo`). Perhaps change the `make grok` task?

**Comment by seth-shaw-unlv** [comment]
@ajs6f I has [a working grok install on CentOS7](https://github.com/seth-shaw-unlv/ansible-role-grok/tree/centos) about 4 months ago. I hadn't submitted the PR for it yet because other CentOS related PRs were still pending.

**Comment by seth-shaw-unlv** [comment]
@ajs6f No, I confirmed it was working with the default CentOS box vagrant provided. Perhaps a different role made the difference? Oh, well. At least you got it working!

**Comment by ajs6f** [comment]
Hmmm... I'm starting to think that the whole morass I climbed into and out of wasn't about CentOS itself as much as whatever weird baseline image we (SI) is using for our VMs. Sigh.

**Comment by seth-shaw-unlv** [comment]
We can resolve this after the new version number is included in claw-playbook. The new version of ansible-role-crayfish, which should arrive shortly, could be included in the same PR.

**Comment by seth-shaw-unlv** [comment]
Resolved back in June by Islandora-Devops/claw-playbook/pull/68
