### ISSUE TITLE
Viewers in CLAW

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#811]
There may have already been some discussion of how we should implement the equivalent of 7.x's solution pack viewers. D8 seems to have a lot of flexibility (well, at least that's the impression I get) around how to render content. Display Suite may be relevant, but the Media Entity module, which we're already using, does too, with "display modes". There are probably other existing frameworks we could look at.

My specific question is has there been any discussion about how we can provide flexibility in how specific Islandora content types (so far, Islandora Image and Islandora Collection) and associated binary media entities (so far, web content, TIFF, and JP2 media) can be presented to users in a modular way? A simple example is the ability to configure and use different video players. For video, it makes sense to use at least as a default whatever the rest of the D8 community is using, but what if that video is also an oral history? Another example is how we will render complex objects like books and newspapers to users.

I'd also like to suggest that we consider Context and its potential to allow site admins to configure how content can be presented to users based on specific, configurable conditions. A real use case that we have at SFU is to have all objects in one collection use a specific 7.x viewer while objects of the same content model in another collection use another viewer. There is a [JIRA ticket](https://jira.duraspace.org/browse/ISLANDORA-1554) for this sort of thing in 7.x already.

If having a use case framing this set of questions would be helpful I'd be happy to create one.

**Comment by mjordan** [comment]
Also like to add that this question might be relevant to porting over 7.x metadata display profiles. At one level D8 already allows configuration of node field-level output, but if we look at how often metadata display profile are configured and customized in 7.x, we may want to implement them in CLAW from the perspective of how a profile is an aggregation of specific fields. Again, Context might be useful here, The killer reaction for 7.x Context, at least for us, is the ability to have all objects in one collection, regardless of content model, use the same Islandora Solr metadata display profile.

**Comment by whikloj** [comment]
Drupal 8 uses [Field Formatters](https://api.drupal.org/api/drupal/core!modules!field!field.api.php/group/field_formatter/8.2.x) which allows you to specify (I think) on a per-field basis which formatter you use. I would suggest that any viewers we create use this setup and then (as you mention) could be altered via Context. 

Display Suite appears (to my reading) as an easy way to configure the entire node view. I think this is neat, but I also think it could be an option that users can choose. One of probably many (from simple templating, Views, etc)

https://www.drupal.org/docs/8/creating-custom-modules/create-a-custom-field-formatter

https://github.com/Islandora-CLAW/openseadragon

**Comment by mjordan** [comment]
Sweet, thanks, I'll take a look.

**Comment by mjordan** [comment]
Note from March 7, 2018 CLAW call: display modes are configurations defining sets of field formatters.

**Comment by Natkeeran** [comment]
Recent [content modeling overhaul](https://github.com/Islandora-CLAW/islandora/pull/86), supporting new viewers has been greatly simplified.  In most cases, you don't need to do any coding.  Additional notes here: https://github.com/Natkeeran/Notes/blob/master/configure-new-viewer-in-claw.md

**Comment by dannylamb** [comment]
@mjordan If we took @Natkeeran's notes and put them into our documentation, could we consider this issue/question resolved?

**Comment by mjordan** [comment]
Yes, I believe so. Feel free to close.
