### ISSUE TITLE
Remove force setting config, update README

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#813]
Now that https://github.com/Islandora-Devops/claw-playbook/pull/57 has landed, we should update our documentation accordingly.

Also, we can axe [this](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora.module#L42-L63), which was a bad attempt at forcing configuration when the module was enabled.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/islandora/commit/ff66f6391549df151198293ee08178e2629f087b
