### ISSUE TITLE
Explore modeling controlled vocabularies as taxonomy terms

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#817]
From the March 14th CLAW Call:

Using the taxonomy module to tag content with terms from controlled vocabularies could be used to alleviate the administrivia involved with managing a large number of content types with their associated fields.   This would break the restriction of one rdf mapping per content type, as well most other site functionality.  This means we'd be using terms to dictate functionality, for which there are plenty of third party modules available.

It seems like a slam dunk, but there are some considerations we'll have to hammer out first.  Most notably that terms are generally considered local, though we'd want them to reference the uris present in the controlled vocabulary we're using.  We'd also have to figure out how we can enrich our RDF with enough information derived from the terms so that information gets persisted in Fedora.  Most likely this means we'd be adding one or more `rdf:type`s to our jsonld based on what taxonomy terms a node is tagged with.

FYI, we'll probably get a lot of mileage out of this: https://www.drupal.org/project/term_condition Aren't plugins beautiful?

**Comment by mjordan** [comment]
@dannylamb isn't Context beautiful... well, at least super useful.

**Comment by seth-shaw-unlv** [comment]
Trying to wrap my head around this, so I may be way off base, but let me see if I'm reading this right...

Currently we have a content model that stores descriptive metadata as part of the node with media entity references for each of the file representations (tiff, th, web_content, etc.). This is serialized into json-ld with the help of RDF Mappings and serves as the basis for what Fedora 4 receives and stores.

With context: would have a suite of fields available, not necessarily associated with any particular content type/bundle, but with a taxonomy term context that would trigger their availability for a given node?

For example, I have this node with the taxonomy terms "image" and "dublin core" applied to it, so _magically_ that node would then have the fields corresponding to each taxonomy term? (E.g. a tiff media entity reference for the image term and dc:date and dc:extent for the dublin core term.)

Is that a correct characterization or am I misunderstanding how context would be used?

**Comment by seth-shaw-unlv** [comment]
Or is it more something like this: we have a generic islandora object with a media entity reference and a descriptive metadata reference. A node stores references to the relevant media entities and descriptive metadata entities (each media type or metadata profile would be their own content type). The Context module would control which types of media or metadata profile entities displayed in the UI and would also control whether the JSON-LD imported the linked entity fields into the JSON-LD (for metadata profiles) or used a reference (for media entities).

Diagrams to illustrate how I am thinking about these...

_How we do it now_: 
![current_model](https://user-images.githubusercontent.com/29869988/37734972-f7f0a204-2d09-11e8-841b-80f8cc8ff84f.png)

_How we would do it with Context_:
 ![mp_ent_model](https://user-images.githubusercontent.com/29869988/37734818-87f5d2da-2d09-11e8-9d42-68f60069bfa7.png)

**Comment by dannylamb** [comment]
I'm looking at the [migrate_plus](https://www.drupal.org/project/migrate_plus) module now from https://github.com/Islandora-CLAW/CLAW/issues/819, and it contains example migrations that pull in taxonomy terms!  Having a framework / template for importing controlled vocabularies would be super sweet.

**Comment by dannylamb** [comment]
Ah, shoulda reloaded my page!  @seth-shaw-unlv So the diagram you've drawn up pretty much nails it.  We'd have to use context to expose an alter for merging the metadata nodes into the main node's jsonld.  We've actually already [done this once to add the Drupal URI to serialized jsonld](https://github.com/Islandora-CLAW/islandora/blob/21124f317d14099753104c0e80540bcb8ecf2b17/src/Plugin/ContextReaction/MappingUriPredicateReaction.php), and could probably just build on it for more jsonld alterations like this.

As for your first post, the tagging of nodes with taxonomy terms can be used to drive pretty much anything.  So things like what what derivatives get triggered, what gets indexed into fedora, etc... can all be configured to based on taxonomy terms instead of content models.  And by that I mean you could probably do it right now all through the UI using https://www.drupal.org/project/term_condition.

Looking forward, we could have that final separation of structural metadata, descriptive metadata, and behaviour I've hinted at a few times during calls.  We would be able to do things like use a _single_ module with entities/fields for structure(PCDM, ORE, EDM, etc..), a _single_ module for descriptive metadata entities/fields (e.g. a `dcterms` module with author and location entities), and a single module for driving behaviour using taxonomy terms (`islandora_collection`, `islandora_image`, etc...).

**Comment by mjordan** [comment]
Just want to make sure we don't loose the link (no pun intended) between this use case and #815. Transmission ended.

**Comment by DiegoPino** [comment]
This is exactly what i was trying to say here https://github.com/Islandora-CLAW/CLAW/issues/815#issuecomment-372728456

Also, in the original JSON-LD module implementation we had the ability to expand referenced entities (any) and make a deep  `@graph` instead. We can reuse the same idea to complement what is missing with the default, flat json-ld?  Or even better, let camel sync machinery deal with the full, deeper, graph when syncing to fedora?

**Comment by dannylamb** [comment]
FYI, yes... we can do this with `migrate_plus`.  We need to write a custom source plugin to download the list of terms from somewhere and parse them... but that's about it.  Chances are rdf+xml will be available and we can parse it using xpath.
