### ISSUE TITLE
Not acceptable format: jsonld

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#820]
I am seeing the following exception get thrown intermittently, specially when claw gets initially deployed. 

```
commit f77f0a97c1f0b23cf79980486e671d76c2b147fc
Author: Jared Whiklo <jwhiklo@gmail.com>
Date:   Wed Mar 14 08:08:53 2018 -0500
Use our drupal-project to pin drupal version (#61)
```

JsonLD and even Json does not return a valid response for a given node.  

```
Message | Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: Not acceptable format: jsonld in Drupal\Core\EventSubscriber\RenderArrayNonHtmlSubscriber->onRespond() (line 30 of /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/RenderArrayNonHtmlSubscriber.php).
```

**Comment by DiegoPino** [comment]
Probably serializers are not enabled yet when this happens?

**Comment by akuckartz** [comment]
:+1: (please support JSON-LD)

**Comment by whikloj** [comment]
I just hit this and then I went into the REST configuration for the Node type. Changed nothing and pressed Save. Fixed.

So I think the new granular permissions are not being picked up correctly by Drupal.

**Comment by dannylamb** [comment]
dangit....

**Comment by ajs6f** [comment]
@whikloj's ["One Simple Trick To Fix `Not acceptable format` Problems"](https://github.com/Islandora-CLAW/CLAW/issues/820#issuecomment-378707072) worked for me too.

**Comment by DiegoPino** [comment]
@ajs6f where is that trick? Can't make that link work here. had never that issue but would be good to know

**Comment by ajs6f** [comment]
It's just what @whikloj reported above in this issue; a save without modification. In IRC @dannylamb mentioned that his giant content modelling PR will also fix it.

**Comment by Natkeeran** [comment]
"giant content modelling PR " is in and I don't see this any longer.
