### ISSUE TITLE
Alter Display and Form Modes with Context

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#821]
By allowing ourselves to alter form and display modes with Context, we can do snazzy things like swap forms based on user permissions, or displays based on taxonomy terms.

This would be a step towards "one bundle to rule them all" with taxonomy term determining behaviour.

**Comment by dannylamb** [comment]
PR forthcoming...

**Comment by mjordan** [comment]
I would happily test this.
