### ISSUE TITLE
Implement access control on nodes and media using taxonomies

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#826]
| Title (Goal)  | Implement access control on nodes and media using taxonomies
--------------- |------------------------------------                           |
| Primary Actor | Repository admin |
| Scope         | Specific service |
| Level         | High |
| Story         | As a repository admin, I want to restrict access to Islandora content using taxonomies. For example, nodes and media tagged with "foo" can only be viewed by users with the role "fooviewers" and only managed by users with the role "foomanagers."

**Comment by mjordan** [comment]
This use case applies more to Drupal than to Islandora. Related issue: #823. https://www.drupal.org/project/permissions_by_term appears to provide this functionality but we need to confirm that it does with some hands-on tests.

**Comment by rosiel** [comment]
I think this would fix https://github.com/Islandora-CLAW/CLAW/issues/412 - if media (files) can be restricted independently of their metadata - especially if the file (payload) can be restricted independently of the file-specific metadata (file size, file type, other FITS-like characteristics that may be on the "media" object not the node representing the conceptual object).

**Comment by dannylamb** [comment]
We can (and are) doing this with `islandora_demo`, though there is nothing tied to it and you are free to use organic groups or whatever else you want :D
