### ISSUE TITLE
No RPM setup for ImageMagick in Crayfish

### ISSUE THREAD

**Issue by ajs6f** [Islandora-CLAW/CLAW#831]
Trying to install from `claw-playbook` on CentOS7, I ran into
```
TASK [Islandora-Devops.crayfish : Install requisite package repositories] ******************************************************************
Tuesday 22 May 2018  10:22:35 -0400 (0:00:00.044)       0:22:23.769 ***********
fatal: [default]: FAILED! => {"changed": false, "module_stderr": "Shared connection to [SI hostname] closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_JZD1B4/ansible_module_apt_repository.py\", line 551, in <module>\r\n    main()\r\n  File \"/tmp/ansible_JZD1B4/ansible_module_apt_repository.py\", line 510, in main\r\n    if isinstance(distro, aptsources_distro.Distribution):\r\nNameError: global name 'aptsources_distro' is not defined\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

which, IIUC, is coming from the fact that that task in `oles/internal/Islandora-Devops.crayfish/tasks/install.yml` has only a setup for `apt`-based and not RPM-based systems. I'm wondering whether the specific package of ImageMagick called out there important or can I use the stock packages for my system?

**Comment by seth-shaw-unlv** [comment]
[My fork's centos branch](https://github.com/seth-shaw-unlv/ansible-role-crayfish/tree/centos) uses the [ansible "package" module](https://github.com/seth-shaw-unlv/ansible-role-crayfish/blob/centos/tasks/install.yml#L8-L12) (as opposed to either yum or apt specifically) to install the provided [ImageMagick](https://github.com/seth-shaw-unlv/ansible-role-crayfish/blob/centos/vars/RedHat.yml#L6) package. 

I don't remember why I haven't created a PR on this yet. Perhaps it needed some cleanup? If that branch works for you I will go ahead and issue the PR.

**Comment by ajs6f** [comment]
@seth-shaw-unlv Awesome! I will test that branch and report back here (might not be until tomorrow).

**Comment by seth-shaw-unlv** [comment]
Oh, wait, [there is a PR already](https://github.com/Islandora-Devops/ansible-role-crayfish/pull/3). It looks like it got side-tracked by other discussions. I'll see if we can push this through now.

**Comment by ajs6f** [comment]
Urg, #828 was my fault, sorry! @seth-shaw-unlv just keeps solving my problems as fast as I can find them!

**Comment by seth-shaw-unlv** [comment]
No, it isn't you @ajs6f; we've just procrastinated actually fixing this piece.

**Comment by dannylamb** [comment]
@ajs6f @seth-shaw-unlv is there anything you need to move https://github.com/Islandora-Devops/ansible-role-crayfish/pull/3 along?  if it's been tested and works, i'm inclined to just pull it in.

**Comment by ajs6f** [comment]
I tried it and it worked for me on CentOS7.

**Comment by seth-shaw-unlv** [comment]
@dannylamb Islandora-Devops/ansible-role-crayfish#3 itself works fine, once you get past the Gemini error. We just hadn't had many testers because of that hurdle. 

@DigitLib made some suggestions for improvement (regarding [tesseract](https://github.com/Islandora-Devops/ansible-role-crayfish/pull/3#issuecomment-379424639) and [httpd.cnf](https://github.com/Islandora-Devops/ansible-role-crayfish/pull/3#issuecomment-379932665)) but they haven't been incorporated into the PR. We could just merge it as is and make a new issue based on @DigitLib's suggestions.

**Comment by dannylamb** [comment]
@seth-shaw-unlv I'll pull the trigger if there's no objections from @DigitLib

**Comment by DigitLib** [comment]
@dannylamb @seth-shaw-unlv  we can also define an additional languages to install with tesseract by default (French, Italian, Serbian....) adding it in  /vars/RedHat.yml
tesseract-langpack-fra
tesseract-langpack-ita
tesseract-langpack-srp
...?

**Comment by seth-shaw-unlv** [comment]
@DigitLib, that is fine by me. Let's just do it as a separate ticket and PR, if that is okay.

**Comment by DigitLib** [comment]
@seth-shaw-unlv Okay great. And to make a little add in README how to install additional language in CentOS (sudo yum install tesseract-langpack-ger for example)

**Comment by DigitLib** [comment]
@seth-shaw-unlv tested langpack addition in /var/RedHat.yml it works! installed!

**Comment by seth-shaw-unlv** [comment]
Resolved by Islandora-Devops/ansible-role-crayfish/pull/3
