### ISSUE TITLE
claw-playbook: Tesseract for crayfish in CentOS

### ISSUE THREAD

**Issue by DigitLib** [Islandora-CLAW/CLAW#834]
Installing a tesseract in CentOS as crayfish package and add an additional laguage-packages. We can decide what languages it can be installed by default.
For example:
French, Italian, German, Spanish and Serbian?
And to add in README a small description how to install an extra language with yum?

**Comment by DigitLib** [comment]
@dannylamb @seth-shaw-unlv created PR https://github.com/Islandora-Devops/ansible-role-crayfish/pull/7 for tesseract install.

**Comment by jonathangreen** [comment]
Merged!
