### ISSUE TITLE
claw-playbook: Crayfish httpd config location is specific to Debian 

### ISSUE THREAD

**Issue by ajs6f** [Islandora-CLAW/CLAW#835]
Currently, `claw-playbook` is leaving HTTPd conf files for Crayfish in `/etc/httpd/conf-enabled`. That's a Debian idiom-- CentOS, for example, doesn't know anything about `conf-enabled` and so Crayfish services will not be on line after `claw-playbook`. The right place for enabled services on CentOS is `/etc/httpd/conf.d`. I will try to make a PR for this, but it's going to be slow because I don't yet have a working CLAW install.

**Comment by DigitLib** [comment]
@ajs6f I put PR https://github.com/Islandora-Devops/ansible-role-crayfish/issues/5 for solving this... Can you test it?

**Comment by ajs6f** [comment]
I sure will, but probably not until tomorrow. Also, do you need this tested over a fresh install? Because I can't really do that right now.

**Comment by seth-shaw-unlv** [comment]
I will test it in a few minutes. (Already running another test.)

**Comment by DigitLib** [comment]
@seth-shaw-unlv GREAT!!!

**Comment by seth-shaw-unlv** [comment]
Resolved by Islandora-Devops/ansible-role-crayfish/pull/8
