### ISSUE TITLE
Trying to use CLAW via claw-playbook

### ISSUE THREAD

**Issue by sulfurchesh** [Islandora-CLAW/CLAW#837]
We're trying to install CLAW via the claw-playbook and running into some issues in getting the "ubuntu/xenial64" file.

claw-playbook doesn't have an issues section, so Natkeeran suggested I post this here.

When I tried to run the box update I received the following error:

$ vagrant box update
==> default: Box 'ubuntu/xenial64' not installed, can't check for updates.

And then when I try to add that specific box, I get this:

$ vagrant box add ubuntu/xenial64
The box 'ubuntu/xenial64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/xenial64"]
Error: The requested URL returned error: 404 Not Found

When I visit https://atlas.hashicorp.com/ubuntu/xenial64, I get a 404 error and a note a the top that reads:

The Packer, Artifact Registry and Terraform Enterprise (Legacy) features of Atlas will no longer be actively developed or maintained and will be fully decommissioned on Thursday, May 31, 2018

**Comment by sulfurchesh** [comment]
Thanks -- we were running Vagrant 1.9, and I've upgraded to 2.0.3 now, and that seems to have found the package.

Might be worth updating the documentation to note that a newer version of vagrant is required due to this changeover.

**Comment by whikloj** [comment]
Good point I will do that right now. Can we close this ticket now?

**Comment by sulfurchesh** [comment]
Definitely. Thanks for the assistance!
