### ISSUE TITLE
claw-playbook: geerlingguy roles updated - list

### ISSUE THREAD

**Issue by DigitLib** [Islandora-CLAW/CLAW#842]
**php**
 3.6.0
-    - libpng12-dev
+    - libpng-dev

Added bionic ubuntu

3.5.2 -> Fix deprecation warnings in Ansible 2.5 for state 'present'.

3.5.1 - Set the correct opcache priority on Debian

**apache**
2.1.2
Fix deprecation warnings in Ansible 2.5 for state 'present'.

3.0.0
use include_tasks instead of include + static

**solr**
 
4.2.0 -> fix pre5 systemd

4.1.0 -> Use include_tasks in more places.

4.0.2 -> Fix deprecation warnings in Ansible 2.5 for state 'present'

4.0.1 -> Daemonize can fail on Ubuntu in some Java installation scenarios.

4.0.0 -> 
-solr_version: "6.6.1"
+solr_version: "7.1.0"

**git**

2.0.2 -> Fix deprecation warnings in Ansible 2.5 for state 'present'

2.0.1 -> Fix source build for Ubuntu 18.05 'Bionic'.

2.0.0 -> Bump minimum Ansible version to 2.4 and update use of include.

1.4.1 -> Fix source build install failure on Ubuntu 16.04.

**mysql**

2.9.0 -> Fix Ansible 2.4+ deprecation warnings for include and static.

2.8.3 -> Fix deprecation warnings in Ansible 2.5 for state 'present'.

2.8.2 -> Use adm group for log files on Debian/Ubuntu.

**postgresql**

1.4.3 -> Add support for Ubuntu 18.04

1.4.2 -> Add docs.

1.4.1 -> include-deprecated-fix

1.4.0 -> include-deprecated-fix

**java**

1.8.1 -> Support Ubuntu 18.04 Bionic.

1.8.0 -> remove deprecation warnings

1.7.7 -> Fix deprecation warnings in Ansible 2.5 for state 'present'.

1.7.6 -> Fix Galaxy meta/main.yml to parse Debian versions correctly.

1.7.5 -> Update variable inclusion method to work correctly.

**drupal**

2.5.0 -> Use localhost for Travis CI tests.

**drush**

3.1.1 -> Update default Drush Launcher version to 0.6.0.

3.1.0 -> Fix Ansible 2.4+ deprecation warnings for include.

3.0.0 -> Merge branch 'drush-newage'
https://github.com/geerlingguy/ansible-role-drush/commit/f24edc8def31a33c7cb0177ed57d5797b3c68974

2.0.2 -> Merge branch 'oxyc-issue-debian'
https://github.com/geerlingguy/ansible-role-drush/commit/ed425b979fdc583aba252149c7f6e4e5688ab31f

**drupal-console**

1.1.1 -> Add python-openssl for SNI support

**Comment by dannylamb** [comment]
resolved via https://github.com/Islandora-Devops/claw-playbook/commit/1b59bb390bb100f185ff2b5c8a3ed22c65c71438
