### ISSUE TITLE
Enable islandora-connector-houdini

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#845]
Not being enabled in claw-playbook

**Comment by dannylamb** [comment]
Should be part of Islandora-Devops/claw-playbook#66

**Comment by jonathangreen** [comment]
https://github.com/Islandora-Devops/ansible-role-alpaca/pull/1

**Comment by jonathangreen** [comment]
I believe it needs to be enabled in that PR as well

**Comment by jonathangreen** [comment]
resolved with: 
https://github.com/Islandora-Devops/ansible-role-alpaca/pull/1
