### ISSUE TITLE
Trying to generate service files without a preservation master tagged media causes WSOD

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#846]
At iCampEU we had a member add a media but not tag with `Preservation Master`, when then trying to use the `Action` to generate the service file it causes Drupal to display a White Screen of Death.

We should handle that more nicely.

**Comment by dannylamb** [comment]
Nice catch

**Comment by jonathangreen** [comment]
Live demos always bring out the bugs!

**Comment by manez** [comment]
Same thing happens when you try to generate a thumbnail and there's no service file.

**Comment by dannylamb** [comment]
Two PRs are up that fix this (and potentially a few more undiscovered gems).  Added a slew of null checks with some better exception handling.
