### ISSUE TITLE
Unable to modify "Content | All repository content" context

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#853]
I was looking to add another node type to index into Fedora and Triplestore.  When checked another content type and clicked saved, the changes could not be saved.  It seems that context could not be altered.  

Creating a new context with condition of node type Basic Page and indexing to Fedora and Triplestore does work.

**Comment by seth-shaw-unlv** [comment]
Odd, it worked in my test before the PR went in. I will try to test this today or tomorrow.

**Comment by dannylamb** [comment]
I just tested this out and there's a weird artifact in there.  The "NodeHasTerm" condition is present, but not filled.  It's totally not needed and shouldn't be there.

I've confirmed that its term field is required and is actually  blocking form submission.  Remove the condition and its fine.  Deleting that from the feature should be pretty straightforward, too.

**Comment by dannylamb** [comment]
@Natkeeran @seth-shaw-unlv PR is up ^^
