### ISSUE TITLE
Documentation: How to Configure Object Display

### ISSUE THREAD

**Issue by manez** [Islandora-CLAW/CLAW#86]
Basic user documentation with screenshots. Although, since this is all done through Content Types -> Manage Displays now, we may want to just lean on the regular Drupal documentation (which would make this task actually "see if/where our process differs from standard Drupal and document that").

**Comment by kumarSC** [comment]
Hi @manez ,  I am a mobile developer and a starter on open source projects. I want to contribute to open source starting with small things as I learn.I found this issue on github with tag documentation.Could you please suggest how I can get started on this issue?
