### ISSUE TITLE
Core block placement is busted

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#863]
Using the Context UI to place blocks works fine, but the stock block placement UI is buggy because of how CLAW's Condition plugins are written.

The easiest thing to do would be to re-write their `evaluate` functions to include this pattern at the top of the function, which lets the block placement UI ignore them:
```php
// Taken from the core NodeType condition
if (empty($this->configuration['bundles']) && !$this->isNegated()) {
  return TRUE;
}
```

A more sophisticated solution is possible, but that will involve some wizardry with Drupal's plugin annotations.

**Comment by manez** [comment]
I'm adding a +1 to any issue that I stumble on as I'm building a CLAW 101 curriculum, because I figure those are the ones that a beginning front-end user is going to find as well, and it should get noted somehow.

+1

**Comment by ajs6f** [comment]
No argument to marking things, @manez, but maybe a tag would be good for this? I ask because maybe you'd like to know if all the "blocks CLAW 101" issues are done or which ones are left, and a tag would let you search quickly.

**Comment by manez** [comment]
I like that idea. I intend to encourage testing/issue creation with the folks attending the iCamp Admin track, so it could also function as a tag they can throw on any issue they create. 

@dannylamb would that be useful, or would it be noise? I don't need to track if they get fixed, I'm just trying to flag issues that a front end user is going to notice, versus the ones that happen entirely in the back end (and are therefore strange magic).

**Comment by dannylamb** [comment]
@manez sounds good to me

**Comment by dannylamb** [comment]
This was resolved via https://github.com/Islandora-CLAW/islandora/commit/cb8bb07238d1822370aca73e7011fdea9235c501
