### ISSUE TITLE
Camel/Houdini not using changes to Karaf config

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#865]
[Initially reported on the islandora-dev list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/islandora-dev/VPC-xiCpo5A/1ItJPu2jBgAJ): 

Updates to the Karaf config are not being used by the Houdini connector.

E.g. the default value for houdini.convert.url in "ca.islandora.alpaca.connector.houdini.cfg" is "http://localhost:8000/houdini/convert". Changing that value to another URL will be reflected in the Karaf config (as seen by "karaf@root()> config:list "(service.pid=ca.islandora.alpaca.connector.houdini)". However, when triggering derivative generation the camel log shows that Camel is still using the default URL instead of the new one.

**Comment by acoburn** [comment]
i.e. this line: https://github.com/Islandora-CLAW/Alpaca/blob/master/islandora-connector-houdini/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L11

should be changed to include `persistent-id="ca.islandora.alpaca.connector.houdini"`
