### ISSUE TITLE
Make all fields available to Views

### ISSUE THREAD

**Issue by manez** [Islandora-CLAW/CLAW#871]
| Title (Goal)  | Make all fields available to build Views
--------------- |------------------------------------                           |
| Primary Actor | End user|
| Scope         | Drupal Views|
| Level         | Low |
| Story         | I'm a front-end user who knows may way around Views and wants to build a bunch of flashy custom Views with my Islandora objects. I need to be able to access all of the fields on those objects (especially the display) as fields in Views so I can drop them in with the Views UI. This should include metadata fields when we have more.

**Comment by dannylamb** [comment]
We've got this one in the bag.  As long as we use nodes, fields for all our content types should be available to views.  If we ever end up making our own content types again, we'll have to add some code in a hook to make all the fields available.

![screenshot from 2018-08-15 11-23-47](https://user-images.githubusercontent.com/20773151/44153584-0250d7c6-a07f-11e8-897d-4187991740eb.png)
