### ISSUE TITLE
Custom Views not showing results for "field_member_of" filter

### ISSUE THREAD

**Issue by manez** [Islandora-CLAW/CLAW#872]
Built a collection "Lobsters," made some things members of it, made a view with the Select Filter Criteria "Content: Member of (= Lobsters)," not getting any results in my View. It's entirely possible that I'm missing something, but it seems like this isn't working like it should.

**Comment by dannylamb** [comment]
Are you setting the regular filter instead of marking it as a "contextual filter"?

We have a membership block already that's built with views if you want an example.  You can check it out at http://localhost:8000/admin/structure/views/view/members?destination=/admin/structure/views

**Comment by manez** [comment]
Setting a regular filter. I'm trying to set it up as though I'm building a collection view, so I don't think contextual will work. It would need to stand alone.
