### ISSUE TITLE
Clicking on member thumbnail opens thumbnail instead of the service file or member

### ISSUE THREAD

**Issue by estregger** [Islandora-CLAW/CLAW#875]
If I'm looking at the members in a collection, and click on the thumbnail, it opens the thumbnail. I'd expect this to either take me to a service file or the object.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/43b971cdf627403d7e3436c79161c06ef8eb26e9

Took me a while, but I got it @estregger!
