### ISSUE TITLE
Will CLAW data model support Work -> Instance abstraction by default?

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#876]
Currently, Islandora CLAW models a digital object as a Resource Item optionally consisting of Media.  

[BIBFRAME](https://www.loc.gov/bibframe/docs/bibframe2-model.html) models a bibliographic object into three related abstractions: Work -> Instance -> Item.  

The principle of separating a Work and Instance (BIBFRAME) or Work/Expression and Manifestation (RDA) seems to be quite established in emerging library cataloguing standards.  [BIBFRAME editor ](http://bibframe.org/bibliomata/bfe/development.html) shows different metadata properties or elements based on whether the user is describing a Work or an Instance.  

Supporting Work -> Instance will add complexity to modelling, medata profiles as well indexing and display.  Will CLAW data model support Work -> Instance abstraction by default?

**Comment by ajs6f** [comment]
As someone from an institution for which only a few use cases involve bibliographical material at all and for which almost no resources will offer a FRBR-style set of distinctions, a huge -1 to this being _by default_. No objection to it being possible, of course-- just not the default.

**Comment by dannylamb** [comment]
Adding the migration tag to this so it can be discussed during the sprint.  While there's nothing that will force anyone to use a work -> instance model in core code, I think there's been enough discussion of "Where do we hang the nail" as far as what constitutes a full object that we should at least discuss this further.

In the end, this will be something that some people do and some people don't, so the main thing to keep in mind is that we don't alienate either camp.  _You do you_, this is just what'll be in our "default metadata profile".

**Comment by rtilla1** [comment]
Sprint Kick-off: A lot of the work we're doing is setting us up to do this later, but this doesn't need to be out-of-the-box because most of our things being migrated aren't modeled that way. This is a future goal, but out-of-scope for now.
