### ISSUE TITLE
Add `file_browser` module

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#877]
Update https://github.com/Islandora-Devops/claw-playbook to install the `file_browser` module: https://www.drupal.org/project/file_browser.

Export all relevant form config in `islandora_demo_feature` to update our media types to use the file browser widget for its file fields.

**Comment by Natkeeran** [comment]
@dannylamb 

With 8.6, there is a media browser.  Do we still need file browser?

**Comment by dannylamb** [comment]
@Natkeeran There's basically one 'browser' per type of content entity in a reference field.  Media browser for media reference fields, file browser for file reference fields, and content browser for node reference fields.  We actually don't have any media reference fields in core right now because we do everything with views, so we won't get much out of the new Media Library after all :(

https://www.drupal.org/project/file_browser would make selecting an existing file to associate with a Media easier if you're going through the forms, but that's it.  FWIW we'll probably get the most bang for our buck with https://www.drupal.org/project/content_browser in https://github.com/Islandora-CLAW/CLAW/issues/878 since we have more node reference fields than anything else.
