### ISSUE TITLE
Support additional RDF types based on a configurable field

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#889]
For a given bundle, I would like to define a field that stores one (or more) types that will be included as a typeof property in the RDFa and a @type in the JSON-LD serialization.

For example, in my [controlled access terms module](https://github.com/seth-shaw-unlv/controlled_access_terms) I define a Corporate Body bundle with the [rdf.mapping config set to use schema:Organization as the type](https://github.com/seth-shaw-unlv/controlled_access_terms/blob/master/config/install/rdf.mapping.node.corporate_body.yml#L11-L12). I would like to add a List field of sub-types (e.g. Organizational Unit, Corporation, and Performing Group) that would be included as additional types.

I tried simply listing the field as a fieldMapping using the type property, but that didn't work as setting the type fields is a separate step from mapping the properties (and the resulting output made all my schema testers throw errors). 

Adding it to the RDFa requires implementing a hook_preprocess_node(). I have [an example gist](https://gist.github.com/seth-shaw-unlv/04eccb0c8594e3c8435544e5fa4d7907) that worked in my testing; although it would need to be made configurale. This fix only works for the HTML serialization. JSON-LD [populates the `@type` field based on the rdf.mapping](https://github.com/Islandora-CLAW/jsonld/blob/8.x-1.x/src/ContextGenerator/JsonldContextGenerator.php#L200) (which is what we would expect) and would need to be extended in some other way.

**Comment by dannylamb** [comment]
We should do this in the islandora module, in an alter with a `ContextReaction`, and let the user configure which taxonomy term fields apply to rdf:type vs. whatever predicate is in the RDF mapping.

**Comment by dannylamb** [comment]
Adding to sprint.  We'll want this for the agents we create from `mods:name` elements.

**Comment by rtilla1** [comment]
From Spring Kick-off: Resolving this ticket will solve 2 types of problems:
1. Creation of compound fields (names can be given both an entity and a relationship marker)
2. Define a list of types that could be included as a property (to be used as a dropdown)

**Comment by seth-shaw-unlv** [comment]
Related ticket: #893

**Comment by dannylamb** [comment]
So it looks like there's two pieces to this.  One is to make a 'compound' field that has the entity reference field plus a role.  The other piece is to provide an implementation in the islandora module's jsonld alter to re-write the rdf accordingly.  Does that sound about right?  Do we want to split this into sub-tickets?

**Comment by seth-shaw-unlv** [comment]
@dannylamb Yes. This ticket would have a simple list field that allows selecting a type. Then the islandora jsonld alter would re-write the RDF accordingly (type's *value*).

The compound field case is slightly different in that the drop-down subfield modifies the *predicate* associated with the compound field's value.

**Comment by seth-shaw-unlv** [comment]
*Thinking out loud*, @dannylamb can you check my reasoning on this:

So, considering how [islandora_jsonld_alter_normalized_array](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora.module#L241-L249) is currently setup, we need to add a \Drupal\islandora\ContextReaction\NormalizerAlterReaction that will alter the type attribute based on the value of a field (to be configured) for the passed entity. The condition would be, what, that the entity is of a predetermined content type (configurable in the Context admin)? Am I on the right track? The type predicate is in the normalized array, right?

If the above is correct, we could also have a another NormalizerAlterReaction for altering TypedRelation fields.

**Comment by dannylamb** [comment]
@seth-shaw-unlv I think the Condition will be left to the user, but probably something along the lines of picking a content type.  We could flesh out something akin to a "has field" condition if we needed one, but we can probably make due with what we've already got for now.

I imagine the context reaction would just give you a list of taxonomy term reference fields to choose from, and the user would be allowed to select multiple.  Then when actually exectuing, the external uris from terms in those fields would be appended to rdf:type.  We'll probably also want to remove whatever predicate it was configured as in the rdf mapping from the jsonld body (if it was configured in the first place).

**Comment by dannylamb** [comment]
@Natkeeran @seth-shaw-unlv I'm about to assign this to @patdunlavey.  Is there anything else either of you have cooking we should know about?

**Comment by seth-shaw-unlv** [comment]
@dannylamb Sounds like a plan. I've been working on some bits for another project this morning (trying to clear the plate a bit more) and then I can better focus here. 

I don't think we need to unset the existing `@type` since the taxonomy term is likely to be a more specific type than the one set in rdf.mapping.

**Comment by dannylamb** [comment]
@seth-shaw-unlv I figured we'd keep that `@type`. What I meant to say was that if the field has been configured as a predicate (like `schema:hasAdditionalType` or something), we'd want to remove that predicate from the jsonld because its value is now in `rdf:type`.

**Comment by patdunlavey** [comment]
Does this module have any potential utility? https://www.drupal.org/project/rdfui (watch the video). Sorry if not, I'm at the bottom end of this learning curve!

**Comment by seth-shaw-unlv** [comment]
@patdunlavey 
Yes, and no. It works fine for how the core rdf module works, but it doesn't work for our attempt to override `@type` or overriding the predicate used by a field for a particular instance. 

Also, it is limited to Schema.org (I believe).

**Comment by mjordan** [comment]
@seth-shaw-unlv ok to close this issue?

**Comment by seth-shaw-unlv** [comment]
@mjordan, I would like to wait until https://github.com/Islandora-CLAW/controlled_access_terms/pull/16 is merged before closing it since the PR came out of this issue thread.
