### ISSUE TITLE
What to do with islandora_collection?

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#891]
Now that we have moved to using context and resource handling is based on tags, etc.

Do we take `islandora_collection` out behind the woodshed and delete it?

**Comment by dannylamb** [comment]
We were young and naive back then.

:fire: :fire: :fire:

**Comment by mjordan** [comment]
I can think of no better use for tags than to define "collections" of things, and Views for displaying them to the user OOTB. If we go this route, should we be defining a Collections taxonomy as per #888?

**Comment by mjordan** [comment]
Just thinking about the perpetual non-recursive nature of collection membership in 7.x where pages/child objects/members of child collections have no direct lineage to the grandparents. I wonder if using taxonomies to define collection and child relationships can help us here, where only an expensive SPARQL query or special Solr indexing meets this need in 7.x.

**Comment by dannylamb** [comment]
My understanding is that if you select a broader (e.g. parent) term to use as a search filter, it will grab everything tagged with that term or any of its children.  So we should have by default what we get from indexing ancestors in 7.x.  Is that what you're looking for?

I'm `vagrant up`ing at the moment, but I'll verify for sure once its up.

**Comment by mjordan** [comment]
Yes, that's what I'm talking about, the equivalent of the ancestor indexing in 7.x.

**Comment by whikloj** [comment]
I'm lost as to what you two are now discussing, you want to use tags for each Collection to be able to identify each item or part of an item that is part of a specific Collection?

**Comment by mjordan** [comment]
@whikloj my question is whether using taxonomies to define collection membership and compound relationships can help us avoid having to do anything special to determine, for example, if a page is a member of a collection where its book is the node that has the collection tag applied to it. I am wondering if we can avoid SPARQL queries or special indexing to determine whether that page is a "member" of its parent's collection.

**Comment by dannylamb** [comment]
@mjordan that's somewhat different than what I was describing.  I guess for what you're saying you'd want to slap the collection term on both the book and its page.

**Comment by mjordan** [comment]
Right, we don't do it in 7.x, and I'm not advocating that we do it in CLAW, I'm just wondering if D8's taxonomies offer any built-in transitivity that we can take advantage of. If not, no problem, I'm just asking the question because in 7.x it's an extra step (either by SPARQL or querying Solr for `<ancestor>` elements) to determine if a page is part of a collection.

**Comment by mjordan** [comment]
Some possible use cases for wanting to know if a page is part of a collection:

* "everything in a collection" (even pages in books) is under some sort of access control
* you want to update metadata for "everything in a collection", even children of compounds
* I want to regenerate thumbnails for "everything in a collection"

**Comment by dannylamb** [comment]
That's a good point.  I'm not sure how the hierarchical information for terms is stored in Drupal.  We may need some custom code to get at that and put it in the RDF.

**Comment by whikloj** [comment]
I has killed islandora_collection.
<img src="https://media1.tenor.com/images/58f72d6a4dc64bcca0755849a3ef95c0/tenor.gif?itemid=4878270" width="300px" alt="SpongeBob covering himself in sand."/>
