### ISSUE TITLE
Create and populate a 'TypeOfResource' vocabulary

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#894]
- Create a 'Type of Resource' vocabulary in the UI
- Create a migration to populate the vocabulary
  - It's a small, hard-coded list, so it's probably easiest to just use a CSV Migration (see https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/modules/islandora_core_feature/config/install/migrate_plus.migration.islandora_tags.yml as an example, which uses https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/migrate/tags.csv as its source).
  - Try to give elements an external URI from http://dublincore.org/documents/dcmi-type-vocabulary/ where possible.

**Comment by rtilla1** [comment]
Sprint Kick-off Meeting: We will use this as a simple field. We can borrow the work from #893 to populate the drop-down list, but it will be a field directly on the node.

**Comment by seth-shaw-unlv** [comment]
This is partially resolved with Islandora-CLAW/islandora_demo/pull/2. 

The missing part was populating the taxonomy. @dannylamb has that covered in [commit fe97fb3](/Islandora-CLAW/islandora_demo/commit/fe97fb337870d3166f3898fc26116a27462f12df) on the [issue-888 branch](/Islandora-CLAW/islandora_demo/tree/issue-888). Once those additions are merged into the main branch we can resolve this (unless we want to add more types to the migration).
