### ISSUE TITLE
Adapt migrate_7x_claw to work with latest CLAW

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#895]
https://github.com/Islandora-Devops/migrate_7x_claw will need to be touched up to account for the latest `flysystem` changes that have been merged into 8.x-1.x.

**Comment by rtilla1** [comment]
Sprint Kick-off: There are a lot of changes that rolled through last week, and patches to that work will need to be made. We do not know what this will require, so sub-tasks will be created as we go.

**Comment by patdunlavey** [comment]
Assign me please. @whikloj is this something you can provide leadership on?

**Comment by whikloj** [comment]
I was able use the existing code to migrate 6 basic images from 7.x to CLAW. 

Structure of the objects seems correct and the OBJ has the proper _Preservation Master_ tag which caused the Service File and Thumbnail to be generated.

What is missing is that the OBJ should have gone to Fedora but is in Drupal as it now needs the `fedora:` scheme to use the flysystem changes.

**Comment by patdunlavey** [comment]
That's great. Fyi, I'm still trying to figure out how to get it to load the migrations. The solr_base_url and fedora_base_url configs seem to be the source of my difficulty.

**Comment by dannylamb** [comment]
This is working for now, and i'm going to make follow up tickets.
