### ISSUE TITLE
Can't delete media/files once nodes are gone.

### ISSUE THREAD

**Issue by whikloj** [Islandora-CLAW/CLAW#900]
A failed migration rollback left me with Media and Files but the Nodes had been removed.

When trying to delete those entities I get a White Screen of Death and the Apache log lists.

> [Mon Aug 20 19:22:53.767286 2018] [:error] [pid 16304] [client 10.0.2.2:51387] Error: Call to a member function getValue() on null in /var/www/html/drupal/web/modules/contrib/islandora/src/IslandoraUtils.php on line 113 #0 /var/www/html/drupal/web/modules/contrib/islandora/src/Plugin/Condition/ParentNodeHasTerm.php(30): Drupal\\islandora\\IslandoraUtils->getParentNode(Object(Drupal\\media\\Entity\\Media))\n#1 /var/www/html/drupal/web/core/lib/Drupal/Core/Condition/ConditionManager.php(66): Drupal\\islandora\\Plugin\\Condition\\ParentNodeHasTerm->evaluate()\n#2 /var/www/html/drupal/web/core/lib/Drupal/Core/Condition/ConditionPluginBase.php(84): Drupal\\Core\\Condition\\ConditionManager->execute(Object(Drupal\\islandora\\Plugin\\Condition\\ParentNodeHasTerm))\n#3 /var/www/html/drupal/web/core/lib/Drupal/Core/Condition/ConditionAccessResolverTrait.php(26): Drupal\\Core\\Condition\\ConditionPluginBase->execute()\n#4 /var/www/html/drupal/web/modules/contrib/islandora/src/IslandoraContextManager.php(64): Drupal\\context\\ContextManager->resolveConditions(Object(Drupal\\Core\\Condition\\ConditionPluginCollection), 'and')\n#5 /var/www/html/drupal/web/modules/contrib/islandora/src/IslandoraContextManager.php(28): Drupal\\islandora\\IslandoraContextManager->evaluateContextConditions(Object(Drupal\\context\\Entity\\Context), Array)\n#6 /var/www/html/drupal/web/modules/contrib/islandora/src/IslandoraUtils.php(261): Drupal\\islandora\\IslandoraContextManager->evaluateContexts(Array)\n#7 /var/www/html/drupal/web/modules/contrib/islandora/islandora.module(161): Drupal\\islandora\\IslandoraUtils->executeMediaReactions('\\\\Drupal\\\\islando...', Object(Drupal\\media\\Entity\\Media))\n#8 [internal function]: islandora_media_delete(Object(Drupal\\media\\Entity\\Media))\n#9 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('islandora_media...', Array)\n#10 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(167): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('media_delete', Array)\n#11 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(730): Drupal\\Core\\Entity\\EntityStorageBase->invokeHook('delete', Object(Drupal\\media\\Entity\\Media))\n#12 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(369): Drupal\\Core\\Entity\\ContentEntityStorageBase->invokeHook('delete', Object(Drupal\\media\\Entity\\Media))\n#13 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(769): Drupal\\Core\\Entity\\EntityStorageBase->delete(Array)\n#14 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Entity.php(399): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->delete(Array)\n#15 /var/www/html/drupal/web/modules/contrib/islandora/src/Plugin/Action/DeleteMediaAndFile.php(105): Drupal\\Core\\Entity\\Entity->delete()\n#16 /var/www/html/drupal/web/core/lib/Drupal/Core/Action/ActionBase.php(22): Drupal\\islandora\\Plugin\\Action\\DeleteMediaAndFile->execute(Object(Drupal\\media\\Entity\\Media))\n#17 /var/www/html/drupal/web/modules/contrib/views_bulk_operations/src/Service/ViewsBulkOperationsActionProcessor.php(372): Drupal\\Core\\Action\\ActionBase->executeMultiple(Array)\n#18 /var/www/html/drupal/web/modules/contrib/views_bulk_operations/src/ViewsBulkOperationsBatch.php(126): Drupal\\views_bulk_operations\\Service\\ViewsBulkOperationsActionProcessor->process()\n#19 /var/www/html/drupal/web/core/includes/batch.inc(294): Drupal\\views_bulk_operations\\ViewsBulkOperationsBatch::operation(Array, Array)\n#20 /var/www/html/drupal/web/core/includes/batch.inc(137): _batch_process()\n#21 /var/www/html/drupal/web/core/includes/batch.inc(93): _batch_do()\n#22 /var/www/html/drupal/web/core/modules/system/src/Controller/BatchController.php(55): _batch_page(Object(Symfony\\Component\\HttpFoundation\\Request))\n#23 [internal function]: Drupal\\system\\Controller\\BatchController->batchPage(Object(Symfony\\Component\\HttpFoundation\\Request))\n#24 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)\n#25 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#26 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#27 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)\n#28 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#29 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#30 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#31 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#32 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#33 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#34 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#35 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#36 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#37 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(666): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#38 /var/www/html/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#39 {main}, referer: http://localhost:8000/batch?id=7&op=start

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/eb906c93bdb20b11bd3701dc51efd19d6b3aa23c
