### ISSUE TITLE
Convert controlled_access_terms config into a feature

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#902]
Wrap up the `config/install` directory of https://github.com/Islandora-CLAW/controlled_access_terms as a feature and push that up as a submodule a la https://github.com/Islandora-CLAW/islandora/tree/8.x-1.x/modules

**Comment by whikloj** [comment]
Soooo what parts of the config are not core to this module?

I am guessing that the 5 newly defined content-types have to stay with this module. 

So do you want all the other field definitions, entity form and display settings and rdf mappings moved out?

**Comment by seth-shaw-unlv** [comment]
Oh, I was thinking that the configs would be made into a separate feature in the controlled_access_terms module; that way the feature could still be used by other non-Islandora sites.

**Comment by whikloj** [comment]
Ohhhhh maybe it was and I read @dannylamb's `ala` incorrectly. I can move it back in.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/controlled_access_terms/commit/66bab1aaa32c5773ea2d003e94cc4e8509313fe1
