### ISSUE TITLE
Get basic XPATHs to extract an Agent from MODS

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#905]
Try to extract MODS name elements in https://github.com/Islandora-Devops/migrate_7x_claw, and provide xpaths to pull out some basic info and make the authority entities using https://github.com/Islandora-CLAW/controlled_access_terms .  This will require setting up both a 7.x and a CLAW, so if you have them both, please give this ticket a shot.   We've recently updated the README with some basic instructions to get things going.

**Comment by dannylamb** [comment]
@DigitLib Let me know if you run into any problems or need guidance on this.

**Comment by DigitLib** [comment]
@dannylamb TNX! I working on it...
