### ISSUE TITLE
Fix controlled_access_terms Authority Link configuration form

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#911]
During the [controlled_access_headings coding standards fix](https://github.com/Islandora-CLAW/controlled_access_terms/commit/6f29d15232cb69fb9d3d9245ebf721158491d817#diff-342be043a969f69e11ad32a7ea70b296L141) I accidentally broke the ability to modify the authorities configuration form. 

(And this is why you don't merge stuff you've been touching. Oh, and why it should have had tests, too.)

A PR is imiment.

**Comment by whikloj** [comment]
Resolved with https://github.com/Islandora-CLAW/controlled_access_terms/commit/5263576c5f2bac82f95d1e453dd4eb795e295991
