### ISSUE TITLE
controlled_access_terms content types as taxonomies

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#912]
Based on our conversation yesterday related to #896 we decided I would explore turning the [Islandora-CLAW/controlled_access_terms](https://github.com/Islandora-CLAW/controlled_access_terms) content models (People, Corporate Bodies, Families, Geographic Locations, and Subjects) into taxonomies; because they are means of organizing content, not necessarily content themselves. 

Tagging: @rtilla1 @rosiel @dannylamb

**Comment by seth-shaw-unlv** [comment]
Based on a conversation with @rosiel in IRC:

- Preferred name will no longer be required.
- We are dropping auto_entitylabel (although we will point people to it in case they want it). This may result in double-entry (but that is, in many cases, desirable; especially for migrations).

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/controlled_access_terms/commit/66bab1aaa32c5773ea2d003e94cc4e8509313fe1
