### ISSUE TITLE
Fix controlled_access_terms TypedRelations validateValues

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#915]
Somehow (I'm guessing when I was doing coding standard cleanup) the [validate values function declaration](https://github.com/Islandora-CLAW/controlled_access_terms/blob/8.x-1.x/src/Plugin/Field/FieldType/TypedRelation.php#L175) declared the wrong variable type (should be array instead of (FormElement). Fortunately, it will be a simple fix.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/controlled_access_terms/commit/66bab1aaa32c5773ea2d003e94cc4e8509313fe1
