### ISSUE TITLE
Migrate AUDIT datastream

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#917]
Following up on #904 and related to #847. I'll start work on this after Sept. 12.

**Comment by dannylamb** [comment]
The selectors need to be tweaked now that we're actually using XPath wtih simplexml.  But all of that is going to change again when I roll it into https://github.com/Islandora-Devops/migrate_7x_claw/pull/10, so maybe I should just do that and address your feedback there.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/migrate_7x_claw/commit/052e2ccf4d0670aed04ac494fef19248d2ef6a25

**Comment by rosiel** [comment]
For the record, resolved via Option 1, and migrate_7x_claw "gets" (extracts) the audit datastream and stores it intact. (right?)

**Comment by dannylamb** [comment]
@rosiel It extracts it form the FOXML with this XPath: `'foxml:datastream[@ID = "AUDIT"]/foxml:datastreamVersion/foxml:xmlContent/*'` and then stores it as a file+media in Drupal associated with your node.

If you're curious, you can configure that XPath here: https://github.com/Islandora-Devops/migrate_7x_claw/blob/master/modules/islandora_migrate_7x_claw_feature/config/install/migrate_plus.migration.islandora_audit_file.yml#L42
