### ISSUE TITLE
Update to Drupal 8.6

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#920]
We'll get a media library and some improvements to content translation.  We should check it out.

https://www.drupal.org/blog/drupal-8-6-0

**Comment by dannylamb** [comment]
I just pushed up a temporary branch to the foundation's repo for testing: https://github.com/Islandora-CLAW/drupal-project/tree/drupal-8.6

This is so I can point our installer at it here: https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L18

**Comment by dannylamb** [comment]
Also, we can upload files directly via REST now, which may or may not affect what we're already doing.  There's a good chance we can ditch some code :fire: :fire: :fire:

**Comment by dannylamb** [comment]
hrm... the geerlingguy drupal role seems to not run `composer drupal:scaffold` anymore, or are we doing that elsewhere?  I have to look.

**Comment by dannylamb** [comment]
Ok, sorted that out, but then ran square into this: https://www.drupal.org/project/features/issues/2992790#comment-12763159

There's already a patch up that works, so it's just a matter of time until we can move forward with this.

**Comment by Natkeeran** [comment]
@dannylamb The patch is committed.

**Comment by Natkeeran** [comment]
Thanks Danny.  Looks good.
