### ISSUE TITLE
Import controlled_access_terms features in claw-playbook

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#921]
Update https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml#L95 to include the features from controlled_access_terms so that they're available when you install.

Also, change https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L43 to enable the feature submodule, which in turn depends on controlled_access_terms.

**Comment by seth-shaw-unlv** [comment]
By default we have claw-playbook enabling islandora_demo, which is great for development, but not so great when someone wants to do a production site with their own content models. Should we have a setting in inventory that can toggle installing demo?

**Comment by dannylamb** [comment]
Once the [bug we're working around](https://www.drupal.org/node/2599228) with all that post-install nonsense gets resolved, we won't have to do it anymore and you can toggle installing the demo module by including/excluding it from https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L29

But in the meantime, adding a toggle as a stop-gap measure sounds very reasonable and easy to implement.
