### ISSUE TITLE
Claw-playbook solr server configuation fail

### ISSUE THREAD

**Issue by sulfurchesh** [Islandora-CLAW/CLAW#923]
On Ubuntu 18.04, vagrant 2.1.2, ansible 2.5.3, I grabbed the latest git repo (hash: 48e157a ) and did a vagrant box update, and vagrant provision, and the configuration/etc failed with the following error:

TASK [webserver-app : Set default solr server to point to CLAW core] ***********
Friday 14 September 2018  14:15:26 -0400 (0:00:00.401)       0:05:13.296 ******
fatal: [default]: FAILED! => {"changed": false, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "-y", "config-set", "search_api.server.default_solr_server", "backend_config.connector_config.core", "CLAW"], "delta": "0:00:00.218546", "end": "2018-09-14 18:15:26.156609", "msg": "non-zero return code", "rc": 1, "start": "2018-09-14 18:15:25.938063", "stderr": " [error]  Config search_api.server.default_solr_server does not exist ", "stderr_lines": [" [error]
  Config search_api.server.default_solr_server does not exist "], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/home/ansibleclaw/claw-playbook/playbook.retry

**Comment by dannylamb** [comment]
Thanks for reporting htis @sulfurchesh

**Comment by sulfurchesh** [comment]
With the latest commits and newest virtualbox provision, this is resolved for us.
