### ISSUE TITLE
Add CENTOS support for installing Matomo

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#946]
Part of https://github.com/Islandora-CLAW/CLAW/issues/792

@Natkeeran added a [Matomo ansible role](https://github.com/Islandora-Devops/ansible-role-matomo) and [some code in claw-playbook to install it](https://github.com/Islandora-Devops/claw-playbook/commit/84275342896bafc95142c8a187f1703b566bc548) on Ubuntu.  We need to add to this to support CENTOS.  I haven't done a deep dive, but I suppose it will have to deal with subtleties in how Apache is handled between distributions.

**Comment by seth-shaw-unlv** [comment]
Not bad. It's the same issue we had with Crayfish. The linked PR resolves it the same way we did it there.

**Comment by seth-shaw-unlv** [comment]
Resolved with Islandora-Devops/ansible-role-matomo/pull/1
