### ISSUE TITLE
Chown and chmod stuff in post-install.yml

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#948]
There's two things I have to do over and over again every time I spin up a claw-playbook instance.

1. Make and then `chown` and `chmod` the `/var/www/html/drupal/web/sites/default/files/simpletest` directory so that it is writable by the apache user.  Otherwise you can't run tests.
1. `chown` and `chmod` the three features modules we use (`islandora_core_feature`, `islandora_demo`, and `controlled_access_terms_default_configuration`).  Otherwise you can't export features.

Ideally, we'd make the vagrant user part of the `www-data` group, then `chown -R www-data:www-data /var/www/html/drupal/web/sites/default/files/simpletest` and `chmod -R g+w /var/www/html/drupal/web/sites/default/files/simpletest`.  Lather, rinse, repeat for the three features.  I'm sure it will be subtly different for CENTOS, but essentially the same.

This would help solve two major annoyances from a developer experience perspective.

**Comment by ppound** [comment]
Danny if you want to assign this to me I can take a look.

**Comment by ppound** [comment]
created a pull request for this here https://github.com/Islandora-Devops/claw-playbook/pull/80.  I think this does what we need but some tests still fail with error that there is html in output but they don't throw the can't copy exception anymore.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/claw-playbook/commit/39ffe550db2bd852fecbbc3e8eb024591a4ca6bb
