### ISSUE TITLE
Persist MODS as binary resource?

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#951]
This is a question about [migrate_7x_claw](https://github.com/Islandora-Devops/migrate_7x_claw). Why is the MODS datastream stored in a text field and not as binary resource? Should the AUDIT datastream (#917) or other text-based datastreams be stored the same way?

**Comment by whikloj** [comment]
I did that as part of a test to get the data out of the MODS into individual fields. 
But now we have the TuqueDatastream data parser that grabs all the various datastreams and makes them each a separate data row to be persisted.

**Comment by mjordan** [comment]
I've removed that block from `migrate_plus.migration.islandora_basic_image.yml` and the `Basic Image Objects` migration still works as expected. Mind if I open a PR that removes that config block?

**Comment by mjordan** [comment]
PR is at https://github.com/Islandora-Devops/migrate_7x_claw/pull/7.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/migrate_7x_claw/commit/6bfed5a204665e7d93b7a6912f0da7f4e587eb9d
