### ISSUE TITLE
Can't get migrate_7x_claw to work

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#952]
I'm trying out migrate_7x_claw and none of my sample objects are migrating. After executing the migration, I get ` Processed 0 items (0 created, 0 updated, 0 failed, 0 ignored) - done with 'islandora_demo_tags' `.

I'm attaching my yaml files, but in summary:

* There are no unexpected entries in the CLAW system messages log.
* My source Islandora 7.x (clean Vagrant) has 20 basic image objects.
* The IP address and port of my source fedora and solr in the YAML files are correct. I can `curl` from my CLAW vagrant:
  * `curl -u fedoraAdmin:fedoraAdmin -v http://192.168.0.120:8080/fedora/admin`
  * `curl -v "http://192.168.0.120:8080/solr/collection1/select?q=*%3A*&rows=100&wt=json&indent=true"`
* `content_model_field: RELS_EXT_hasModel_uri_ms` is correct
* I've tried both without (as in the .yaml files in the repo) and with (as documented in the README) the `&fedora_auth` and `&fedora_base_url` placeholders.

Any suggestions as to what I'm doing wrong or what I can check?

[migration_yamls.zip](https://github.com/Islandora-CLAW/CLAW/files/2462176/migration_yamls.zip)

**Comment by whikloj** [comment]
`islandora_demo_tags` would not be this migration, you're looking to run `islandora_basic_image`, `islandora_basic_image_files` and `islandora_basic_image_media`.

**Comment by mjordan** [comment]
I must be missing something. Here's what I did:

1. Built my claw-playbook from 84275342896bafc95142c8a187f1703b566bc548. 
1. Cloned https://github.com/Islandora-Devops/migrate_7x_claw into `/var/www/html/drupal/web/modules/contrib`
1. `drush en migrate_7x_claw`
1. `drush cc all` (just for good measure)

But when I go to `http://localhost:8000/admin/structure/migrate` before and after the above steps, I see the following:

![migrations0](https://user-images.githubusercontent.com/403918/46709459-bdb6c580-cbf8-11e8-9fb2-770a601a19ab.png)

Which doesn't match the screenshot on the Migrate 7x CLAW README.

**Comment by mjordan** [comment]
OK, figured it out seconds after posting the previous comment. There are two modules - I didn't `drush en islandora_migrate_7x_claw_feature`.

**Comment by mjordan** [comment]
Sigh. Now I'm getting the following error:

> Drupal\migrate\MigrateException: Error message: cURL error 7: Failed to connect to 10.0.2.2 port 18080: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at http://10.0.2.2:18080/solr/select?rows=0&start=0&fl=PID&wt=json&q=RELS_EXT_hasModel_uri_ms:("islandora:sp_basic_image" OR "info:fedora/islandora:sp_basic_image")&sort=PID+asc. in Drupal\migrate_plus\Plugin\migrate_plus\data_fetcher\Http->getResponse() (line 108 of /var/www/html/drupal/web/modules/contrib/migrate_plus/src/Plugin/migrate_plus/data_fetcher/Http.php).

Which is really strange because when I run `grep -r '10\.0\.2\.2' *` inside `/var/www/html/drupal/web/modules` I only get hits in README.md. In other words, the IP address `10.0.2.2` doesn't exist in my yaml files. I also tried clearing the cache with no effect.

**Comment by DiegoPino** [comment]
@mjordan your configurations for each YAML file tid to each CMODEL type migration are probably wrong or missing pieces. You need to make sure `solr_base` is set as requested by https://github.com/Islandora-Devops/migrate_7x_claw/blob/master/src/Plugin/migrate/source/Islandora.php#L138
and according to https://github.com/Islandora-Devops/migrate_7x_claw#example-usage its here

https://github.com/Islandora-Devops/migrate_7x_claw/tree/master/modules/islandora_migrate_7x_claw_feature/config/install

i see a lot of 10.0.2.2:18080  there https://github.com/Islandora-Devops/migrate_7x_claw/blob/master/modules/islandora_migrate_7x_claw_feature/config/install/migrate_plus.migration.islandora_basic_image_media.yml#L18

with a HIGH EMPHASIS on defaulting to port **18080** which is a quite high port so my guess its a type

Give that a try

**Comment by mjordan** [comment]
@DiegoPino thanks but, I've just eyeballed all the yaml files in `/var/www/html/drupal/web/modules/contrib/migrate_7x_claw/modules/islandora_migrate_7x_claw_feature/config/install
` plus done the `grep` I described above. No occurrences of that IP address or port number exist in those files.

**Comment by mjordan** [comment]
Hm. `Running drush pm:uninstall islandora_migrate_7x_claw_feature` and then `drush en islandora_migrate_7x_claw_feature` have resolved my problems. Closing.... thanks guys.

@whikloj I'm probably going to open a PR on the README.

**Comment by whikloj** [comment]
@mjordan I am no `feature` master, but you might have needed to `enable` the feature, then `import` it once you made your changes.

**Comment by mjordan** [comment]
Any reason `islandora_migrate_7x_claw_feature` is not in the `dependencies` list for `migrate_7x_claw`?

**Comment by whikloj** [comment]
Because it is not a strict dependency. You can use the plugins from `migrate_7x_claw` with your own migration.

**Comment by mjordan** [comment]
Ah, thanks.
