### ISSUE TITLE
Add a search block

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#953]
We need to create a search block (text field + magnifying lens button) and deploy that with claw-playbook.  Blocks are inherently tied to theme, so while we may have to define the block in `islandora`, the actual exported block configuration will have to go in `islandora_demo` since it will couple tightly with `carapace`.

**Comment by dannylamb** [comment]
:man_shrugging: https://www.drupal.org/project/better_search

**Comment by Natkeeran** [comment]
@dannylamb 

Since we disabled search module, the default Drupal search box does not seem to be available.  

https://www.drupal.org/project/search_api_page seems like a simple solution to search Full Text fields.
