### ISSUE TITLE
Investigate re-using `islandora-connector-houdini`

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#957]
We should be able to re-use `islandora-connector-houdini` from Alpaca and deploy another copy of it by placing a config file in `/opt/karaf/etc`.  By chaning the input stream and houdini URLs, we could conceivably point at a wide variety of microservices that follow Houdini's pattern.  For example, a microservice built around `ffmpeg` could use the same `Accept` and `Apix-Ldp-Resource` headers, and the Camel listener wouldn't have to change.  Just config!

It's a promise of OSGi that's enticing, but I'd like to investigate it to be 100% sure it's possible before making a ticket to do it.

**Comment by whikloj** [comment]
So I don't think I understand this. You can't get a whole new service by adding a new configuration file, can you?

**Comment by ajs6f** [comment]
Actually, you totally can. OSGi services need code and (possibly some) configuration, but there's no reason they would need fresh code for every service.

**Comment by whikloj** [comment]
I've made simple route just dropping the XML into a Karaf deploy directory, but I had not heard of this and will now watch patiently and learn.
<img src="https://media.giphy.com/media/Bzebpz5rnyBb2/giphy.gif"/>

**Comment by dannylamb** [comment]
So this works fine dropping an XML into the deploy directory, but I'm having a heckuva time getting it wrapped up as a bundle and made into a feature.  I need some time to wrestle the OSGi bear a bit.  Right now it builds, but does not deploy because it can't find code that I know I'm exporting correctly :sob:

**Comment by dannylamb** [comment]
Here's my work so far: https://github.com/dannylamb/Alpaca/tree/refactor-blueprint
