### ISSUE TITLE
Migration produces empty binary resources

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#958]
Migrate_7x_claw does not persist the content of the 7.x datastreams into corresponding binary resources. I know that my 7.x repository is serving the content up, since from the terminal on my CLAW machine I can issue curl requests like:

`curl -u fedoraAdmin:fedoraAdmin "http://192.168.0.120:8080/fedora/objects/testing:1/datastreams/MODS/content"`

and get back the expected XML content (in this case). But during the `islandora_basic_image_files` migration I see the following (I'm doing it on the command line):

```
 drush migrate-import islandora_basic_image_files
[warning] fseek(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:421
[warning] fclose(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:387
[warning] fseek(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:421
[warning] fclose(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:387
[...]
```

and during the `islandora_basic_image_media` migration:
```
drush migrate-import islandora_basic_image_media
adding in mimetype mappings
 [error]  Error generating event: Could not locate source file for media 4 
 [error]  Error generating event: Could not locate source file for media 11 
 [error]  Error generating event: Could not locate source file for media 18 
 [error]  Error generating event: Could not locate source file for media 25 
 [[...]
```

Binary resources are created in Fedora, but they all have a 0 hasSize value and they all have the same SHA-1 digest, `urn:sha1:da39a3ee5e6b4b0d3255bfef95601890afd80709 `, which is the SHA-1 digest generated from an empty string:

![fcrepo](https://user-images.githubusercontent.com/403918/46766637-6582d080-cc97-11e8-9e7f-ab8a4d7e5b9d.png)

**Comment by dannylamb** [comment]
@mjordan Are Solr and Fedora 3 url's are set properly in this chunk? https://github.com/Islandora-Devops/migrate_7x_claw/blob/master/modules/islandora_migrate_7x_claw_feature/config/install/migrate_plus.migration.islandora_basic_image_files.yml#L16-L26

Also seeing Fedora url is repeated here: https://github.com/Islandora-Devops/migrate_7x_claw/blob/master/modules/islandora_migrate_7x_claw_feature/config/install/migrate_plus.migration.islandora_basic_image_files.yml#L34

**Comment by dannylamb** [comment]
@whikloj You think when I exported the feature it stripped those out?

**Comment by whikloj** [comment]
@dannylamb right, so we could add them back in or leave it up to the end user to populate them correctly.

**Comment by dannylamb** [comment]
@mjordan Running a test migration from a fresh `islandora_vagrant` now.

@whikloj Either way, i'm easy.

**Comment by dannylamb** [comment]
@mjordan Just worked fine for me.  I ran it on about 20 something objects and all the datastreams came over intact.  I need to slap `Media Use` tags on them, but they came over and are accessible through Drupal and Fedora.

![screenshot from 2018-10-11 10-52-15](https://user-images.githubusercontent.com/20773151/46809115-370eff00-cd44-11e8-8576-7c6c38a41800.png)
![screenshot from 2018-10-11 10-53-10](https://user-images.githubusercontent.com/20773151/46809121-39715900-cd44-11e8-9e3a-faec95bd5228.png)
![screenshot from 2018-10-11 10-59-50](https://user-images.githubusercontent.com/20773151/46809427-ce745200-cd44-11e8-9826-a1aa1191e750.png)


We're by default set up to run off an `islandora_vagrant` instance locally (that's what the 10.0.2.2 is all about), which is all I've ever tried.  Are you pointing at a separate machine?  Maybe there's another step we just haven't taken into consideration due to that.

**Comment by mjordan** [comment]
Just building a 7:00 am claw-playbook now to retest... but yes, I am pointing to a separate machine. But I can `curl` to it to get the datastream content from the claw-playbook's command line so I don't think there are any authentication (for example) issues. Will retest when my box has built and let you know what the outcome is.

**Comment by mjordan** [comment]
When you say "slap media tags on them", what do you mean exactly?

**Comment by whikloj** [comment]
@dannylamb oh right, so we need to remove these `bundle` tags right? I wonder if it will work like that and just check every vocabulary?
https://github.com/Islandora-Devops/migrate_7x_claw/blob/master/modules/islandora_migrate_7x_claw_feature/config/install/migrate_plus.migration.islandora_basic_image_media.yml#L111

**Comment by whikloj** [comment]
Also it looks like we are assigning them to the field tags. So that will have to be changed too.

**Comment by dannylamb** [comment]
@whikloj Yeah, seeing that now too.  I'll see what I can do.

Also thinking if we moved these yml to the migration group defined in core `islandora`, we could piggyback off of the tag migrations and grab them with entity_lookup.

**Comment by mjordan** [comment]
On this morning's fresh CLAW vm, my files now have content :smile: Not sure what's different. But, I am still seeing the following warnings when I run the `islandora_basic_image_files` migration:

```
 drush migrate-import islandora_basic_image_files
adding in mimetype mappings
 [warning] fseek(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:421
 [warning] fclose(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:387
 [warning] fseek(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:421
 [warning] fclose(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:387
 [warning] fseek(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:421
 [warning] fclose(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:387
 [warning] fseek(): supplied resource is not a valid stream resource FlysystemStreamWrapper.php:421
```
etc. Are they important?

**Comment by dannylamb** [comment]
@mjordan No, they're not.  In fact I can even squash those with an @ in the flysystem code.  At one point i was doing that, then felt bad/dirty and took it out.  Now I realize I should've just left it in.

**Comment by mjordan** [comment]
Welp, looks like I can close this issue then! That OK or do you want to do it once you've created issues for some of the things you guys were discussing above?

**Comment by whikloj** [comment]
You can close this and we can create an issue to revisit these configurations once #888 is merged.
