### ISSUE TITLE
Consolidate controlled_access_terms external authority fields

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#963]
Currently the [controlled_access_terms_default_configuration](https://github.com/Islandora-CLAW/controlled_access_terms/tree/8.x-1.x/modules/controlled_access_terms_default_configuration/config/install) creates separate field storage configurations. This unnecessary complexity makes searching for a term based on an external uri difficult unless you know which vocabulary it is already in.

E.g. searching for a term based on a uri looks something like: 
```
print_r(\Drupal::entityManager()->getStorage('taxonomy_term')->loadByProperties(['field_subject_authorities'=>'http://example_uri']));
print_r(\Drupal::entityManager()->getStorage('taxonomy_term')->loadByProperties(['field_person_name_authority'=>'http://example_uri']));
print_r(\Drupal::entityManager()->getStorage('taxonomy_term')->loadByProperties(['field_geo_authority_link'=>'http://example_uri']));
print_r(\Drupal::entityManager()->getStorage('taxonomy_term')->loadByProperties(['field_family_name_authorities'=>'http://example_uri']));
print_r(\Drupal::entityManager()->getStorage('taxonomy_term')->loadByProperties(['field_corporate_body_authorities'=>'http://example_uri']));
```

Consolidating them down to a single field (field_authority_link) allows us to perform a single search across all the vocabularies that implement this field: 
```
print_r(\Drupal::entityManager()->getStorage('taxonomy_term')->loadByProperties(['field_authority_link'=>'http://example_uri']));
```

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/controlled_access_terms/commit/cc85deac98c62824e38802f9c565b27e98db64bd
