### ISSUE TITLE
Swapping display mode with Context affects all entities rendered on a single page

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#969]
If you use context to swich display modes (like in islandora_demo with the openseadragon tag), all entities rendered on a page will be rendered with the selected display mode.  This means a view will adopt the display mode that you switched with context, which is unexpected behaviour to say the least.

For example, turn on openseadragon for a collection, and watch the teasers of all its members use the openseadragon viewer.

We need to add a check here https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/islandora.module#L255 to make sure we're only changing the display mode of the entity that's in the url.  E.g. only affect node 1 and no other entities on localhost:8000/node/1.

**Comment by ppound** [comment]
I created a pull request for this https://github.com/Islandora-CLAW/islandora/pull/104 that I think solves this issue.

**Comment by seth-shaw-unlv** [comment]
Resolved via Islandora-CLAW/islandora/pull/104
