### ISSUE TITLE
Rename islandora_demo to islandora_default

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#970]
Remove the `islandora_object` content type and all of its fields and put into its own module.  Rebrand the remains of islandora_demo (the contexts, the actions, etc...) as islandora_ext.

This may be very difficult due to how drupal handles dependencies.  By their nature, those contexts and actions rely on the `islandora_object` content type, so how we split those things out is in the air.  Automating some sort of process, or using templating to generate the config with users supplying the content type, anything.  However we can figure out how to do it, because there's a lot of great functionality in islandora_demo that people can't use without taking on the full `repository_item` content type.

**Comment by dannylamb** [comment]
Giving this some thought while I spin up a vagrant box...

@seth-shaw-unlv  Were you hinting earlier at perhaps instead of supplying the feature, we supply a script that will generate a feature for a user if they supply a content type?

**Comment by seth-shaw-unlv** [comment]
@dannylamb I was actually hinting at telling someone how to write their own install script to do it (that way when they enable their module it simply inserts itself where it belongs), but I think your second suggestion might be better. Furthering that line of thinking, how hard would it be to use the existing drush config:set command to do this?

**Comment by seth-shaw-unlv** [comment]
We can leave islandora_object in the module. We should rename it to islandora_defaults instead of islandora_ext.

**Comment by Natkeeran** [comment]
Suggest naming it to islandora_default instead of islandora_default_config.

**Comment by dannylamb** [comment]
yup... i derped there @Natkeeran.  Seeing that now.

**Comment by Natkeeran** [comment]
Should it be islandora_default or islandora_defaults ? :)

**Comment by seth-shaw-unlv** [comment]
search_api_solr uses the plural: search_api_solr_defaults

**Comment by dannylamb** [comment]
i'm leaning towards `defaults`, but that's 100% feels based

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/claw-playbook/commit/eaaeeeb2ad5853cbf8ec097266cdbe86659a89a0

**Comment by mjordan** [comment]
Coolest commit short hash ever.
