### ISSUE TITLE
fcrepo_data_dir in ansible-role-fcrepo is misleading

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#971]
The documentation says that the variable `fcrepo_data_dir` is the "Path to put Fedora data directory". However, the role only creates the directory. This does not affect the repository.json file which declares where Fedora will actually try to put your data.

Try it out with a clean playbook: run it with the defaults and create some repository items. You will notice that the claw_playbook created a directory `/var/lib/tomcat8/fcrepo4-data` as indicated by the role's default settings; however, the new fcrepo objects will actually be stored in the fedora home `/opt/fcrepo/`. 

I didn't notice this behavior until I set fcrepo_data_dir to a path on a large storage partition (`/data/fcrepo`) and ran a _large batch import that crashed the system_ because it filled the primary partition (because it had the fedora home directory `/opt/fcrepo/`).

So, to avoid this for others I recommend we do one of two things:

1. Update the documentation to say users should modify their tomcat variables to match, e.g. using the tomcat ansible role we currently do
    ```
    fcrepo_data_dir: "/data/fcrepo-data"
    
    tomcat8_java_opts:
      - -Dfcrepo.binary.directory={{ fcrepo_data_dir }}
    ```
1. OR update the role's repository.json to explicitly use fcrepo_data_dir instead of the default Tomcat opts (e.g.`${fcrepo.binary.directory:target/binaries}`)

Thoughts on which would be preferable?

**Comment by dannylamb** [comment]
@seth-shaw-unlv Option 2?  Then you only have to set it in one place.

**Comment by seth-shaw-unlv** [comment]
Either is fine by me. I just wasn't sure how sacred (if at all) those Tomcat variables are to the Fedora crowd or if we would be confusing long-time Fedora users by not using them since _every_ example I've seen uses them. (It actually took me quite a while to figure out they _were_ Tomcat variables since I didn't see the documentation didn't state that anywhere despite all the examples using them.)

**Comment by whikloj** [comment]
I would suggest using the system property `fcrepo.home` which will stick the fcrepo4-data directory under it. 
Ala `-Dfcrepo.home=/put/my/data`

For more information see: https://wiki.duraspace.org/display/FEDORA4x/Application+Configuration

**Comment by seth-shaw-unlv** [comment]
@whikloj, the claw_playbook includes using the fcrepo_home_dir directory, so changing that variable would work, although it would also place all the configuration files there as well. 

However, focusing on fcrepo_home_dir means that fcrepo_data_dir is still sitting around impotently. I think we should either document how to use it correctly (even if it isn't preferred) or remove it from the ansible role to avoid confusion.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/ansible-role-fcrepo/commit/be9ae4c2c4fccd836736fcaddcb80663a3b12ec6
