### ISSUE TITLE
AuthenticationException when trying to create derivatives

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#981]
Crayfish - Houdini is throwing AuthenticationException when trying to create derivatives.

## Steps to reproduce
* vagrant up
* create an image with a Preservation Master File use tag

## Expected
* derivative Service and TN files to be created

## Actual
* derivative files are not created

## Additional Notes
houdini.log
```
[2018-11-30 09:22:34] app.INFO: Matched route "{route}". {"route":"GET_convert","route_parameters":{"_controller":"houdini.controller:convert","_route":"GET_convert"},"re$
[2018-11-30 09:22:34] app.DEBUG: Checking for guard authentication credentials. {"firewall_key":"default","authenticators":1} []
[2018-11-30 09:22:34] app.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"default","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenti$
[2018-11-30 09:22:34] crayfish.syn.jwt_authentication.DEBUG: Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1NDM1OTEzMzQsImV4cCI6MTU0MzU5ODUzNCwid2ViaWQiOiIxIiwia$
[2018-11-30 09:22:34] crayfish.syn.jwt_authentication.INFO: Token missing uid [] []
[2018-11-30 09:22:34] app.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Co$
[2018-11-30 09:22:34] app.DEBUG: Calling Authentication entry point. [] []
[2018-11-30 09:22:34] app.DEBUG: < 401 [] []
```

Event creation log
```
{
   "@context":"https:\/\/www.w3.org\/ns\/activitystreams",
   "actor":{
      "type":"Person",
      "id":"urn:uuid:ad6049e0-dd9c-4c04-bad3-1255e929d1c7",
      "url":[
         {
            "name":"Canonical",
            "type":"Link",
            "href":"http:\/\/localhost:8000\/user\/1",
            "mediaType":"text\/html",
            "rel":"canonical"
         }
      ]
   },
   "object":{
      "id":"urn:uuid:818a7e60-ed3f-4646-bb47-05bf61fa8e1a",
      "url":[
         {
            "name":"Canonical",
            "type":"Link",
            "href":"http:\/\/localhost:8000\/node\/2",
            "mediaType":"text\/html",
            "rel":"canonical"
         },
         {
            "name":"JSON",
            "type":"Link",
            "href":"http:\/\/localhost:8000\/node\/2?_format=json",
            "mediaType":"application\/json",
            "rel":"alternate"
         },
         {
            "name":"JSONLD",
            "type":"Link",
            "href":"http:\/\/localhost:8000\/node\/2?_format=jsonld",
            "mediaType":"application\/ld+json",
            "rel":"alternate"
         }
      ]
   },
   "type":"Activity",
   "summary":"Generate Derivative",
   "attachment":{
      "type":"Object",
      "content":{
         "mimetype":"video\/mp4",
         "args":"",
         "source_uri":"http:\/\/localhost:8000\/_flysystem\/fedora\/2018-11\/Red_Panda.JPG",
         "destination_uri":"http:\/\/localhost:8000\/node\/2\/media\/image\/17",
         "file_upload_uri":"public:\/\/2018-11\/2.mp4"
      },
      "mediaType":"application\/json"
   }
}
```

## Environment 
* Islandora - 4ba1816ed91fcb5f7ab77b56145496fc63332248 (after video derivative abstraction commit)
* claw-playbook - fa448ea6aad0c898f25824dab7d335402533e325 (latest!)
* Crayfish - 6223e2fd5253d3abbdeb4541d4405983b1563c4a

@whikloj @dannylamb

**Comment by dannylamb** [comment]
I recently experienced this when testing on a pretty frankenstein'd environment.  I was going to blow it away and spin back up with the hopes of it sorting itself out :frowning: 

`crayfish.syn.jwt_authentication.INFO: Token missing uid [] []`

We reverted the syn PR, but not https://github.com/Islandora-CLAW/islandora/pull/84 and https://github.com/Islandora-CLAW/Crayfish-Commons/pull/15.  We probably want to keep on using the standard claims, so we need to sort out where it's looking for `uid` and change that to `webid`.

**Comment by dannylamb** [comment]
Hrm... that's basically what https://github.com/Islandora-CLAW/Crayfish-Commons/pull/15 did...

Maybe we need to update the .lock files or something in each microservice in Crayfish.  They're all set to pull `dev-master` of crayfish commons, so it should be pulling down the latest in theory.

**Comment by dannylamb** [comment]
Oh yah, my box is stuck at 38657d33f959b8bdeb59e8f7f4aa6012db2160e7 for Gemini, Houdini, and Hypercube.  9434f75659af2abaf433436d1aa847de4416d8ae for Milliner.  Only Homarus has the right version.

**Comment by dannylamb** [comment]
@Natkeeran PR is up ^^
