### ISSUE TITLE
Video derivative event gets fired when an image media is created

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#982]
When an image media file is created for an image repository item, a video derivative event is created.  Should it?

## Steps to reproduce
* vagrant up
* create an image with a Preservation Master File use tag

## Additional Notes
```
{
   "@context":"https:\/\/www.w3.org\/ns\/activitystreams",
   "actor":{
      "type":"Person",
      "id":"urn:uuid:ad6049e0-dd9c-4c04-bad3-1255e929d1c7",
      "url":[
         {
            "name":"Canonical",
            "type":"Link",
            "href":"http:\/\/localhost:8000\/user\/1",
            "mediaType":"text\/html",
            "rel":"canonical"
         }
      ]
   },
   "object":{
      "id":"urn:uuid:818a7e60-ed3f-4646-bb47-05bf61fa8e1a",
      "url":[
         {
            "name":"Canonical",
            "type":"Link",
            "href":"http:\/\/localhost:8000\/node\/2",
            "mediaType":"text\/html",
            "rel":"canonical"
         },
         {
            "name":"JSON",
            "type":"Link",
            "href":"http:\/\/localhost:8000\/node\/2?_format=json",
            "mediaType":"application\/json",
            "rel":"alternate"
         },
         {
            "name":"JSONLD",
            "type":"Link",
            "href":"http:\/\/localhost:8000\/node\/2?_format=jsonld",
            "mediaType":"application\/ld+json",
            "rel":"alternate"
         }
      ]
   },
   "type":"Activity",
   "summary":"Generate Derivative",
   "attachment":{
      "type":"Object",
      "content":{
         "mimetype":"video\/mp4",
         "args":"",
         "source_uri":"http:\/\/localhost:8000\/_flysystem\/fedora\/2018-11\/Red_Panda.JPG",
         "destination_uri":"http:\/\/localhost:8000\/node\/2\/media\/image\/17",
         "file_upload_uri":"public:\/\/2018-11\/2.mp4"
      },
      "mediaType":"application\/json"
   }
}
```

## Environment 
* Islandora - 4ba1816ed91fcb5f7ab77b56145496fc63332248 (after video derivative abstraction commit)
* claw-playbook - fa448ea6aad0c898f25824dab7d335402533e325 (latest!)
* Crayfish - 6223e2fd5253d3abbdeb4541d4405983b1563c4a

@whikloj

**Comment by whikloj** [comment]
I am not seeing the same thing, but if you could check the Context for the "Video Preservation Master" and see what the "Parent node for Media has Term" looks like? I see "Video" which means the parent Repository Item needs to have the "System -> Model" of "Video" to get that event.

Also check your Action -> "Generate a service file from image preservation master" and make sure none of the configuration there is messed up.

**Comment by Natkeeran** [comment]
The Video Preservation Master context looks good.  It is looking for Video (24) and Preservation Master File (16).  

Action -> "Generate a service video file from preservation master video file" is pointing to islandora-connector-houdini.  Other than that they look good.
