### ISSUE TITLE
Add userid option to drush migrate command

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#988]
The most recent versions of Drush migrate removed the userid switch. This results in migrations being performed by anonymous which breaks authentication with other services. We need to restore that switch so migrations can be performed by those with authority to create derivatives.

**Comment by whikloj** [comment]
When this is resolved a PR for claw-playbook should update [this line](https://github.com/Islandora-Devops/claw-playbook/blob/master/post-install.yml#L33) with the admin user id.

**Comment by mjordan** [comment]
@seth-shaw-unlv tested your issue-988 branch, and it worked:

```
drush  migrate:import --userid 1 --group migrate_islandora_csv
 [notice] Now acting as user ID 1
 [notice] Processed 0 items (0 created, 0 updated, 0 failed, 0 ignored) - done with 'file'
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'node'
adding in mimetype mappings
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'media'
 [notice] Switching back from user 1.
```

:+1:

**Comment by mjordan** [comment]
Woops, sorry, it didn't work, my first test was in an unclean environment. The migration I'm using is https://github.com/dannylamb/migrate_islandora_csv, and (now that I've rolled back a previously failed migration) the files migration is failing:

```
drush  migrate:import --userid 1 --group migrate_islandora_csv
 [notice] Now acting as user ID 1
 [notice] Processed 5 items (0 created, 0 updated, 5 failed, 0 ignored) - done with 'file'

In MigrateToolsCommands.php line 717:
                              
  file Migration - 5 failed.  
                              

migrate:import [--all [ALL]] [--group [GROUP]] [--tag [TAG]] [--limit [LIMIT]] [--feedback [FEEDBACK]] [--idlist [IDLIST]] [--update [UPDATE]] [--force [FORCE]] [--execute-dependencies [EXECUTE-DEPENDENCIES]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--userid USERID] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<migration_names>]

```
If I rerun the group migration, I get this:

```
vagrant@claw:/var/www/html/drupal/web/modules/contrib/islandora$ drush  migrate:import --userid 1 --group migrate_islandora_csv
 [notice] Now acting as user ID 1
 [notice] Processed 0 items (0 created, 0 updated, 0 failed, 0 ignored) - done with 'file'
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'node'
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'media'
 [notice] Switching back from user 1.
```

showing the failed 'file' migration. Without digging too far into `MigrateToolsCommands.php` I'd say your PR works, the problem is with the migration itself. Not sure though.

**Comment by seth-shaw-unlv** [comment]
@mjordan did you run the drush command as a user with write permission to the target directory? E.g. in past migrations I've needed to run it as `sudo -u www-data drush -l http://localhost:8000 mim --userid=1 --all`

**Comment by seth-shaw-unlv** [comment]
@mjordan Also, you can check the migrate messages for more information. Either `drush migrate:messages file` or query the D8 database `select * from migrate_messages_file;` (double-check the table name though).

**Comment by mjordan** [comment]
@seth-shaw-unlv no, I didn't run with `sudo`. I'm rebuilding a box right now to retest. Will report back.

**Comment by mjordan** [comment]
@seth-shaw-unlv worked, but I had some permissions issues on a clean, new Vagrant, which I overcame by running with just `sudo`:

```
sudo -u www-data drush migrate:import --group migrate_islandora_csv --userid=1
 [preflight] Failed to create "/home/vagrant/.drush/cache/factory": mkdir(): Permission denied.
 
 chmod o-w -R /home/vagrant/.drush/cache
```
`chmod o-wx -R /home/vagrant/.drush/cache` didn't work, probably because `www-data` needs permissions on `/home/vagrant`?. Running as super user worked:

```
sudo drush migrate:import --group migrate_islandora_csv --userid=1
 [notice] Now acting as user ID 1
adding in mimetype mappings
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'file'
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'node'
 [notice] Processed 5 items (5 created, 0 updated, 0 failed, 0 ignored) - done with 'media'
 [notice] Switching back from user 1.
```
 
Having super user ownership of the files is not a good situation, but it's fixable.

So, :+1: Nice catch and fix!

**Comment by seth-shaw-unlv** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/pull/108 and https://github.com/Islandora-Devops/claw-playbook/pull/86.
