### ISSUE TITLE
Add descriptions to controlled_access_terms vocabularies

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#991]
Several vocabularies defined in controlled_access_terms need descriptions.  See screenshot below:

![screenshot from 2018-12-19 11-29-44](https://user-images.githubusercontent.com/20773151/50229818-919a8c00-0381-11e9-9685-35c4bdba03f8.png)

Edit each vocab and enter a description.  You can re-export the feature from the UI by visiting http://localhost:8000/admin/config/development/features/edit/controlled_access_terms_default_configuration and hitting the "write" button.

**Comment by manez** [comment]
Welp.. I tried: https://github.com/Islandora-CLAW/controlled_access_terms/pull/17

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/controlled_access_terms/commit/9e191e667bac914b8aaba882421521c5142f2153

Thx @manez
