### ISSUE TITLE
EDTF Changes

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#995]
The EDTF support built into the existing Controlled Access Terms module was written based on [the 2012 pre-submission specification](https://www.loc.gov/standards/datetime/pre-submission.html), level 1. As of [October 22, 2018 the spec was re-released](https://www.loc.gov/standards/datetime/edtf.html) as part of the ISO-8601 rewrite with some significant syntax changes. 

We need to update our EDTF implementation to match Level 1.

**Comment by seth-shaw-unlv** [comment]
I'm working on this right now and I'm going to try to support Level 2. 🤞

**Comment by whikloj** [comment]
@seth-shaw-unlv can this be closed now?
