### ISSUE TITLE
fcrepo Ansible role uses wrong download URL

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#996]
Provisioning a CLAW VM using ansible-role-fcrepo at 5be6f02d9696045fce97ebec22c6d53369f684c1 produces the following failure caused by a 404 on the download URL for the fcrepo war file:

```
TASK [Islandora-Devops.fcrepo : Download fcrepo war] ***************************
Friday 21 December 2018  11:53:18 -0800 (0:00:00.708)       0:33:04.800 ******* 
fatal: [default]: FAILED! => {"changed": false, "dest": "/var/lib/tomcat8/webapps/fcrepo.war", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://github.com/fcrepo4-exts/fcrepo-webapp-plus/releases/download/fcrepo-webapp-plus-5.0.0/fcrepo-webapp-plus-5.0.0.war"}
```

Looks like this is the correct URL: https://github.com/fcrepo4/fcrepo4/releases/download/fcrepo-5.0.0/fcrepo-webapp-5.0.0.war.

I changed the URL template and version numbers in the role at https://github.com/mjordan/ansible-role-fcrepo and updated `requirements.yml` to point to that, and ran `vagrant up` on a clean claw-playbook repo.  Destroying and redeploying vagrant results in a working Islandora. I can open a PR from my fork if you want.

**Comment by whikloj** [comment]
@mjordan we did that in the last PR. You probably need to delete your
roles/external directly and re-provision the box to get the new ansible
role.

**Comment by mjordan** [comment]
Just rebuilt a vagrant after deleting my `claw-playbook` directory and it worked. I was sure I did that earlier and it failed.... so went down the path of updating the URL. At least I learned something abuut Ansible! Sorry for the trouble. Please resume your regularly scheduled holiday prep.
