### ISSUE TITLE
Optimizing composer memory requirements

### ISSUE THREAD

**Issue by mjordan** [Islandora-CLAW/CLAW#997]
I have noticed that running `composer require` to install new modules sometimes consumes all available RAM and craps out. Just noticed [this post](https://www.jeffgeerling.com/blog/2018/make-composer-operations-drupal-way-faster-and-easier-on-ram) from @geerlingguy. I'm happy to test to see if it solves the problems I have encountered. If it does, we should add it to the Vagrant.

**Comment by dannylamb** [comment]
@mjordan YES PLEASE

That's a super annoying one I run into all the time.  My solution thus far has been to shutdown tomcat to free some memory while I run composer :hankey:

**Comment by mjordan** [comment]
Yeah. My solution has been to increase max memory in php.ini, and I think @whikloj adds swap space to his VM.

Ansible newbie question,  but if we're using `geerlingguy.drupal` as per https://github.com/Islandora-Devops/claw-playbook/blob/master/webserver.yml, how do we add `composer require zaporylie/composer-drupal-optimizations:^1.0` ourselves? In https://github.com/Islandora-Devops/claw-playbook/blob/master/roles/internal/webserver-app/tasks/drupal.yml?

**Comment by mjordan** [comment]
PR merged, closing.
